/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as AuthenticatedStoreIdRouteImport } from './routes/_authenticated/$storeId'
import { Route as AuthenticatedStoreIdIndexRouteImport } from './routes/_authenticated/$storeId/index'
import { Route as AuthenticatedStoreIdSettingsRouteImport } from './routes/_authenticated/$storeId/settings'
import { Route as AuthenticatedStoreIdGettingStartedRouteImport } from './routes/_authenticated/$storeId/getting-started'
import { Route as AuthenticatedStoreIdSettingsIndexRouteImport } from './routes/_authenticated/$storeId/settings/index'
import { Route as AuthenticatedStoreIdPromotionsIndexRouteImport } from './routes/_authenticated/$storeId/promotions/index'
import { Route as AuthenticatedStoreIdProductsIndexRouteImport } from './routes/_authenticated/$storeId/products/index'
import { Route as AuthenticatedStoreIdOrdersIndexRouteImport } from './routes/_authenticated/$storeId/orders/index'
import { Route as AuthenticatedStoreIdCustomersIndexRouteImport } from './routes/_authenticated/$storeId/customers/index'
import { Route as AuthenticatedStoreIdSettingsTaxCategoriesRouteImport } from './routes/_authenticated/$storeId/settings/tax-categories'
import { Route as AuthenticatedStoreIdSettingsStoreRouteImport } from './routes/_authenticated/$storeId/settings/store'
import { Route as AuthenticatedStoreIdSettingsStockLocationsRouteImport } from './routes/_authenticated/$storeId/settings/stock-locations'
import { Route as AuthenticatedStoreIdSettingsStaffRouteImport } from './routes/_authenticated/$storeId/settings/staff'
import { Route as AuthenticatedStoreIdSettingsProfileRouteImport } from './routes/_authenticated/$storeId/settings/profile'
import { Route as AuthenticatedStoreIdSettingsPaymentMethodsRouteImport } from './routes/_authenticated/$storeId/settings/payment-methods'
import { Route as AuthenticatedStoreIdSettingsMarketsRouteImport } from './routes/_authenticated/$storeId/settings/markets'
import { Route as AuthenticatedStoreIdSettingsEmailsRouteImport } from './routes/_authenticated/$storeId/settings/emails'
import { Route as AuthenticatedStoreIdSettingsCustomFieldDefinitionsRouteImport } from './routes/_authenticated/$storeId/settings/custom-field-definitions'
import { Route as AuthenticatedStoreIdSettingsChannelsRouteImport } from './routes/_authenticated/$storeId/settings/channels'
import { Route as AuthenticatedStoreIdSettingsApiKeysRouteImport } from './routes/_authenticated/$storeId/settings/api-keys'
import { Route as AuthenticatedStoreIdSettingsAllowedOriginsRouteImport } from './routes/_authenticated/$storeId/settings/allowed-origins'
import { Route as AuthenticatedStoreIdPromotionsNewRouteImport } from './routes/_authenticated/$storeId/promotions/new'
import { Route as AuthenticatedStoreIdPromotionsGiftCardsRouteImport } from './routes/_authenticated/$storeId/promotions/gift-cards'
import { Route as AuthenticatedStoreIdPromotionsPromotionIdRouteImport } from './routes/_authenticated/$storeId/promotions/$promotionId'
import { Route as AuthenticatedStoreIdProductsTransfersRouteImport } from './routes/_authenticated/$storeId/products/transfers'
import { Route as AuthenticatedStoreIdProductsOptionsRouteImport } from './routes/_authenticated/$storeId/products/options'
import { Route as AuthenticatedStoreIdProductsNewRouteImport } from './routes/_authenticated/$storeId/products/new'
import { Route as AuthenticatedStoreIdProductsProductIdRouteImport } from './routes/_authenticated/$storeId/products/$productId'
import { Route as AuthenticatedStoreIdOrdersNewRouteImport } from './routes/_authenticated/$storeId/orders/new'
import { Route as AuthenticatedStoreIdOrdersDraftsRouteImport } from './routes/_authenticated/$storeId/orders/drafts'
import { Route as AuthenticatedStoreIdOrdersOrderIdRouteImport } from './routes/_authenticated/$storeId/orders/$orderId'
import { Route as AuthenticatedStoreIdCustomersGroupsRouteImport } from './routes/_authenticated/$storeId/customers/groups'
import { Route as AuthenticatedStoreIdCustomersCustomerIdRouteImport } from './routes/_authenticated/$storeId/customers/$customerId'
import { Route as AuthenticatedStoreIdSettingsWebhooksIndexRouteImport } from './routes/_authenticated/$storeId/settings/webhooks/index'
import { Route as AuthenticatedStoreIdProductsPriceListsIndexRouteImport } from './routes/_authenticated/$storeId/products/price-lists/index'
import { Route as AuthenticatedStoreIdProductsCategoriesIndexRouteImport } from './routes/_authenticated/$storeId/products/categories/index'
import { Route as AuthenticatedStoreIdSettingsWebhooksWebhookEndpointIdRouteImport } from './routes/_authenticated/$storeId/settings/webhooks/$webhookEndpointId'
import { Route as AuthenticatedStoreIdProductsPriceListsNewRouteImport } from './routes/_authenticated/$storeId/products/price-lists/new'
import { Route as AuthenticatedStoreIdProductsCategoriesNewRouteImport } from './routes/_authenticated/$storeId/products/categories/new'
import { Route as AuthenticatedStoreIdProductsCategoriesCategoryIdRouteImport } from './routes/_authenticated/$storeId/products/categories/$categoryId'
import { Route as AuthenticatedStoreIdProductsPriceListsPriceListIdIndexRouteImport } from './routes/_authenticated/$storeId/products/price-lists/$priceListId/index'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedStoreIdRoute = AuthenticatedStoreIdRouteImport.update({
  id: '/$storeId',
  path: '/$storeId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStoreIdIndexRoute =
  AuthenticatedStoreIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdSettingsRoute =
  AuthenticatedStoreIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdGettingStartedRoute =
  AuthenticatedStoreIdGettingStartedRouteImport.update({
    id: '/getting-started',
    path: '/getting-started',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdSettingsIndexRoute =
  AuthenticatedStoreIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdPromotionsIndexRoute =
  AuthenticatedStoreIdPromotionsIndexRouteImport.update({
    id: '/promotions/',
    path: '/promotions/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdProductsIndexRoute =
  AuthenticatedStoreIdProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdOrdersIndexRoute =
  AuthenticatedStoreIdOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdCustomersIndexRoute =
  AuthenticatedStoreIdCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdSettingsTaxCategoriesRoute =
  AuthenticatedStoreIdSettingsTaxCategoriesRouteImport.update({
    id: '/tax-categories',
    path: '/tax-categories',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdSettingsStoreRoute =
  AuthenticatedStoreIdSettingsStoreRouteImport.update({
    id: '/store',
    path: '/store',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdSettingsStockLocationsRoute =
  AuthenticatedStoreIdSettingsStockLocationsRouteImport.update({
    id: '/stock-locations',
    path: '/stock-locations',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdSettingsStaffRoute =
  AuthenticatedStoreIdSettingsStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdSettingsProfileRoute =
  AuthenticatedStoreIdSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdSettingsPaymentMethodsRoute =
  AuthenticatedStoreIdSettingsPaymentMethodsRouteImport.update({
    id: '/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdSettingsMarketsRoute =
  AuthenticatedStoreIdSettingsMarketsRouteImport.update({
    id: '/markets',
    path: '/markets',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdSettingsEmailsRoute =
  AuthenticatedStoreIdSettingsEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdSettingsCustomFieldDefinitionsRoute =
  AuthenticatedStoreIdSettingsCustomFieldDefinitionsRouteImport.update({
    id: '/custom-field-definitions',
    path: '/custom-field-definitions',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdSettingsChannelsRoute =
  AuthenticatedStoreIdSettingsChannelsRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdSettingsApiKeysRoute =
  AuthenticatedStoreIdSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdSettingsAllowedOriginsRoute =
  AuthenticatedStoreIdSettingsAllowedOriginsRouteImport.update({
    id: '/allowed-origins',
    path: '/allowed-origins',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdPromotionsNewRoute =
  AuthenticatedStoreIdPromotionsNewRouteImport.update({
    id: '/promotions/new',
    path: '/promotions/new',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdPromotionsGiftCardsRoute =
  AuthenticatedStoreIdPromotionsGiftCardsRouteImport.update({
    id: '/promotions/gift-cards',
    path: '/promotions/gift-cards',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdPromotionsPromotionIdRoute =
  AuthenticatedStoreIdPromotionsPromotionIdRouteImport.update({
    id: '/promotions/$promotionId',
    path: '/promotions/$promotionId',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdProductsTransfersRoute =
  AuthenticatedStoreIdProductsTransfersRouteImport.update({
    id: '/products/transfers',
    path: '/products/transfers',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdProductsOptionsRoute =
  AuthenticatedStoreIdProductsOptionsRouteImport.update({
    id: '/products/options',
    path: '/products/options',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdProductsNewRoute =
  AuthenticatedStoreIdProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdProductsProductIdRoute =
  AuthenticatedStoreIdProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdOrdersNewRoute =
  AuthenticatedStoreIdOrdersNewRouteImport.update({
    id: '/orders/new',
    path: '/orders/new',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdOrdersDraftsRoute =
  AuthenticatedStoreIdOrdersDraftsRouteImport.update({
    id: '/orders/drafts',
    path: '/orders/drafts',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdOrdersOrderIdRoute =
  AuthenticatedStoreIdOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdCustomersGroupsRoute =
  AuthenticatedStoreIdCustomersGroupsRouteImport.update({
    id: '/customers/groups',
    path: '/customers/groups',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdCustomersCustomerIdRoute =
  AuthenticatedStoreIdCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdSettingsWebhooksIndexRoute =
  AuthenticatedStoreIdSettingsWebhooksIndexRouteImport.update({
    id: '/webhooks/',
    path: '/webhooks/',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdProductsPriceListsIndexRoute =
  AuthenticatedStoreIdProductsPriceListsIndexRouteImport.update({
    id: '/products/price-lists/',
    path: '/products/price-lists/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdProductsCategoriesIndexRoute =
  AuthenticatedStoreIdProductsCategoriesIndexRouteImport.update({
    id: '/products/categories/',
    path: '/products/categories/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdSettingsWebhooksWebhookEndpointIdRoute =
  AuthenticatedStoreIdSettingsWebhooksWebhookEndpointIdRouteImport.update({
    id: '/webhooks/$webhookEndpointId',
    path: '/webhooks/$webhookEndpointId',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdProductsPriceListsNewRoute =
  AuthenticatedStoreIdProductsPriceListsNewRouteImport.update({
    id: '/products/price-lists/new',
    path: '/products/price-lists/new',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdProductsCategoriesNewRoute =
  AuthenticatedStoreIdProductsCategoriesNewRouteImport.update({
    id: '/products/categories/new',
    path: '/products/categories/new',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdProductsCategoriesCategoryIdRoute =
  AuthenticatedStoreIdProductsCategoriesCategoryIdRouteImport.update({
    id: '/products/categories/$categoryId',
    path: '/products/categories/$categoryId',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdProductsPriceListsPriceListIdIndexRoute =
  AuthenticatedStoreIdProductsPriceListsPriceListIdIndexRouteImport.update({
    id: '/products/price-lists/$priceListId/',
    path: '/products/price-lists/$priceListId/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$storeId': typeof AuthenticatedStoreIdRouteWithChildren
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/$storeId/getting-started': typeof AuthenticatedStoreIdGettingStartedRoute
  '/$storeId/settings': typeof AuthenticatedStoreIdSettingsRouteWithChildren
  '/$storeId/': typeof AuthenticatedStoreIdIndexRoute
  '/$storeId/customers/$customerId': typeof AuthenticatedStoreIdCustomersCustomerIdRoute
  '/$storeId/customers/groups': typeof AuthenticatedStoreIdCustomersGroupsRoute
  '/$storeId/orders/$orderId': typeof AuthenticatedStoreIdOrdersOrderIdRoute
  '/$storeId/orders/drafts': typeof AuthenticatedStoreIdOrdersDraftsRoute
  '/$storeId/orders/new': typeof AuthenticatedStoreIdOrdersNewRoute
  '/$storeId/products/$productId': typeof AuthenticatedStoreIdProductsProductIdRoute
  '/$storeId/products/new': typeof AuthenticatedStoreIdProductsNewRoute
  '/$storeId/products/options': typeof AuthenticatedStoreIdProductsOptionsRoute
  '/$storeId/products/transfers': typeof AuthenticatedStoreIdProductsTransfersRoute
  '/$storeId/promotions/$promotionId': typeof AuthenticatedStoreIdPromotionsPromotionIdRoute
  '/$storeId/promotions/gift-cards': typeof AuthenticatedStoreIdPromotionsGiftCardsRoute
  '/$storeId/promotions/new': typeof AuthenticatedStoreIdPromotionsNewRoute
  '/$storeId/settings/allowed-origins': typeof AuthenticatedStoreIdSettingsAllowedOriginsRoute
  '/$storeId/settings/api-keys': typeof AuthenticatedStoreIdSettingsApiKeysRoute
  '/$storeId/settings/channels': typeof AuthenticatedStoreIdSettingsChannelsRoute
  '/$storeId/settings/custom-field-definitions': typeof AuthenticatedStoreIdSettingsCustomFieldDefinitionsRoute
  '/$storeId/settings/emails': typeof AuthenticatedStoreIdSettingsEmailsRoute
  '/$storeId/settings/markets': typeof AuthenticatedStoreIdSettingsMarketsRoute
  '/$storeId/settings/payment-methods': typeof AuthenticatedStoreIdSettingsPaymentMethodsRoute
  '/$storeId/settings/profile': typeof AuthenticatedStoreIdSettingsProfileRoute
  '/$storeId/settings/staff': typeof AuthenticatedStoreIdSettingsStaffRoute
  '/$storeId/settings/stock-locations': typeof AuthenticatedStoreIdSettingsStockLocationsRoute
  '/$storeId/settings/store': typeof AuthenticatedStoreIdSettingsStoreRoute
  '/$storeId/settings/tax-categories': typeof AuthenticatedStoreIdSettingsTaxCategoriesRoute
  '/$storeId/customers/': typeof AuthenticatedStoreIdCustomersIndexRoute
  '/$storeId/orders/': typeof AuthenticatedStoreIdOrdersIndexRoute
  '/$storeId/products/': typeof AuthenticatedStoreIdProductsIndexRoute
  '/$storeId/promotions/': typeof AuthenticatedStoreIdPromotionsIndexRoute
  '/$storeId/settings/': typeof AuthenticatedStoreIdSettingsIndexRoute
  '/$storeId/products/categories/$categoryId': typeof AuthenticatedStoreIdProductsCategoriesCategoryIdRoute
  '/$storeId/products/categories/new': typeof AuthenticatedStoreIdProductsCategoriesNewRoute
  '/$storeId/products/price-lists/new': typeof AuthenticatedStoreIdProductsPriceListsNewRoute
  '/$storeId/settings/webhooks/$webhookEndpointId': typeof AuthenticatedStoreIdSettingsWebhooksWebhookEndpointIdRoute
  '/$storeId/products/categories/': typeof AuthenticatedStoreIdProductsCategoriesIndexRoute
  '/$storeId/products/price-lists/': typeof AuthenticatedStoreIdProductsPriceListsIndexRoute
  '/$storeId/settings/webhooks/': typeof AuthenticatedStoreIdSettingsWebhooksIndexRoute
  '/$storeId/products/price-lists/$priceListId/': typeof AuthenticatedStoreIdProductsPriceListsPriceListIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/$storeId/getting-started': typeof AuthenticatedStoreIdGettingStartedRoute
  '/$storeId': typeof AuthenticatedStoreIdIndexRoute
  '/$storeId/customers/$customerId': typeof AuthenticatedStoreIdCustomersCustomerIdRoute
  '/$storeId/customers/groups': typeof AuthenticatedStoreIdCustomersGroupsRoute
  '/$storeId/orders/$orderId': typeof AuthenticatedStoreIdOrdersOrderIdRoute
  '/$storeId/orders/drafts': typeof AuthenticatedStoreIdOrdersDraftsRoute
  '/$storeId/orders/new': typeof AuthenticatedStoreIdOrdersNewRoute
  '/$storeId/products/$productId': typeof AuthenticatedStoreIdProductsProductIdRoute
  '/$storeId/products/new': typeof AuthenticatedStoreIdProductsNewRoute
  '/$storeId/products/options': typeof AuthenticatedStoreIdProductsOptionsRoute
  '/$storeId/products/transfers': typeof AuthenticatedStoreIdProductsTransfersRoute
  '/$storeId/promotions/$promotionId': typeof AuthenticatedStoreIdPromotionsPromotionIdRoute
  '/$storeId/promotions/gift-cards': typeof AuthenticatedStoreIdPromotionsGiftCardsRoute
  '/$storeId/promotions/new': typeof AuthenticatedStoreIdPromotionsNewRoute
  '/$storeId/settings/allowed-origins': typeof AuthenticatedStoreIdSettingsAllowedOriginsRoute
  '/$storeId/settings/api-keys': typeof AuthenticatedStoreIdSettingsApiKeysRoute
  '/$storeId/settings/channels': typeof AuthenticatedStoreIdSettingsChannelsRoute
  '/$storeId/settings/custom-field-definitions': typeof AuthenticatedStoreIdSettingsCustomFieldDefinitionsRoute
  '/$storeId/settings/emails': typeof AuthenticatedStoreIdSettingsEmailsRoute
  '/$storeId/settings/markets': typeof AuthenticatedStoreIdSettingsMarketsRoute
  '/$storeId/settings/payment-methods': typeof AuthenticatedStoreIdSettingsPaymentMethodsRoute
  '/$storeId/settings/profile': typeof AuthenticatedStoreIdSettingsProfileRoute
  '/$storeId/settings/staff': typeof AuthenticatedStoreIdSettingsStaffRoute
  '/$storeId/settings/stock-locations': typeof AuthenticatedStoreIdSettingsStockLocationsRoute
  '/$storeId/settings/store': typeof AuthenticatedStoreIdSettingsStoreRoute
  '/$storeId/settings/tax-categories': typeof AuthenticatedStoreIdSettingsTaxCategoriesRoute
  '/$storeId/customers': typeof AuthenticatedStoreIdCustomersIndexRoute
  '/$storeId/orders': typeof AuthenticatedStoreIdOrdersIndexRoute
  '/$storeId/products': typeof AuthenticatedStoreIdProductsIndexRoute
  '/$storeId/promotions': typeof AuthenticatedStoreIdPromotionsIndexRoute
  '/$storeId/settings': typeof AuthenticatedStoreIdSettingsIndexRoute
  '/$storeId/products/categories/$categoryId': typeof AuthenticatedStoreIdProductsCategoriesCategoryIdRoute
  '/$storeId/products/categories/new': typeof AuthenticatedStoreIdProductsCategoriesNewRoute
  '/$storeId/products/price-lists/new': typeof AuthenticatedStoreIdProductsPriceListsNewRoute
  '/$storeId/settings/webhooks/$webhookEndpointId': typeof AuthenticatedStoreIdSettingsWebhooksWebhookEndpointIdRoute
  '/$storeId/products/categories': typeof AuthenticatedStoreIdProductsCategoriesIndexRoute
  '/$storeId/products/price-lists': typeof AuthenticatedStoreIdProductsPriceListsIndexRoute
  '/$storeId/settings/webhooks': typeof AuthenticatedStoreIdSettingsWebhooksIndexRoute
  '/$storeId/products/price-lists/$priceListId': typeof AuthenticatedStoreIdProductsPriceListsPriceListIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/$storeId': typeof AuthenticatedStoreIdRouteWithChildren
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$storeId/getting-started': typeof AuthenticatedStoreIdGettingStartedRoute
  '/_authenticated/$storeId/settings': typeof AuthenticatedStoreIdSettingsRouteWithChildren
  '/_authenticated/$storeId/': typeof AuthenticatedStoreIdIndexRoute
  '/_authenticated/$storeId/customers/$customerId': typeof AuthenticatedStoreIdCustomersCustomerIdRoute
  '/_authenticated/$storeId/customers/groups': typeof AuthenticatedStoreIdCustomersGroupsRoute
  '/_authenticated/$storeId/orders/$orderId': typeof AuthenticatedStoreIdOrdersOrderIdRoute
  '/_authenticated/$storeId/orders/drafts': typeof AuthenticatedStoreIdOrdersDraftsRoute
  '/_authenticated/$storeId/orders/new': typeof AuthenticatedStoreIdOrdersNewRoute
  '/_authenticated/$storeId/products/$productId': typeof AuthenticatedStoreIdProductsProductIdRoute
  '/_authenticated/$storeId/products/new': typeof AuthenticatedStoreIdProductsNewRoute
  '/_authenticated/$storeId/products/options': typeof AuthenticatedStoreIdProductsOptionsRoute
  '/_authenticated/$storeId/products/transfers': typeof AuthenticatedStoreIdProductsTransfersRoute
  '/_authenticated/$storeId/promotions/$promotionId': typeof AuthenticatedStoreIdPromotionsPromotionIdRoute
  '/_authenticated/$storeId/promotions/gift-cards': typeof AuthenticatedStoreIdPromotionsGiftCardsRoute
  '/_authenticated/$storeId/promotions/new': typeof AuthenticatedStoreIdPromotionsNewRoute
  '/_authenticated/$storeId/settings/allowed-origins': typeof AuthenticatedStoreIdSettingsAllowedOriginsRoute
  '/_authenticated/$storeId/settings/api-keys': typeof AuthenticatedStoreIdSettingsApiKeysRoute
  '/_authenticated/$storeId/settings/channels': typeof AuthenticatedStoreIdSettingsChannelsRoute
  '/_authenticated/$storeId/settings/custom-field-definitions': typeof AuthenticatedStoreIdSettingsCustomFieldDefinitionsRoute
  '/_authenticated/$storeId/settings/emails': typeof AuthenticatedStoreIdSettingsEmailsRoute
  '/_authenticated/$storeId/settings/markets': typeof AuthenticatedStoreIdSettingsMarketsRoute
  '/_authenticated/$storeId/settings/payment-methods': typeof AuthenticatedStoreIdSettingsPaymentMethodsRoute
  '/_authenticated/$storeId/settings/profile': typeof AuthenticatedStoreIdSettingsProfileRoute
  '/_authenticated/$storeId/settings/staff': typeof AuthenticatedStoreIdSettingsStaffRoute
  '/_authenticated/$storeId/settings/stock-locations': typeof AuthenticatedStoreIdSettingsStockLocationsRoute
  '/_authenticated/$storeId/settings/store': typeof AuthenticatedStoreIdSettingsStoreRoute
  '/_authenticated/$storeId/settings/tax-categories': typeof AuthenticatedStoreIdSettingsTaxCategoriesRoute
  '/_authenticated/$storeId/customers/': typeof AuthenticatedStoreIdCustomersIndexRoute
  '/_authenticated/$storeId/orders/': typeof AuthenticatedStoreIdOrdersIndexRoute
  '/_authenticated/$storeId/products/': typeof AuthenticatedStoreIdProductsIndexRoute
  '/_authenticated/$storeId/promotions/': typeof AuthenticatedStoreIdPromotionsIndexRoute
  '/_authenticated/$storeId/settings/': typeof AuthenticatedStoreIdSettingsIndexRoute
  '/_authenticated/$storeId/products/categories/$categoryId': typeof AuthenticatedStoreIdProductsCategoriesCategoryIdRoute
  '/_authenticated/$storeId/products/categories/new': typeof AuthenticatedStoreIdProductsCategoriesNewRoute
  '/_authenticated/$storeId/products/price-lists/new': typeof AuthenticatedStoreIdProductsPriceListsNewRoute
  '/_authenticated/$storeId/settings/webhooks/$webhookEndpointId': typeof AuthenticatedStoreIdSettingsWebhooksWebhookEndpointIdRoute
  '/_authenticated/$storeId/products/categories/': typeof AuthenticatedStoreIdProductsCategoriesIndexRoute
  '/_authenticated/$storeId/products/price-lists/': typeof AuthenticatedStoreIdProductsPriceListsIndexRoute
  '/_authenticated/$storeId/settings/webhooks/': typeof AuthenticatedStoreIdSettingsWebhooksIndexRoute
  '/_authenticated/$storeId/products/price-lists/$priceListId/': typeof AuthenticatedStoreIdProductsPriceListsPriceListIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/$storeId'
    | '/accept-invitation/$invitationId'
    | '/$storeId/getting-started'
    | '/$storeId/settings'
    | '/$storeId/'
    | '/$storeId/customers/$customerId'
    | '/$storeId/customers/groups'
    | '/$storeId/orders/$orderId'
    | '/$storeId/orders/drafts'
    | '/$storeId/orders/new'
    | '/$storeId/products/$productId'
    | '/$storeId/products/new'
    | '/$storeId/products/options'
    | '/$storeId/products/transfers'
    | '/$storeId/promotions/$promotionId'
    | '/$storeId/promotions/gift-cards'
    | '/$storeId/promotions/new'
    | '/$storeId/settings/allowed-origins'
    | '/$storeId/settings/api-keys'
    | '/$storeId/settings/channels'
    | '/$storeId/settings/custom-field-definitions'
    | '/$storeId/settings/emails'
    | '/$storeId/settings/markets'
    | '/$storeId/settings/payment-methods'
    | '/$storeId/settings/profile'
    | '/$storeId/settings/staff'
    | '/$storeId/settings/stock-locations'
    | '/$storeId/settings/store'
    | '/$storeId/settings/tax-categories'
    | '/$storeId/customers/'
    | '/$storeId/orders/'
    | '/$storeId/products/'
    | '/$storeId/promotions/'
    | '/$storeId/settings/'
    | '/$storeId/products/categories/$categoryId'
    | '/$storeId/products/categories/new'
    | '/$storeId/products/price-lists/new'
    | '/$storeId/settings/webhooks/$webhookEndpointId'
    | '/$storeId/products/categories/'
    | '/$storeId/products/price-lists/'
    | '/$storeId/settings/webhooks/'
    | '/$storeId/products/price-lists/$priceListId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/accept-invitation/$invitationId'
    | '/'
    | '/$storeId/getting-started'
    | '/$storeId'
    | '/$storeId/customers/$customerId'
    | '/$storeId/customers/groups'
    | '/$storeId/orders/$orderId'
    | '/$storeId/orders/drafts'
    | '/$storeId/orders/new'
    | '/$storeId/products/$productId'
    | '/$storeId/products/new'
    | '/$storeId/products/options'
    | '/$storeId/products/transfers'
    | '/$storeId/promotions/$promotionId'
    | '/$storeId/promotions/gift-cards'
    | '/$storeId/promotions/new'
    | '/$storeId/settings/allowed-origins'
    | '/$storeId/settings/api-keys'
    | '/$storeId/settings/channels'
    | '/$storeId/settings/custom-field-definitions'
    | '/$storeId/settings/emails'
    | '/$storeId/settings/markets'
    | '/$storeId/settings/payment-methods'
    | '/$storeId/settings/profile'
    | '/$storeId/settings/staff'
    | '/$storeId/settings/stock-locations'
    | '/$storeId/settings/store'
    | '/$storeId/settings/tax-categories'
    | '/$storeId/customers'
    | '/$storeId/orders'
    | '/$storeId/products'
    | '/$storeId/promotions'
    | '/$storeId/settings'
    | '/$storeId/products/categories/$categoryId'
    | '/$storeId/products/categories/new'
    | '/$storeId/products/price-lists/new'
    | '/$storeId/settings/webhooks/$webhookEndpointId'
    | '/$storeId/products/categories'
    | '/$storeId/products/price-lists'
    | '/$storeId/settings/webhooks'
    | '/$storeId/products/price-lists/$priceListId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/$storeId'
    | '/accept-invitation/$invitationId'
    | '/_authenticated/'
    | '/_authenticated/$storeId/getting-started'
    | '/_authenticated/$storeId/settings'
    | '/_authenticated/$storeId/'
    | '/_authenticated/$storeId/customers/$customerId'
    | '/_authenticated/$storeId/customers/groups'
    | '/_authenticated/$storeId/orders/$orderId'
    | '/_authenticated/$storeId/orders/drafts'
    | '/_authenticated/$storeId/orders/new'
    | '/_authenticated/$storeId/products/$productId'
    | '/_authenticated/$storeId/products/new'
    | '/_authenticated/$storeId/products/options'
    | '/_authenticated/$storeId/products/transfers'
    | '/_authenticated/$storeId/promotions/$promotionId'
    | '/_authenticated/$storeId/promotions/gift-cards'
    | '/_authenticated/$storeId/promotions/new'
    | '/_authenticated/$storeId/settings/allowed-origins'
    | '/_authenticated/$storeId/settings/api-keys'
    | '/_authenticated/$storeId/settings/channels'
    | '/_authenticated/$storeId/settings/custom-field-definitions'
    | '/_authenticated/$storeId/settings/emails'
    | '/_authenticated/$storeId/settings/markets'
    | '/_authenticated/$storeId/settings/payment-methods'
    | '/_authenticated/$storeId/settings/profile'
    | '/_authenticated/$storeId/settings/staff'
    | '/_authenticated/$storeId/settings/stock-locations'
    | '/_authenticated/$storeId/settings/store'
    | '/_authenticated/$storeId/settings/tax-categories'
    | '/_authenticated/$storeId/customers/'
    | '/_authenticated/$storeId/orders/'
    | '/_authenticated/$storeId/products/'
    | '/_authenticated/$storeId/promotions/'
    | '/_authenticated/$storeId/settings/'
    | '/_authenticated/$storeId/products/categories/$categoryId'
    | '/_authenticated/$storeId/products/categories/new'
    | '/_authenticated/$storeId/products/price-lists/new'
    | '/_authenticated/$storeId/settings/webhooks/$webhookEndpointId'
    | '/_authenticated/$storeId/products/categories/'
    | '/_authenticated/$storeId/products/price-lists/'
    | '/_authenticated/$storeId/settings/webhooks/'
    | '/_authenticated/$storeId/products/price-lists/$priceListId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$storeId': {
      id: '/_authenticated/$storeId'
      path: '/$storeId'
      fullPath: '/$storeId'
      preLoaderRoute: typeof AuthenticatedStoreIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$storeId/': {
      id: '/_authenticated/$storeId/'
      path: '/'
      fullPath: '/$storeId/'
      preLoaderRoute: typeof AuthenticatedStoreIdIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/settings': {
      id: '/_authenticated/$storeId/settings'
      path: '/settings'
      fullPath: '/$storeId/settings'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/getting-started': {
      id: '/_authenticated/$storeId/getting-started'
      path: '/getting-started'
      fullPath: '/$storeId/getting-started'
      preLoaderRoute: typeof AuthenticatedStoreIdGettingStartedRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/settings/': {
      id: '/_authenticated/$storeId/settings/'
      path: '/'
      fullPath: '/$storeId/settings/'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/promotions/': {
      id: '/_authenticated/$storeId/promotions/'
      path: '/promotions'
      fullPath: '/$storeId/promotions/'
      preLoaderRoute: typeof AuthenticatedStoreIdPromotionsIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/': {
      id: '/_authenticated/$storeId/products/'
      path: '/products'
      fullPath: '/$storeId/products/'
      preLoaderRoute: typeof AuthenticatedStoreIdProductsIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/orders/': {
      id: '/_authenticated/$storeId/orders/'
      path: '/orders'
      fullPath: '/$storeId/orders/'
      preLoaderRoute: typeof AuthenticatedStoreIdOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/customers/': {
      id: '/_authenticated/$storeId/customers/'
      path: '/customers'
      fullPath: '/$storeId/customers/'
      preLoaderRoute: typeof AuthenticatedStoreIdCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/settings/tax-categories': {
      id: '/_authenticated/$storeId/settings/tax-categories'
      path: '/tax-categories'
      fullPath: '/$storeId/settings/tax-categories'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsTaxCategoriesRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/settings/store': {
      id: '/_authenticated/$storeId/settings/store'
      path: '/store'
      fullPath: '/$storeId/settings/store'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsStoreRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/settings/stock-locations': {
      id: '/_authenticated/$storeId/settings/stock-locations'
      path: '/stock-locations'
      fullPath: '/$storeId/settings/stock-locations'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsStockLocationsRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/settings/staff': {
      id: '/_authenticated/$storeId/settings/staff'
      path: '/staff'
      fullPath: '/$storeId/settings/staff'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsStaffRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/settings/profile': {
      id: '/_authenticated/$storeId/settings/profile'
      path: '/profile'
      fullPath: '/$storeId/settings/profile'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/settings/payment-methods': {
      id: '/_authenticated/$storeId/settings/payment-methods'
      path: '/payment-methods'
      fullPath: '/$storeId/settings/payment-methods'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsPaymentMethodsRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/settings/markets': {
      id: '/_authenticated/$storeId/settings/markets'
      path: '/markets'
      fullPath: '/$storeId/settings/markets'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsMarketsRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/settings/emails': {
      id: '/_authenticated/$storeId/settings/emails'
      path: '/emails'
      fullPath: '/$storeId/settings/emails'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsEmailsRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/settings/custom-field-definitions': {
      id: '/_authenticated/$storeId/settings/custom-field-definitions'
      path: '/custom-field-definitions'
      fullPath: '/$storeId/settings/custom-field-definitions'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsCustomFieldDefinitionsRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/settings/channels': {
      id: '/_authenticated/$storeId/settings/channels'
      path: '/channels'
      fullPath: '/$storeId/settings/channels'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsChannelsRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/settings/api-keys': {
      id: '/_authenticated/$storeId/settings/api-keys'
      path: '/api-keys'
      fullPath: '/$storeId/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/settings/allowed-origins': {
      id: '/_authenticated/$storeId/settings/allowed-origins'
      path: '/allowed-origins'
      fullPath: '/$storeId/settings/allowed-origins'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsAllowedOriginsRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/promotions/new': {
      id: '/_authenticated/$storeId/promotions/new'
      path: '/promotions/new'
      fullPath: '/$storeId/promotions/new'
      preLoaderRoute: typeof AuthenticatedStoreIdPromotionsNewRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/promotions/gift-cards': {
      id: '/_authenticated/$storeId/promotions/gift-cards'
      path: '/promotions/gift-cards'
      fullPath: '/$storeId/promotions/gift-cards'
      preLoaderRoute: typeof AuthenticatedStoreIdPromotionsGiftCardsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/promotions/$promotionId': {
      id: '/_authenticated/$storeId/promotions/$promotionId'
      path: '/promotions/$promotionId'
      fullPath: '/$storeId/promotions/$promotionId'
      preLoaderRoute: typeof AuthenticatedStoreIdPromotionsPromotionIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/transfers': {
      id: '/_authenticated/$storeId/products/transfers'
      path: '/products/transfers'
      fullPath: '/$storeId/products/transfers'
      preLoaderRoute: typeof AuthenticatedStoreIdProductsTransfersRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/options': {
      id: '/_authenticated/$storeId/products/options'
      path: '/products/options'
      fullPath: '/$storeId/products/options'
      preLoaderRoute: typeof AuthenticatedStoreIdProductsOptionsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/new': {
      id: '/_authenticated/$storeId/products/new'
      path: '/products/new'
      fullPath: '/$storeId/products/new'
      preLoaderRoute: typeof AuthenticatedStoreIdProductsNewRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/$productId': {
      id: '/_authenticated/$storeId/products/$productId'
      path: '/products/$productId'
      fullPath: '/$storeId/products/$productId'
      preLoaderRoute: typeof AuthenticatedStoreIdProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/orders/new': {
      id: '/_authenticated/$storeId/orders/new'
      path: '/orders/new'
      fullPath: '/$storeId/orders/new'
      preLoaderRoute: typeof AuthenticatedStoreIdOrdersNewRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/orders/drafts': {
      id: '/_authenticated/$storeId/orders/drafts'
      path: '/orders/drafts'
      fullPath: '/$storeId/orders/drafts'
      preLoaderRoute: typeof AuthenticatedStoreIdOrdersDraftsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/orders/$orderId': {
      id: '/_authenticated/$storeId/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/$storeId/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedStoreIdOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/customers/groups': {
      id: '/_authenticated/$storeId/customers/groups'
      path: '/customers/groups'
      fullPath: '/$storeId/customers/groups'
      preLoaderRoute: typeof AuthenticatedStoreIdCustomersGroupsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/customers/$customerId': {
      id: '/_authenticated/$storeId/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/$storeId/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedStoreIdCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/settings/webhooks/': {
      id: '/_authenticated/$storeId/settings/webhooks/'
      path: '/webhooks'
      fullPath: '/$storeId/settings/webhooks/'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsWebhooksIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/products/price-lists/': {
      id: '/_authenticated/$storeId/products/price-lists/'
      path: '/products/price-lists'
      fullPath: '/$storeId/products/price-lists/'
      preLoaderRoute: typeof AuthenticatedStoreIdProductsPriceListsIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/categories/': {
      id: '/_authenticated/$storeId/products/categories/'
      path: '/products/categories'
      fullPath: '/$storeId/products/categories/'
      preLoaderRoute: typeof AuthenticatedStoreIdProductsCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/settings/webhooks/$webhookEndpointId': {
      id: '/_authenticated/$storeId/settings/webhooks/$webhookEndpointId'
      path: '/webhooks/$webhookEndpointId'
      fullPath: '/$storeId/settings/webhooks/$webhookEndpointId'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsWebhooksWebhookEndpointIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/products/price-lists/new': {
      id: '/_authenticated/$storeId/products/price-lists/new'
      path: '/products/price-lists/new'
      fullPath: '/$storeId/products/price-lists/new'
      preLoaderRoute: typeof AuthenticatedStoreIdProductsPriceListsNewRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/categories/new': {
      id: '/_authenticated/$storeId/products/categories/new'
      path: '/products/categories/new'
      fullPath: '/$storeId/products/categories/new'
      preLoaderRoute: typeof AuthenticatedStoreIdProductsCategoriesNewRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/categories/$categoryId': {
      id: '/_authenticated/$storeId/products/categories/$categoryId'
      path: '/products/categories/$categoryId'
      fullPath: '/$storeId/products/categories/$categoryId'
      preLoaderRoute: typeof AuthenticatedStoreIdProductsCategoriesCategoryIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/price-lists/$priceListId/': {
      id: '/_authenticated/$storeId/products/price-lists/$priceListId/'
      path: '/products/price-lists/$priceListId'
      fullPath: '/$storeId/products/price-lists/$priceListId/'
      preLoaderRoute: typeof AuthenticatedStoreIdProductsPriceListsPriceListIdIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
  }
}

interface AuthenticatedStoreIdSettingsRouteChildren {
  AuthenticatedStoreIdSettingsAllowedOriginsRoute: typeof AuthenticatedStoreIdSettingsAllowedOriginsRoute
  AuthenticatedStoreIdSettingsApiKeysRoute: typeof AuthenticatedStoreIdSettingsApiKeysRoute
  AuthenticatedStoreIdSettingsChannelsRoute: typeof AuthenticatedStoreIdSettingsChannelsRoute
  AuthenticatedStoreIdSettingsCustomFieldDefinitionsRoute: typeof AuthenticatedStoreIdSettingsCustomFieldDefinitionsRoute
  AuthenticatedStoreIdSettingsEmailsRoute: typeof AuthenticatedStoreIdSettingsEmailsRoute
  AuthenticatedStoreIdSettingsMarketsRoute: typeof AuthenticatedStoreIdSettingsMarketsRoute
  AuthenticatedStoreIdSettingsPaymentMethodsRoute: typeof AuthenticatedStoreIdSettingsPaymentMethodsRoute
  AuthenticatedStoreIdSettingsProfileRoute: typeof AuthenticatedStoreIdSettingsProfileRoute
  AuthenticatedStoreIdSettingsStaffRoute: typeof AuthenticatedStoreIdSettingsStaffRoute
  AuthenticatedStoreIdSettingsStockLocationsRoute: typeof AuthenticatedStoreIdSettingsStockLocationsRoute
  AuthenticatedStoreIdSettingsStoreRoute: typeof AuthenticatedStoreIdSettingsStoreRoute
  AuthenticatedStoreIdSettingsTaxCategoriesRoute: typeof AuthenticatedStoreIdSettingsTaxCategoriesRoute
  AuthenticatedStoreIdSettingsIndexRoute: typeof AuthenticatedStoreIdSettingsIndexRoute
  AuthenticatedStoreIdSettingsWebhooksWebhookEndpointIdRoute: typeof AuthenticatedStoreIdSettingsWebhooksWebhookEndpointIdRoute
  AuthenticatedStoreIdSettingsWebhooksIndexRoute: typeof AuthenticatedStoreIdSettingsWebhooksIndexRoute
}

const AuthenticatedStoreIdSettingsRouteChildren: AuthenticatedStoreIdSettingsRouteChildren =
  {
    AuthenticatedStoreIdSettingsAllowedOriginsRoute:
      AuthenticatedStoreIdSettingsAllowedOriginsRoute,
    AuthenticatedStoreIdSettingsApiKeysRoute:
      AuthenticatedStoreIdSettingsApiKeysRoute,
    AuthenticatedStoreIdSettingsChannelsRoute:
      AuthenticatedStoreIdSettingsChannelsRoute,
    AuthenticatedStoreIdSettingsCustomFieldDefinitionsRoute:
      AuthenticatedStoreIdSettingsCustomFieldDefinitionsRoute,
    AuthenticatedStoreIdSettingsEmailsRoute:
      AuthenticatedStoreIdSettingsEmailsRoute,
    AuthenticatedStoreIdSettingsMarketsRoute:
      AuthenticatedStoreIdSettingsMarketsRoute,
    AuthenticatedStoreIdSettingsPaymentMethodsRoute:
      AuthenticatedStoreIdSettingsPaymentMethodsRoute,
    AuthenticatedStoreIdSettingsProfileRoute:
      AuthenticatedStoreIdSettingsProfileRoute,
    AuthenticatedStoreIdSettingsStaffRoute:
      AuthenticatedStoreIdSettingsStaffRoute,
    AuthenticatedStoreIdSettingsStockLocationsRoute:
      AuthenticatedStoreIdSettingsStockLocationsRoute,
    AuthenticatedStoreIdSettingsStoreRoute:
      AuthenticatedStoreIdSettingsStoreRoute,
    AuthenticatedStoreIdSettingsTaxCategoriesRoute:
      AuthenticatedStoreIdSettingsTaxCategoriesRoute,
    AuthenticatedStoreIdSettingsIndexRoute:
      AuthenticatedStoreIdSettingsIndexRoute,
    AuthenticatedStoreIdSettingsWebhooksWebhookEndpointIdRoute:
      AuthenticatedStoreIdSettingsWebhooksWebhookEndpointIdRoute,
    AuthenticatedStoreIdSettingsWebhooksIndexRoute:
      AuthenticatedStoreIdSettingsWebhooksIndexRoute,
  }

const AuthenticatedStoreIdSettingsRouteWithChildren =
  AuthenticatedStoreIdSettingsRoute._addFileChildren(
    AuthenticatedStoreIdSettingsRouteChildren,
  )

interface AuthenticatedStoreIdRouteChildren {
  AuthenticatedStoreIdGettingStartedRoute: typeof AuthenticatedStoreIdGettingStartedRoute
  AuthenticatedStoreIdSettingsRoute: typeof AuthenticatedStoreIdSettingsRouteWithChildren
  AuthenticatedStoreIdIndexRoute: typeof AuthenticatedStoreIdIndexRoute
  AuthenticatedStoreIdCustomersCustomerIdRoute: typeof AuthenticatedStoreIdCustomersCustomerIdRoute
  AuthenticatedStoreIdCustomersGroupsRoute: typeof AuthenticatedStoreIdCustomersGroupsRoute
  AuthenticatedStoreIdOrdersOrderIdRoute: typeof AuthenticatedStoreIdOrdersOrderIdRoute
  AuthenticatedStoreIdOrdersDraftsRoute: typeof AuthenticatedStoreIdOrdersDraftsRoute
  AuthenticatedStoreIdOrdersNewRoute: typeof AuthenticatedStoreIdOrdersNewRoute
  AuthenticatedStoreIdProductsProductIdRoute: typeof AuthenticatedStoreIdProductsProductIdRoute
  AuthenticatedStoreIdProductsNewRoute: typeof AuthenticatedStoreIdProductsNewRoute
  AuthenticatedStoreIdProductsOptionsRoute: typeof AuthenticatedStoreIdProductsOptionsRoute
  AuthenticatedStoreIdProductsTransfersRoute: typeof AuthenticatedStoreIdProductsTransfersRoute
  AuthenticatedStoreIdPromotionsPromotionIdRoute: typeof AuthenticatedStoreIdPromotionsPromotionIdRoute
  AuthenticatedStoreIdPromotionsGiftCardsRoute: typeof AuthenticatedStoreIdPromotionsGiftCardsRoute
  AuthenticatedStoreIdPromotionsNewRoute: typeof AuthenticatedStoreIdPromotionsNewRoute
  AuthenticatedStoreIdCustomersIndexRoute: typeof AuthenticatedStoreIdCustomersIndexRoute
  AuthenticatedStoreIdOrdersIndexRoute: typeof AuthenticatedStoreIdOrdersIndexRoute
  AuthenticatedStoreIdProductsIndexRoute: typeof AuthenticatedStoreIdProductsIndexRoute
  AuthenticatedStoreIdPromotionsIndexRoute: typeof AuthenticatedStoreIdPromotionsIndexRoute
  AuthenticatedStoreIdProductsCategoriesCategoryIdRoute: typeof AuthenticatedStoreIdProductsCategoriesCategoryIdRoute
  AuthenticatedStoreIdProductsCategoriesNewRoute: typeof AuthenticatedStoreIdProductsCategoriesNewRoute
  AuthenticatedStoreIdProductsPriceListsNewRoute: typeof AuthenticatedStoreIdProductsPriceListsNewRoute
  AuthenticatedStoreIdProductsCategoriesIndexRoute: typeof AuthenticatedStoreIdProductsCategoriesIndexRoute
  AuthenticatedStoreIdProductsPriceListsIndexRoute: typeof AuthenticatedStoreIdProductsPriceListsIndexRoute
  AuthenticatedStoreIdProductsPriceListsPriceListIdIndexRoute: typeof AuthenticatedStoreIdProductsPriceListsPriceListIdIndexRoute
}

const AuthenticatedStoreIdRouteChildren: AuthenticatedStoreIdRouteChildren = {
  AuthenticatedStoreIdGettingStartedRoute:
    AuthenticatedStoreIdGettingStartedRoute,
  AuthenticatedStoreIdSettingsRoute:
    AuthenticatedStoreIdSettingsRouteWithChildren,
  AuthenticatedStoreIdIndexRoute: AuthenticatedStoreIdIndexRoute,
  AuthenticatedStoreIdCustomersCustomerIdRoute:
    AuthenticatedStoreIdCustomersCustomerIdRoute,
  AuthenticatedStoreIdCustomersGroupsRoute:
    AuthenticatedStoreIdCustomersGroupsRoute,
  AuthenticatedStoreIdOrdersOrderIdRoute:
    AuthenticatedStoreIdOrdersOrderIdRoute,
  AuthenticatedStoreIdOrdersDraftsRoute: AuthenticatedStoreIdOrdersDraftsRoute,
  AuthenticatedStoreIdOrdersNewRoute: AuthenticatedStoreIdOrdersNewRoute,
  AuthenticatedStoreIdProductsProductIdRoute:
    AuthenticatedStoreIdProductsProductIdRoute,
  AuthenticatedStoreIdProductsNewRoute: AuthenticatedStoreIdProductsNewRoute,
  AuthenticatedStoreIdProductsOptionsRoute:
    AuthenticatedStoreIdProductsOptionsRoute,
  AuthenticatedStoreIdProductsTransfersRoute:
    AuthenticatedStoreIdProductsTransfersRoute,
  AuthenticatedStoreIdPromotionsPromotionIdRoute:
    AuthenticatedStoreIdPromotionsPromotionIdRoute,
  AuthenticatedStoreIdPromotionsGiftCardsRoute:
    AuthenticatedStoreIdPromotionsGiftCardsRoute,
  AuthenticatedStoreIdPromotionsNewRoute:
    AuthenticatedStoreIdPromotionsNewRoute,
  AuthenticatedStoreIdCustomersIndexRoute:
    AuthenticatedStoreIdCustomersIndexRoute,
  AuthenticatedStoreIdOrdersIndexRoute: AuthenticatedStoreIdOrdersIndexRoute,
  AuthenticatedStoreIdProductsIndexRoute:
    AuthenticatedStoreIdProductsIndexRoute,
  AuthenticatedStoreIdPromotionsIndexRoute:
    AuthenticatedStoreIdPromotionsIndexRoute,
  AuthenticatedStoreIdProductsCategoriesCategoryIdRoute:
    AuthenticatedStoreIdProductsCategoriesCategoryIdRoute,
  AuthenticatedStoreIdProductsCategoriesNewRoute:
    AuthenticatedStoreIdProductsCategoriesNewRoute,
  AuthenticatedStoreIdProductsPriceListsNewRoute:
    AuthenticatedStoreIdProductsPriceListsNewRoute,
  AuthenticatedStoreIdProductsCategoriesIndexRoute:
    AuthenticatedStoreIdProductsCategoriesIndexRoute,
  AuthenticatedStoreIdProductsPriceListsIndexRoute:
    AuthenticatedStoreIdProductsPriceListsIndexRoute,
  AuthenticatedStoreIdProductsPriceListsPriceListIdIndexRoute:
    AuthenticatedStoreIdProductsPriceListsPriceListIdIndexRoute,
}

const AuthenticatedStoreIdRouteWithChildren =
  AuthenticatedStoreIdRoute._addFileChildren(AuthenticatedStoreIdRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedStoreIdRoute: typeof AuthenticatedStoreIdRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedStoreIdRoute: AuthenticatedStoreIdRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
