// This file is auto-generated by scripts/generate-admin-client.ts
// Do not edit manually. Run: npm run generate:admin-client

// Request parameter types (generated from OpenAPI request bodies)

export interface AdminAssetCreateParams {
  alt?: string;
  position?: number;
  type?: string;
  viewable_type?: string;
  viewable_id?: string;
}

export interface AdminAssetUpdateParams {
  alt?: string;
  position?: number;
}

export interface AdminOptionTypeCreateParams {
  name: string;
  presentation: string;
  position?: number;
  filterable?: boolean;
  option_values?: Array<{
    name?: string;
    presentation?: string;
    position?: number;
  }>;
}

export interface AdminOptionTypeUpdateParams {
  name?: string;
  presentation?: string;
  position?: number;
  filterable?: boolean;
  option_values?: Array<{
    id?: string;
    name?: string;
    presentation?: string;
    position?: number;
  }>;
}

export interface AdminProductCreateParams {
  name: string;
  price: number;
  description?: string;
  slug?: string;
  status?: 'draft' | 'active' | 'archived';
  sku?: string;
  shipping_category_id: string;
  tax_category_id?: string;
  taxon_ids?: Array<string>;
  tags?: Array<string>;
  variants?: Array<{
    sku?: string;
    price?: number;
    option_type?: string;
    option_value?: string;
    total_on_hand?: number;
    prices?: Array<{
      currency: string;
      amount: number;
      compare_at_amount?: number;
    }>;
  }>;
}

export interface AdminProductUpdateParams {
  name?: string;
  price?: number;
  description?: string;
  slug?: string;
  status?: 'draft' | 'active' | 'archived';
  sku?: string;
  shipping_category_id?: string;
  tax_category_id?: string;
  taxon_ids?: Array<string>;
  tags?: Array<string>;
  variants?: Array<{
    sku?: string;
    price?: number;
    option_type?: string;
    option_value?: string;
    total_on_hand?: number;
    prices?: Array<{
      currency: string;
      amount: number;
      compare_at_amount?: number;
    }>;
  }>;
}

export interface AdminTaxonomyCreateParams {
  name: string;
  position?: number;
}

export interface AdminTaxonomyUpdateParams {
  name?: string;
  position?: number;
}

export interface AdminTaxonCreateParams {
  name: string;
  parent_id?: string;
  position?: number;
  description?: string;
  permalink?: string;
  meta_title?: string;
  meta_description?: string;
  meta_keywords?: string;
  hide_from_nav?: boolean;
  sort_order?: string;
}

export interface AdminTaxonUpdateParams {
  name?: string;
  parent_id?: string;
  position?: number;
  description?: string;
  permalink?: string;
  meta_title?: string;
  meta_description?: string;
  meta_keywords?: string;
  hide_from_nav?: boolean;
  sort_order?: string;
}

export interface AdminVariantCreateParams {
  sku?: string;
  price?: number;
  compare_at_price?: number;
  cost_price?: number;
  cost_currency?: string;
  weight?: number;
  height?: number;
  width?: number;
  depth?: number;
  weight_unit?: string;
  dimensions_unit?: string;
  track_inventory?: boolean;
  tax_category_id?: string;
  option_type?: string;
  option_value?: string;
  total_on_hand?: number;
  position?: number;
  barcode?: string;
  prices?: Array<{
    currency: string;
    amount: number;
    compare_at_amount?: number;
  }>;
  stock_items?: Array<{
    stock_location_id?: string;
    count_on_hand?: number;
    backorderable?: boolean;
  }>;
}

export interface AdminVariantUpdateParams {
  sku?: string;
  price?: number;
  compare_at_price?: number;
  cost_price?: number;
  cost_currency?: string;
  weight?: number;
  height?: number;
  width?: number;
  depth?: number;
  weight_unit?: string;
  dimensions_unit?: string;
  track_inventory?: boolean;
  tax_category_id?: string;
  option_type?: string;
  option_value?: string;
  total_on_hand?: number;
  position?: number;
  barcode?: string;
  prices?: Array<{
    currency: string;
    amount: number;
    compare_at_amount?: number;
  }>;
  stock_items?: Array<{
    stock_location_id?: string;
    count_on_hand?: number;
    backorderable?: boolean;
  }>;
}
