// This file is auto-generated by scripts/generate-admin-client.ts
// Do not edit manually. Run: npm run generate:admin-client

import type { RequestFn, RequestOptions } from './request';
import { transformListParams } from './params';
import type {
  PaginatedResponse,
  ListParams,
  AdminAuthTokens,
  AdminLoginCredentials,
  AdminAdjustment,
  AdminAsset,
  AdminLineItem,
  AdminOptionType,
  AdminOrder,
  AdminPayment,
  AdminProduct,
  AdminRefund,
  AdminShipment,
  AdminTaxon,
  AdminTaxonomy,
  AdminVariant,
} from './types';
import type {
  AdminAdjustmentCreateParams,
  AdminAdjustmentUpdateParams,
  AdminAssetCreateParams,
  AdminAssetUpdateParams,
  AdminLineItemCreateParams,
  AdminLineItemUpdateParams,
  AdminOptionTypeCreateParams,
  AdminOptionTypeUpdateParams,
  AdminOrderCreateParams,
  AdminOrderUpdateParams,
  AdminPaymentCreateParams,
  AdminProductCreateParams,
  AdminProductUpdateParams,
  AdminRefundCreateParams,
  AdminShipmentUpdateParams,
  AdminTaxonCreateParams,
  AdminTaxonUpdateParams,
  AdminTaxonomyCreateParams,
  AdminTaxonomyUpdateParams,
  AdminVariantCreateParams,
  AdminVariantUpdateParams,
} from './admin-params';

export type {
  AdminAdjustmentCreateParams,
  AdminAdjustmentUpdateParams,
  AdminAssetCreateParams,
  AdminAssetUpdateParams,
  AdminLineItemCreateParams,
  AdminLineItemUpdateParams,
  AdminOptionTypeCreateParams,
  AdminOptionTypeUpdateParams,
  AdminOrderCreateParams,
  AdminOrderUpdateParams,
  AdminPaymentCreateParams,
  AdminProductCreateParams,
  AdminProductUpdateParams,
  AdminRefundCreateParams,
  AdminShipmentUpdateParams,
  AdminTaxonCreateParams,
  AdminTaxonUpdateParams,
  AdminTaxonomyCreateParams,
  AdminTaxonomyUpdateParams,
  AdminVariantCreateParams,
  AdminVariantUpdateParams,
} from './admin-params';

/** Serialize expand arrays into comma-separated query params */
function getParams(params?: { expand?: string[] }): Record<string, string> | undefined {
  if (!params?.expand?.length) return undefined;
  return { expand: params.expand.join(',') };
}

export class AdminClient {
  private readonly request: RequestFn;

  constructor(request: RequestFn) {
    this.request = request;
  }

  // ============================================
  // Authentication (hand-written, not auto-generated)
  // ============================================

  readonly auth = {
    /** Login with email and password */
    login: (credentials: AdminLoginCredentials): Promise<AdminAuthTokens> =>
      this.request<AdminAuthTokens>('POST', '/auth/login', { body: credentials }),

    /** Refresh access token (requires valid Bearer token) */
    refresh: (options: RequestOptions): Promise<AdminAuthTokens> =>
      this.request<AdminAuthTokens>('POST', '/auth/refresh', options),
  };

  // ============================================
  // Option Types
  // ============================================

  readonly optionTypes = {
    /** List option types */
    list: (
      params?: ListParams,
      options?: RequestOptions
    ): Promise<PaginatedResponse<AdminOptionType>> =>
      this.request<PaginatedResponse<AdminOptionType>>('GET', '/option_types', {
        ...options,
        params: transformListParams({ ...params }),
      }),

    /** Create an option type */
    create: (
      params: AdminOptionTypeCreateParams,
      options?: RequestOptions
    ): Promise<AdminOptionType> =>
      this.request<AdminOptionType>('POST', '/option_types', {
        ...options,
        body: params,
      }),

    /** Get an option type */
    get: (
      id: string,
      params?: { expand?: string[] },
      options?: RequestOptions
    ): Promise<AdminOptionType> =>
      this.request<AdminOptionType>('GET', `/option_types/${id}`, {
        ...options,
        params: getParams(params),
      }),

    /** Update an option type */
    update: (
      id: string,
      params: AdminOptionTypeUpdateParams,
      options?: RequestOptions
    ): Promise<AdminOptionType> =>
      this.request<AdminOptionType>('PATCH', `/option_types/${id}`, {
        ...options,
        body: params,
      }),

    /** Delete an option type */
    delete: (
      id: string,
      options?: RequestOptions
    ): Promise<void> =>
      this.request<void>('DELETE', `/option_types/${id}`, options),

  };

  // ============================================
  // Orders
  // ============================================

  readonly orders = {
    /** List orders */
    list: (
      params?: ListParams,
      options?: RequestOptions
    ): Promise<PaginatedResponse<AdminOrder>> =>
      this.request<PaginatedResponse<AdminOrder>>('GET', '/orders', {
        ...options,
        params: transformListParams({ ...params }),
      }),

    /** Create a draft order */
    create: (
      params: AdminOrderCreateParams,
      options?: RequestOptions
    ): Promise<AdminOrder> =>
      this.request<AdminOrder>('POST', '/orders', {
        ...options,
        body: params,
      }),

    /** Show an order */
    get: (
      id: string,
      params?: { expand?: string[] },
      options?: RequestOptions
    ): Promise<AdminOrder> =>
      this.request<AdminOrder>('GET', `/orders/${id}`, {
        ...options,
        params: getParams(params),
      }),

    /** Update an order */
    update: (
      id: string,
      params: AdminOrderUpdateParams,
      options?: RequestOptions
    ): Promise<AdminOrder> =>
      this.request<AdminOrder>('PATCH', `/orders/${id}`, {
        ...options,
        body: params,
      }),

    /** Delete a draft order */
    delete: (
      id: string,
      options?: RequestOptions
    ): Promise<void> =>
      this.request<void>('DELETE', `/orders/${id}`, options),

    /** Cancel an order */
    cancel: (
      id: string,
      params?: Record<string, unknown>,
      options?: RequestOptions
    ): Promise<AdminOrder> =>
      this.request<AdminOrder>('PATCH', `/orders/${id}/cancel`, {
        ...options,
        body: params,
      }),

    /** Approve an order */
    approve: (
      id: string,
      params?: Record<string, unknown>,
      options?: RequestOptions
    ): Promise<AdminOrder> =>
      this.request<AdminOrder>('PATCH', `/orders/${id}/approve`, {
        ...options,
        body: params,
      }),

    /** Resume a canceled order */
    resume: (
      id: string,
      params?: Record<string, unknown>,
      options?: RequestOptions
    ): Promise<AdminOrder> =>
      this.request<AdminOrder>('PATCH', `/orders/${id}/resume`, {
        ...options,
        body: params,
      }),

    /** Resend confirmation email */
    resendConfirmation: (
      id: string,
      params?: Record<string, unknown>,
      options?: RequestOptions
    ): Promise<AdminOrder> =>
      this.request<AdminOrder>('POST', `/orders/${id}/resend_confirmation`, {
        ...options,
        body: params,
      }),

    /** Nested: orders/{id}/adjustments */
    adjustments: {
      /** List adjustments */
      list: (
        orderId: string,
        params?: ListParams,
        options?: RequestOptions
      ): Promise<PaginatedResponse<AdminAdjustment>> =>
        this.request<PaginatedResponse<AdminAdjustment>>('GET', `/orders/${orderId}/adjustments`, {
          ...options,
          params: transformListParams({ ...params }),
        }),

      /** Create an adjustment */
      create: (
        orderId: string,
        params: AdminAdjustmentCreateParams,
        options?: RequestOptions
      ): Promise<AdminAdjustment> =>
        this.request<AdminAdjustment>('POST', `/orders/${orderId}/adjustments`, {
          ...options,
          body: params,
        }),

      /** Show an adjustment */
      get: (
        orderId: string,
        id: string,
        params?: { expand?: string[] },
        options?: RequestOptions
      ): Promise<AdminAdjustment> =>
        this.request<AdminAdjustment>('GET', `/orders/${orderId}/adjustments/${id}`, {
          ...options,
          params: getParams(params),
        }),

      /** Update an adjustment */
      update: (
        orderId: string,
        id: string,
        params: AdminAdjustmentUpdateParams,
        options?: RequestOptions
      ): Promise<AdminAdjustment> =>
        this.request<AdminAdjustment>('PATCH', `/orders/${orderId}/adjustments/${id}`, {
          ...options,
          body: params,
        }),

      /** Delete an adjustment */
      delete: (
        orderId: string,
        id: string,
        options?: RequestOptions
      ): Promise<void> =>
        this.request<void>('DELETE', `/orders/${orderId}/adjustments/${id}`, options),

    },

    /** Nested: orders/{id}/line_items */
    lineItems: {
      /** List line items */
      list: (
        orderId: string,
        params?: ListParams,
        options?: RequestOptions
      ): Promise<PaginatedResponse<AdminLineItem>> =>
        this.request<PaginatedResponse<AdminLineItem>>('GET', `/orders/${orderId}/line_items`, {
          ...options,
          params: transformListParams({ ...params }),
        }),

      /** Add a line item */
      create: (
        orderId: string,
        params: AdminLineItemCreateParams,
        options?: RequestOptions
      ): Promise<AdminLineItem> =>
        this.request<AdminLineItem>('POST', `/orders/${orderId}/line_items`, {
          ...options,
          body: params,
        }),

      /** Show a line item */
      get: (
        orderId: string,
        id: string,
        params?: { expand?: string[] },
        options?: RequestOptions
      ): Promise<AdminLineItem> =>
        this.request<AdminLineItem>('GET', `/orders/${orderId}/line_items/${id}`, {
          ...options,
          params: getParams(params),
        }),

      /** Update a line item */
      update: (
        orderId: string,
        id: string,
        params: AdminLineItemUpdateParams,
        options?: RequestOptions
      ): Promise<AdminLineItem> =>
        this.request<AdminLineItem>('PATCH', `/orders/${orderId}/line_items/${id}`, {
          ...options,
          body: params,
        }),

      /** Remove a line item */
      delete: (
        orderId: string,
        id: string,
        options?: RequestOptions
      ): Promise<void> =>
        this.request<void>('DELETE', `/orders/${orderId}/line_items/${id}`, options),

    },

    /** Nested: orders/{id}/payments */
    payments: {
      /** List payments */
      list: (
        orderId: string,
        params?: ListParams,
        options?: RequestOptions
      ): Promise<PaginatedResponse<AdminPayment>> =>
        this.request<PaginatedResponse<AdminPayment>>('GET', `/orders/${orderId}/payments`, {
          ...options,
          params: transformListParams({ ...params }),
        }),

      /** Create a payment */
      create: (
        orderId: string,
        params: AdminPaymentCreateParams,
        options?: RequestOptions
      ): Promise<AdminPayment> =>
        this.request<AdminPayment>('POST', `/orders/${orderId}/payments`, {
          ...options,
          body: params,
        }),

      /** Show a payment */
      get: (
        orderId: string,
        id: string,
        params?: { expand?: string[] },
        options?: RequestOptions
      ): Promise<AdminPayment> =>
        this.request<AdminPayment>('GET', `/orders/${orderId}/payments/${id}`, {
          ...options,
          params: getParams(params),
        }),

      /** Capture a payment */
      capture: (
        orderId: string,
        id: string,
        params?: Record<string, unknown>,
        options?: RequestOptions
      ): Promise<AdminPayment> =>
        this.request<AdminPayment>('PATCH', `/orders/${orderId}/payments/${id}/capture`, {
          ...options,
          body: params,
        }),

      /** Void a payment */
      void: (
        orderId: string,
        id: string,
        params?: Record<string, unknown>,
        options?: RequestOptions
      ): Promise<AdminPayment> =>
        this.request<AdminPayment>('PATCH', `/orders/${orderId}/payments/${id}/void`, {
          ...options,
          body: params,
        }),

    },

    /** Nested: orders/{id}/refunds */
    refunds: {
      /** List refunds */
      list: (
        orderId: string,
        params?: ListParams,
        options?: RequestOptions
      ): Promise<PaginatedResponse<AdminRefund>> =>
        this.request<PaginatedResponse<AdminRefund>>('GET', `/orders/${orderId}/refunds`, {
          ...options,
          params: transformListParams({ ...params }),
        }),

      /** Create a refund */
      create: (
        orderId: string,
        params: AdminRefundCreateParams,
        options?: RequestOptions
      ): Promise<AdminRefund> =>
        this.request<AdminRefund>('POST', `/orders/${orderId}/refunds`, {
          ...options,
          body: params,
        }),

    },

    /** Nested: orders/{id}/shipments */
    shipments: {
      /** List shipments */
      list: (
        orderId: string,
        params?: ListParams,
        options?: RequestOptions
      ): Promise<PaginatedResponse<AdminShipment>> =>
        this.request<PaginatedResponse<AdminShipment>>('GET', `/orders/${orderId}/shipments`, {
          ...options,
          params: transformListParams({ ...params }),
        }),

      /** Show a shipment */
      get: (
        orderId: string,
        id: string,
        params?: { expand?: string[] },
        options?: RequestOptions
      ): Promise<AdminShipment> =>
        this.request<AdminShipment>('GET', `/orders/${orderId}/shipments/${id}`, {
          ...options,
          params: getParams(params),
        }),

      /** Update a shipment */
      update: (
        orderId: string,
        id: string,
        params: AdminShipmentUpdateParams,
        options?: RequestOptions
      ): Promise<AdminShipment> =>
        this.request<AdminShipment>('PATCH', `/orders/${orderId}/shipments/${id}`, {
          ...options,
          body: params,
        }),

      /** Ship a shipment */
      ship: (
        orderId: string,
        id: string,
        params?: Record<string, unknown>,
        options?: RequestOptions
      ): Promise<AdminShipment> =>
        this.request<AdminShipment>('PATCH', `/orders/${orderId}/shipments/${id}/ship`, {
          ...options,
          body: params,
        }),

      /** Cancel a shipment */
      cancel: (
        orderId: string,
        id: string,
        params?: Record<string, unknown>,
        options?: RequestOptions
      ): Promise<AdminShipment> =>
        this.request<AdminShipment>('PATCH', `/orders/${orderId}/shipments/${id}/cancel`, {
          ...options,
          body: params,
        }),

      /** Resume a shipment */
      resume: (
        orderId: string,
        id: string,
        params?: Record<string, unknown>,
        options?: RequestOptions
      ): Promise<AdminShipment> =>
        this.request<AdminShipment>('PATCH', `/orders/${orderId}/shipments/${id}/resume`, {
          ...options,
          body: params,
        }),

      /** Split a shipment */
      split: (
        orderId: string,
        id: string,
        params?: Record<string, unknown>,
        options?: RequestOptions
      ): Promise<AdminShipment> =>
        this.request<AdminShipment>('PATCH', `/orders/${orderId}/shipments/${id}/split`, {
          ...options,
          body: params,
        }),

    },

  };

  // ============================================
  // Products
  // ============================================

  readonly products = {
    /** List products */
    list: (
      params?: ListParams,
      options?: RequestOptions
    ): Promise<PaginatedResponse<AdminProduct>> =>
      this.request<PaginatedResponse<AdminProduct>>('GET', '/products', {
        ...options,
        params: transformListParams({ ...params }),
      }),

    /** Create a product */
    create: (
      params: AdminProductCreateParams,
      options?: RequestOptions
    ): Promise<AdminProduct> =>
      this.request<AdminProduct>('POST', '/products', {
        ...options,
        body: params,
      }),

    /** Get a product */
    get: (
      id: string,
      params?: { expand?: string[] },
      options?: RequestOptions
    ): Promise<AdminProduct> =>
      this.request<AdminProduct>('GET', `/products/${id}`, {
        ...options,
        params: getParams(params),
      }),

    /** Update a product */
    update: (
      id: string,
      params: AdminProductUpdateParams,
      options?: RequestOptions
    ): Promise<AdminProduct> =>
      this.request<AdminProduct>('PATCH', `/products/${id}`, {
        ...options,
        body: params,
      }),

    /** Delete a product */
    delete: (
      id: string,
      options?: RequestOptions
    ): Promise<void> =>
      this.request<void>('DELETE', `/products/${id}`, options),

    /** Nested: products/{id}/assets */
    assets: {
      /** List product assets */
      list: (
        productId: string,
        params?: ListParams,
        options?: RequestOptions
      ): Promise<PaginatedResponse<AdminAsset>> =>
        this.request<PaginatedResponse<AdminAsset>>('GET', `/products/${productId}/assets`, {
          ...options,
          params: transformListParams({ ...params }),
        }),

      /** Create an asset */
      create: (
        productId: string,
        params: AdminAssetCreateParams,
        options?: RequestOptions
      ): Promise<AdminAsset> =>
        this.request<AdminAsset>('POST', `/products/${productId}/assets`, {
          ...options,
          body: params,
        }),

      /** Update an asset */
      update: (
        productId: string,
        id: string,
        params: AdminAssetUpdateParams,
        options?: RequestOptions
      ): Promise<AdminAsset> =>
        this.request<AdminAsset>('PATCH', `/products/${productId}/assets/${id}`, {
          ...options,
          body: params,
        }),

      /** Delete an asset */
      delete: (
        productId: string,
        id: string,
        options?: RequestOptions
      ): Promise<void> =>
        this.request<void>('DELETE', `/products/${productId}/assets/${id}`, options),

    },

    /** Nested: products/{id}/variants */
    variants: {
      /** List product variants */
      list: (
        productId: string,
        params?: ListParams,
        options?: RequestOptions
      ): Promise<PaginatedResponse<AdminVariant>> =>
        this.request<PaginatedResponse<AdminVariant>>('GET', `/products/${productId}/variants`, {
          ...options,
          params: transformListParams({ ...params }),
        }),

      /** Create a variant */
      create: (
        productId: string,
        params: AdminVariantCreateParams,
        options?: RequestOptions
      ): Promise<AdminVariant> =>
        this.request<AdminVariant>('POST', `/products/${productId}/variants`, {
          ...options,
          body: params,
        }),

      /** Get a variant */
      get: (
        productId: string,
        id: string,
        params?: { expand?: string[] },
        options?: RequestOptions
      ): Promise<AdminVariant> =>
        this.request<AdminVariant>('GET', `/products/${productId}/variants/${id}`, {
          ...options,
          params: getParams(params),
        }),

      /** Update a variant */
      update: (
        productId: string,
        id: string,
        params: AdminVariantUpdateParams,
        options?: RequestOptions
      ): Promise<AdminVariant> =>
        this.request<AdminVariant>('PATCH', `/products/${productId}/variants/${id}`, {
          ...options,
          body: params,
        }),

      /** Delete a variant */
      delete: (
        productId: string,
        id: string,
        options?: RequestOptions
      ): Promise<void> =>
        this.request<void>('DELETE', `/products/${productId}/variants/${id}`, options),

    },

  };

  // ============================================
  // Taxonomies
  // ============================================

  readonly taxonomies = {
    /** List taxonomies */
    list: (
      params?: ListParams,
      options?: RequestOptions
    ): Promise<PaginatedResponse<AdminTaxonomy>> =>
      this.request<PaginatedResponse<AdminTaxonomy>>('GET', '/taxonomies', {
        ...options,
        params: transformListParams({ ...params }),
      }),

    /** Create a taxonomy */
    create: (
      params: AdminTaxonomyCreateParams,
      options?: RequestOptions
    ): Promise<AdminTaxonomy> =>
      this.request<AdminTaxonomy>('POST', '/taxonomies', {
        ...options,
        body: params,
      }),

    /** Get a taxonomy */
    get: (
      id: string,
      params?: { expand?: string[] },
      options?: RequestOptions
    ): Promise<AdminTaxonomy> =>
      this.request<AdminTaxonomy>('GET', `/taxonomies/${id}`, {
        ...options,
        params: getParams(params),
      }),

    /** Update a taxonomy */
    update: (
      id: string,
      params: AdminTaxonomyUpdateParams,
      options?: RequestOptions
    ): Promise<AdminTaxonomy> =>
      this.request<AdminTaxonomy>('PATCH', `/taxonomies/${id}`, {
        ...options,
        body: params,
      }),

    /** Delete a taxonomy */
    delete: (
      id: string,
      options?: RequestOptions
    ): Promise<void> =>
      this.request<void>('DELETE', `/taxonomies/${id}`, options),

    /** Nested: taxonomies/{id}/taxons */
    taxons: {
      /** List taxonomy taxons */
      list: (
        taxonomyId: string,
        params?: ListParams,
        options?: RequestOptions
      ): Promise<PaginatedResponse<AdminTaxon>> =>
        this.request<PaginatedResponse<AdminTaxon>>('GET', `/taxonomies/${taxonomyId}/taxons`, {
          ...options,
          params: transformListParams({ ...params }),
        }),

      /** Create a taxon */
      create: (
        taxonomyId: string,
        params: AdminTaxonCreateParams,
        options?: RequestOptions
      ): Promise<AdminTaxon> =>
        this.request<AdminTaxon>('POST', `/taxonomies/${taxonomyId}/taxons`, {
          ...options,
          body: params,
        }),

      /** Get a taxonomy taxon */
      get: (
        taxonomyId: string,
        id: string,
        params?: { expand?: string[] },
        options?: RequestOptions
      ): Promise<AdminTaxon> =>
        this.request<AdminTaxon>('GET', `/taxonomies/${taxonomyId}/taxons/${id}`, {
          ...options,
          params: getParams(params),
        }),

      /** Update a taxon */
      update: (
        taxonomyId: string,
        id: string,
        params: AdminTaxonUpdateParams,
        options?: RequestOptions
      ): Promise<AdminTaxon> =>
        this.request<AdminTaxon>('PATCH', `/taxonomies/${taxonomyId}/taxons/${id}`, {
          ...options,
          body: params,
        }),

      /** Delete a taxon */
      delete: (
        taxonomyId: string,
        id: string,
        options?: RequestOptions
      ): Promise<void> =>
        this.request<void>('DELETE', `/taxonomies/${taxonomyId}/taxons/${id}`, options),

    },

  };

  // ============================================
  // Taxons
  // ============================================

  readonly taxons = {
    /** List taxons */
    list: (
      params?: ListParams,
      options?: RequestOptions
    ): Promise<PaginatedResponse<AdminTaxon>> =>
      this.request<PaginatedResponse<AdminTaxon>>('GET', '/taxons', {
        ...options,
        params: transformListParams({ ...params }),
      }),

    /** Get a taxon */
    get: (
      id: string,
      params?: { expand?: string[] },
      options?: RequestOptions
    ): Promise<AdminTaxon> =>
      this.request<AdminTaxon>('GET', `/taxons/${id}`, {
        ...options,
        params: getParams(params),
      }),

  };
}
