// DO NOT MODIFY: generated by scripts/generate-webhook-events.ts
// Run `pnpm generate:webhook-events` to regenerate.
//
// The discriminated union of every event Spree can deliver to a webhook
// endpoint. The `data` payload type is the Store API V3 serializer output —
// the same shape the REST API returns. Narrow on `name` to type `data`:
//
//   switch (event.name) {
//     case 'order.completed': event.data // Order
//     case 'product.updated': event.data // Product
//   }
import type {
  Digital,
  DigitalLink,
  Fulfillment,
  GiftCard,
  GiftCardBatch,
  LineItem,
  NewsletterSubscriber,
  Order,
  Payment,
  PaymentSession,
  PaymentSetupSession,
  Price,
  Product,
  Promotion,
  Refund,
  ReturnAuthorization,
  ReturnItem,
  StockReservation,
  StoreCredit,
  Variant,
  Wishlist,
  WishlistItem,
} from './types/generated'

/** Discriminated union of every Spree webhook event, keyed by `name`. */
export type SpreeWebhookEventData =
  | { name: 'order.created'; data: Order }
  | { name: 'order.updated'; data: Order }
  | { name: 'order.deleted'; data: Order }
  | { name: 'line_item.created'; data: LineItem }
  | { name: 'line_item.updated'; data: LineItem }
  | { name: 'line_item.deleted'; data: LineItem }
  | { name: 'product.created'; data: Product }
  | { name: 'product.updated'; data: Product }
  | { name: 'product.deleted'; data: Product }
  | { name: 'variant.created'; data: Variant }
  | { name: 'variant.updated'; data: Variant }
  | { name: 'variant.deleted'; data: Variant }
  | { name: 'price.created'; data: Price }
  | { name: 'price.updated'; data: Price }
  | { name: 'price.deleted'; data: Price }
  | { name: 'payment.created'; data: Payment }
  | { name: 'payment.updated'; data: Payment }
  | { name: 'payment.deleted'; data: Payment }
  | { name: 'payment_session.created'; data: PaymentSession }
  | { name: 'payment_session.updated'; data: PaymentSession }
  | { name: 'payment_session.deleted'; data: PaymentSession }
  | { name: 'payment_setup_session.created'; data: PaymentSetupSession }
  | { name: 'payment_setup_session.updated'; data: PaymentSetupSession }
  | { name: 'payment_setup_session.deleted'; data: PaymentSetupSession }
  | { name: 'refund.created'; data: Refund }
  | { name: 'refund.updated'; data: Refund }
  | { name: 'refund.deleted'; data: Refund }
  | { name: 'shipment.created'; data: Fulfillment }
  | { name: 'shipment.updated'; data: Fulfillment }
  | { name: 'shipment.deleted'; data: Fulfillment }
  | { name: 'stock_reservation.created'; data: StockReservation }
  | { name: 'stock_reservation.updated'; data: StockReservation }
  | { name: 'stock_reservation.deleted'; data: StockReservation }
  | { name: 'return_authorization.created'; data: ReturnAuthorization }
  | { name: 'return_authorization.updated'; data: ReturnAuthorization }
  | { name: 'return_authorization.deleted'; data: ReturnAuthorization }
  | { name: 'store_credit.created'; data: StoreCredit }
  | { name: 'store_credit.updated'; data: StoreCredit }
  | { name: 'store_credit.deleted'; data: StoreCredit }
  | { name: 'gift_card.created'; data: GiftCard }
  | { name: 'gift_card.updated'; data: GiftCard }
  | { name: 'gift_card.deleted'; data: GiftCard }
  | { name: 'gift_card_batch.created'; data: GiftCardBatch }
  | { name: 'gift_card_batch.updated'; data: GiftCardBatch }
  | { name: 'gift_card_batch.deleted'; data: GiftCardBatch }
  | { name: 'promotion.created'; data: Promotion }
  | { name: 'promotion.updated'; data: Promotion }
  | { name: 'promotion.deleted'; data: Promotion }
  | { name: 'digital.created'; data: Digital }
  | { name: 'digital.updated'; data: Digital }
  | { name: 'digital.deleted'; data: Digital }
  | { name: 'digital_link.created'; data: DigitalLink }
  | { name: 'digital_link.updated'; data: DigitalLink }
  | { name: 'digital_link.deleted'; data: DigitalLink }
  | { name: 'wishlist.created'; data: Wishlist }
  | { name: 'wishlist.updated'; data: Wishlist }
  | { name: 'wishlist.deleted'; data: Wishlist }
  | { name: 'wished_item.created'; data: WishlistItem }
  | { name: 'wished_item.updated'; data: WishlistItem }
  | { name: 'wished_item.deleted'; data: WishlistItem }
  | { name: 'newsletter_subscriber.created'; data: NewsletterSubscriber }
  | { name: 'newsletter_subscriber.updated'; data: NewsletterSubscriber }
  | { name: 'newsletter_subscriber.deleted'; data: NewsletterSubscriber }
  | { name: 'order.completed'; data: Order }
  | { name: 'order.paid'; data: Order }
  | { name: 'order.canceled'; data: Order }
  | { name: 'order.resumed'; data: Order }
  | { name: 'order.approved'; data: Order }
  | { name: 'order.shipped'; data: Order }
  | { name: 'payment.completed'; data: Payment }
  | { name: 'payment.paid'; data: Payment }
  | { name: 'payment.voided'; data: Payment }
  | { name: 'payment_session.processing'; data: PaymentSession }
  | { name: 'payment_session.completed'; data: PaymentSession }
  | { name: 'payment_session.failed'; data: PaymentSession }
  | { name: 'payment_session.canceled'; data: PaymentSession }
  | { name: 'payment_session.expired'; data: PaymentSession }
  | { name: 'payment_setup_session.processing'; data: PaymentSetupSession }
  | { name: 'payment_setup_session.completed'; data: PaymentSetupSession }
  | { name: 'payment_setup_session.failed'; data: PaymentSetupSession }
  | { name: 'payment_setup_session.canceled'; data: PaymentSetupSession }
  | { name: 'payment_setup_session.expired'; data: PaymentSetupSession }
  | { name: 'product.activated'; data: Product }
  | { name: 'product.archived'; data: Product }
  | { name: 'product.back_in_stock'; data: Product }
  | { name: 'product.out_of_stock'; data: Product }
  | { name: 'shipment.shipped'; data: Fulfillment }
  | { name: 'shipment.canceled'; data: Fulfillment }
  | { name: 'shipment.resumed'; data: Fulfillment }
  | { name: 'gift_card.redeemed'; data: GiftCard }
  | { name: 'gift_card.partially_redeemed'; data: GiftCard }
  | { name: 'return_authorization.canceled'; data: ReturnAuthorization }
  | { name: 'return_item.received'; data: ReturnItem }
  | { name: 'return_item.given'; data: ReturnItem }
  | { name: 'return_item.canceled'; data: ReturnItem }
  | { name: 'newsletter_subscriber.subscription_requested'; data: NewsletterSubscriber }
  | { name: 'newsletter_subscriber.verified'; data: NewsletterSubscriber }
  | { name: 'reimbursement.reimbursed'; data: Record<string, unknown> }
  | { name: 'import.completed'; data: Record<string, unknown> }
  | { name: 'import.progress'; data: Record<string, unknown> }
  | { name: 'import_row.completed'; data: Record<string, unknown> }
  | { name: 'import_row.failed'; data: Record<string, unknown> }
  | { name: 'customer.password_reset'; data: Record<string, unknown> }
  | { name: 'customer.password_reset_requested'; data: Record<string, unknown> }
  | { name: 'invitation.created'; data: Record<string, unknown> }
  | { name: 'invitation.accepted'; data: Record<string, unknown> }
  | { name: 'invitation.resent'; data: Record<string, unknown> }

/** Every event name Spree can deliver to a webhook endpoint. */
export type SpreeWebhookEventName = SpreeWebhookEventData['name']

/** Runtime set of every known event name (for filtering/validation). */
export const SPREE_WEBHOOK_EVENT_NAMES = [
  'order.created',
  'order.updated',
  'order.deleted',
  'line_item.created',
  'line_item.updated',
  'line_item.deleted',
  'product.created',
  'product.updated',
  'product.deleted',
  'variant.created',
  'variant.updated',
  'variant.deleted',
  'price.created',
  'price.updated',
  'price.deleted',
  'payment.created',
  'payment.updated',
  'payment.deleted',
  'payment_session.created',
  'payment_session.updated',
  'payment_session.deleted',
  'payment_setup_session.created',
  'payment_setup_session.updated',
  'payment_setup_session.deleted',
  'refund.created',
  'refund.updated',
  'refund.deleted',
  'shipment.created',
  'shipment.updated',
  'shipment.deleted',
  'stock_reservation.created',
  'stock_reservation.updated',
  'stock_reservation.deleted',
  'return_authorization.created',
  'return_authorization.updated',
  'return_authorization.deleted',
  'store_credit.created',
  'store_credit.updated',
  'store_credit.deleted',
  'gift_card.created',
  'gift_card.updated',
  'gift_card.deleted',
  'gift_card_batch.created',
  'gift_card_batch.updated',
  'gift_card_batch.deleted',
  'promotion.created',
  'promotion.updated',
  'promotion.deleted',
  'digital.created',
  'digital.updated',
  'digital.deleted',
  'digital_link.created',
  'digital_link.updated',
  'digital_link.deleted',
  'wishlist.created',
  'wishlist.updated',
  'wishlist.deleted',
  'wished_item.created',
  'wished_item.updated',
  'wished_item.deleted',
  'newsletter_subscriber.created',
  'newsletter_subscriber.updated',
  'newsletter_subscriber.deleted',
  'order.completed',
  'order.paid',
  'order.canceled',
  'order.resumed',
  'order.approved',
  'order.shipped',
  'payment.completed',
  'payment.paid',
  'payment.voided',
  'payment_session.processing',
  'payment_session.completed',
  'payment_session.failed',
  'payment_session.canceled',
  'payment_session.expired',
  'payment_setup_session.processing',
  'payment_setup_session.completed',
  'payment_setup_session.failed',
  'payment_setup_session.canceled',
  'payment_setup_session.expired',
  'product.activated',
  'product.archived',
  'product.back_in_stock',
  'product.out_of_stock',
  'shipment.shipped',
  'shipment.canceled',
  'shipment.resumed',
  'gift_card.redeemed',
  'gift_card.partially_redeemed',
  'return_authorization.canceled',
  'return_item.received',
  'return_item.given',
  'return_item.canceled',
  'newsletter_subscriber.subscription_requested',
  'newsletter_subscriber.verified',
  'reimbursement.reimbursed',
  'import.completed',
  'import.progress',
  'import_row.completed',
  'import_row.failed',
  'customer.password_reset',
  'customer.password_reset_requested',
  'invitation.created',
  'invitation.accepted',
  'invitation.resent',
] as const
