AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'spec/fixtures/**/*'
    - 'config/initializers/*'
    - 'public/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 200

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/UselessAssignment:
  Enabled: true

RSpec:
  AllCops:
    Exclude:
      - 'spec/fixtures/**/*'
      - 'spec/support/**/*'
      - 'spec/factories/**/*'
  Language:
    Enabled: true
  FactoryBot:
    Enabled: