eval(File.read(File.dirname(__FILE__) + '/../common_spree_dependencies.rb'))

gem 'spree_core', :path => '../core'
gem 'spree_api', :path => '../api'

# TODO: Rein: Should we move this to the gemspec?

gem 'sprockets-rails', '~> 2.1.4'
gem 'bootstrap-sass', '~> 3.3.1'

gemspec
