eval(File.read(File.dirname(__FILE__) + '/../common_spree_dependencies.rb'))

gem 'spree_core', :path => '../core'
gem 'spree_api', :path => '../api'

gem 'ransack', github: 'ernie/ransack', branch: 'rails-4'

gemspec
