require 'rails/all'

require 'bootstrap-kaminari-views'
require 'canonical-rails'
require 'deface'
require 'jquery-rails'
require 'spree/core'
require 'spree/frontend/middleware/seo_assist'
require 'spree/frontend/engine'
require 'spree/responder'
