require 'rails/all'
require 'sprockets/rails'

require 'bootstrap'
require 'glyphicons'
require 'inline_svg'
require 'popper_js'
require 'canonical-rails'
require 'jquery-rails'
require 'turbolinks'
require 'spree/core'
require 'spree/frontend/middleware/seo_assist'
require 'spree/frontend/engine'
