require 'rails/all'
require 'sprockets/rails'

require 'canonical-rails'
require 'deface'
require 'jquery-rails'
require 'bootstrap'
require 'popper_js'
require 'spree/core'
require 'spree/frontend/middleware/seo_assist'
require 'spree/frontend/engine'
require 'spree/responder'
