appraise 'spree-4' do
  gem 'spree', '~> 4.2'
  gem 'rails-controller-testing'
end

appraise 'spree-master' do
  gem 'spree', github: 'spree/spree', branch: 'master'
  gem 'rails-controller-testing'
end
