require 'rails/all'
require 'jquery-rails'
require 'jquery-ui-rails'
require 'select2-rails'
require 'flatpickr'
require 'bootstrap'
require 'glyphicons'
require 'popper_js'
require 'inline_svg'

require 'spree_core'
require 'spree_api'

require 'spree/backend/action_callbacks'
require 'spree/backend/callbacks'
require 'spree/backend/engine'
