eval_gemfile('../common_spree_dependencies.rb')

gem 'spree_core', path: '../core'
gem 'spree_api', path: '../api'
gem 'spree_emails', path: '../emails'

gem 'devise'
gem 'canonical-rails', github: 'commonlit/canonical-rails', branch: "bump-rails-8-1" # temporary fix for Rails 8.1 compatibility
gem 'sprockets-rails', '>= 3.5.2'

group :test, :development do
  gem 'selenium-webdriver'
end

gemspec
