require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rspec/core/rake_task'
require 'spree/testing_support/common_rake'

RSpec::Core::RakeTask.new

task default: :spec

desc "Generates a dummy app for testing"
task :test_app do
  ENV['LIB_NAME'] = 'spree/storefront'

  if ENV['USE_PREBUILT_APP'] == 'true'
    Rake::Task['common:use_prebuilt_app'].invoke('full')
  else
    Rake::Task['common:test_app'].execute(
      user_class: 'Spree::LegacyUser',
      admin_user_class: 'Spree::LegacyAdminUser',
      authentication: 'dummy',
      install_admin: true,
      css: true,
      javascript: true
    )
  end
end
