require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rspec/core/rake_task'
require 'spree/testing_support/common_rake'

RSpec::Core::RakeTask.new

task default: :spec

desc "Generates a dummy app for testing"
task :test_app do
  ENV['LIB_NAME'] = 'spree/storefront'

  Rake::Task['common:test_app'].execute(
    user_class: 'Spree::User',
    admin_user_class: 'Spree::AdminUser',
    authentication: 'devise',
    install_admin: true,
    css: true,
    javascript: true
  )
end
