require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rake/packagetask'
require 'rubygems/package_task'

desc "Default Task"
task :default => [:spec, :cucumber ]

spec = eval(File.read('spree_auth.gemspec'))

Gem::PackageTask.new(spec) do |p|
  p.gem_spec = spec
end

desc "Release to gemcutter"
task :release => :package do
  require 'rake/gemcutter'
  Rake::Gemcutter::Tasks.new(spec).define
  Rake::Task['gem:push'].invoke
end

desc "Default Task"
task :default => [ :spec ]

desc "Regenerates a rails 3 app for testing"
task :test_app do
  require 'rails/generators'
  require File.expand_path('../../core/lib/generators/spree_core/site/site_generator', __FILE__)
  require File.expand_path('../../core/lib/generators/spree_core/sandbox/sandbox_generator', __FILE__)
  require File.expand_path('../../core/lib/generators/spree_core/test_app/test_app_generator', __FILE__)

  SpreeCore::Generators::TestAppGenerator.class_eval do
    protected
    def additions_for_gemfile
      { :spree_core => File.join(File.dirname(__FILE__), "..", "core"),
        :spree_auth => File.dirname(__FILE__) } 
    end
  end

  SpreeCore::Generators::TestAppGenerator.start
end

ENV['SPREE_GEM_PATH'] = __FILE__
require File.expand_path("../../core/lib/tasks/common", __FILE__)
