/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as loginRouteImport } from './routes/login'
import { Route as authenticatedRouteImport } from './routes/_authenticated'
import { Route as authenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as acceptInvitationDotinvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as authenticatedSellerIdRouteImport } from './routes/_authenticated/$sellerId'
import { Route as IndexRouteImport } from './routes/_authenticated/$sellerId/index'
import { Route as TeamRouteImport } from './routes/_authenticated/$sellerId/team'
import { Route as ProfileRouteImport } from './routes/_authenticated/$sellerId/profile'
import { Route as OnboardingRouteImport } from './routes/_authenticated/$sellerId/onboarding'

const loginRoute = loginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRoute = authenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedRoute,
} as any)
const acceptInvitationDotinvitationIdRoute =
  acceptInvitationDotinvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticatedSellerIdRoute = authenticatedSellerIdRouteImport.update({
  id: '/$sellerId',
  path: '/$sellerId',
  getParentRoute: () => authenticatedRoute,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedSellerIdRoute,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => authenticatedSellerIdRoute,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => authenticatedSellerIdRoute,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => authenticatedSellerIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof authenticatedIndexRoute
  '/login': typeof loginRoute
  '/$sellerId': typeof authenticatedSellerIdRouteWithChildren
  '/accept-invitation/$invitationId': typeof acceptInvitationDotinvitationIdRoute
  '/$sellerId/onboarding': typeof OnboardingRoute
  '/$sellerId/profile': typeof ProfileRoute
  '/$sellerId/team': typeof TeamRoute
  '/$sellerId/': typeof IndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof loginRoute
  '/accept-invitation/$invitationId': typeof acceptInvitationDotinvitationIdRoute
  '/': typeof authenticatedIndexRoute
  '/$sellerId/onboarding': typeof OnboardingRoute
  '/$sellerId/profile': typeof ProfileRoute
  '/$sellerId/team': typeof TeamRoute
  '/$sellerId': typeof IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof authenticatedRouteWithChildren
  '/login': typeof loginRoute
  '/_authenticated/$sellerId': typeof authenticatedSellerIdRouteWithChildren
  '/accept-invitation/$invitationId': typeof acceptInvitationDotinvitationIdRoute
  '/_authenticated/': typeof authenticatedIndexRoute
  '/_authenticated/$sellerId/onboarding': typeof OnboardingRoute
  '/_authenticated/$sellerId/profile': typeof ProfileRoute
  '/_authenticated/$sellerId/team': typeof TeamRoute
  '/_authenticated/$sellerId/': typeof IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$sellerId'
    | '/accept-invitation/$invitationId'
    | '/$sellerId/onboarding'
    | '/$sellerId/profile'
    | '/$sellerId/team'
    | '/$sellerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/accept-invitation/$invitationId'
    | '/'
    | '/$sellerId/onboarding'
    | '/$sellerId/profile'
    | '/$sellerId/team'
    | '/$sellerId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/$sellerId'
    | '/accept-invitation/$invitationId'
    | '/_authenticated/'
    | '/_authenticated/$sellerId/onboarding'
    | '/_authenticated/$sellerId/profile'
    | '/_authenticated/$sellerId/team'
    | '/_authenticated/$sellerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRoute: typeof authenticatedRouteWithChildren
  loginRoute: typeof loginRoute
  acceptInvitationDotinvitationIdRoute: typeof acceptInvitationDotinvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof authenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof authenticatedRoute
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof acceptInvitationDotinvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$sellerId': {
      id: '/_authenticated/$sellerId'
      path: '/$sellerId'
      fullPath: '/$sellerId'
      preLoaderRoute: typeof authenticatedSellerIdRouteImport
      parentRoute: typeof authenticatedRoute
    }
    '/_authenticated/$sellerId/': {
      id: '/_authenticated/$sellerId/'
      path: '/'
      fullPath: '/$sellerId/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof authenticatedSellerIdRoute
    }
    '/_authenticated/$sellerId/team': {
      id: '/_authenticated/$sellerId/team'
      path: '/team'
      fullPath: '/$sellerId/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof authenticatedSellerIdRoute
    }
    '/_authenticated/$sellerId/profile': {
      id: '/_authenticated/$sellerId/profile'
      path: '/profile'
      fullPath: '/$sellerId/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof authenticatedSellerIdRoute
    }
    '/_authenticated/$sellerId/onboarding': {
      id: '/_authenticated/$sellerId/onboarding'
      path: '/onboarding'
      fullPath: '/$sellerId/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof authenticatedSellerIdRoute
    }
  }
}

interface authenticatedSellerIdRouteChildren {
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  TeamRoute: typeof TeamRoute
  IndexRoute: typeof IndexRoute
}

const authenticatedSellerIdRouteChildren: authenticatedSellerIdRouteChildren = {
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  TeamRoute: TeamRoute,
  IndexRoute: IndexRoute,
}

const authenticatedSellerIdRouteWithChildren =
  authenticatedSellerIdRoute._addFileChildren(
    authenticatedSellerIdRouteChildren,
  )

interface authenticatedRouteChildren {
  authenticatedSellerIdRoute: typeof authenticatedSellerIdRouteWithChildren
  authenticatedIndexRoute: typeof authenticatedIndexRoute
}

const authenticatedRouteChildren: authenticatedRouteChildren = {
  authenticatedSellerIdRoute: authenticatedSellerIdRouteWithChildren,
  authenticatedIndexRoute: authenticatedIndexRoute,
}

const authenticatedRouteWithChildren = authenticatedRoute._addFileChildren(
  authenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRoute: authenticatedRouteWithChildren,
  loginRoute: loginRoute,
  acceptInvitationDotinvitationIdRoute: acceptInvitationDotinvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
