import { createSellerApiClient, createSellerRouter, SellerDashboard } from '@spree/seller-dashboard'
import { createRoot } from 'react-dom/client'
import './styles.css'
// Generated by @spree/seller-dashboard/vite on every dev start and build.
// Commit it — its diff on upgrades shows exactly which pages changed.
import { routeTree } from './routeTree.gen'

// Build the Seller API client and register it with the shared framework
// before anything renders: the providers read it on mount.
createSellerApiClient({ baseUrl: import.meta.env.VITE_SPREE_API_URL || '' })

// basepath mirrors Vite's `base` so sub-path mounts route correctly.
const router = createSellerRouter(routeTree, { basepath: import.meta.env.BASE_URL })

// Registers the router program-wide so <Link> and navigation are type-checked
// against the real route tree.
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

createRoot(document.getElementById('root')!).render(<SellerDashboard router={router} />)
