/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../seller-dashboard/src/routes/__root'
import { Route as loginRouteImport } from './../../seller-dashboard/src/routes/login'
import { Route as authenticatedRouteImport } from './../../seller-dashboard/src/routes/_authenticated'
import { Route as authenticatedIndexRouteImport } from './../../seller-dashboard/src/routes/_authenticated/index'
import { Route as acceptInvitationDotinvitationIdRouteImport } from './../../seller-dashboard/src/routes/accept-invitation.$invitationId'
import { Route as authenticatedSellerIdRouteImport } from './../../seller-dashboard/src/routes/_authenticated/$sellerId'
import { Route as IndexRouteImport } from './../../seller-dashboard/src/routes/_authenticated/$sellerId/index'
import { Route as SettingsRouteImport } from './../../seller-dashboard/src/routes/_authenticated/$sellerId/settings'
import { Route as ProfileRouteImport } from './../../seller-dashboard/src/routes/_authenticated/$sellerId/profile'
import { Route as OnboardingRouteImport } from './../../seller-dashboard/src/routes/_authenticated/$sellerId/onboarding'
import { Route as SettingsIndexRouteImport } from './../../seller-dashboard/src/routes/_authenticated/$sellerId/settings/index'
import { Route as SettingsTeamRouteImport } from './../../seller-dashboard/src/routes/_authenticated/$sellerId/settings/team'
import { Route as SettingsStockLocationsRouteImport } from './../../seller-dashboard/src/routes/_authenticated/$sellerId/settings/stock-locations'

const loginRoute = loginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRoute = authenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedRoute,
} as any)
const acceptInvitationDotinvitationIdRoute =
  acceptInvitationDotinvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticatedSellerIdRoute = authenticatedSellerIdRouteImport.update({
  id: '/$sellerId',
  path: '/$sellerId',
  getParentRoute: () => authenticatedRoute,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedSellerIdRoute,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => authenticatedSellerIdRoute,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => authenticatedSellerIdRoute,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => authenticatedSellerIdRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsStockLocationsRoute = SettingsStockLocationsRouteImport.update({
  id: '/stock-locations',
  path: '/stock-locations',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof authenticatedIndexRoute
  '/login': typeof loginRoute
  '/$sellerId': typeof authenticatedSellerIdRouteWithChildren
  '/accept-invitation/$invitationId': typeof acceptInvitationDotinvitationIdRoute
  '/$sellerId/onboarding': typeof OnboardingRoute
  '/$sellerId/profile': typeof ProfileRoute
  '/$sellerId/settings': typeof SettingsRouteWithChildren
  '/$sellerId/': typeof IndexRoute
  '/$sellerId/settings/stock-locations': typeof SettingsStockLocationsRoute
  '/$sellerId/settings/team': typeof SettingsTeamRoute
  '/$sellerId/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof loginRoute
  '/accept-invitation/$invitationId': typeof acceptInvitationDotinvitationIdRoute
  '/': typeof authenticatedIndexRoute
  '/$sellerId/onboarding': typeof OnboardingRoute
  '/$sellerId/profile': typeof ProfileRoute
  '/$sellerId': typeof IndexRoute
  '/$sellerId/settings/stock-locations': typeof SettingsStockLocationsRoute
  '/$sellerId/settings/team': typeof SettingsTeamRoute
  '/$sellerId/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof authenticatedRouteWithChildren
  '/login': typeof loginRoute
  '/_authenticated/$sellerId': typeof authenticatedSellerIdRouteWithChildren
  '/accept-invitation/$invitationId': typeof acceptInvitationDotinvitationIdRoute
  '/_authenticated/': typeof authenticatedIndexRoute
  '/_authenticated/$sellerId/onboarding': typeof OnboardingRoute
  '/_authenticated/$sellerId/profile': typeof ProfileRoute
  '/_authenticated/$sellerId/settings': typeof SettingsRouteWithChildren
  '/_authenticated/$sellerId/': typeof IndexRoute
  '/_authenticated/$sellerId/settings/stock-locations': typeof SettingsStockLocationsRoute
  '/_authenticated/$sellerId/settings/team': typeof SettingsTeamRoute
  '/_authenticated/$sellerId/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$sellerId'
    | '/accept-invitation/$invitationId'
    | '/$sellerId/onboarding'
    | '/$sellerId/profile'
    | '/$sellerId/settings'
    | '/$sellerId/'
    | '/$sellerId/settings/stock-locations'
    | '/$sellerId/settings/team'
    | '/$sellerId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/accept-invitation/$invitationId'
    | '/'
    | '/$sellerId/onboarding'
    | '/$sellerId/profile'
    | '/$sellerId'
    | '/$sellerId/settings/stock-locations'
    | '/$sellerId/settings/team'
    | '/$sellerId/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/$sellerId'
    | '/accept-invitation/$invitationId'
    | '/_authenticated/'
    | '/_authenticated/$sellerId/onboarding'
    | '/_authenticated/$sellerId/profile'
    | '/_authenticated/$sellerId/settings'
    | '/_authenticated/$sellerId/'
    | '/_authenticated/$sellerId/settings/stock-locations'
    | '/_authenticated/$sellerId/settings/team'
    | '/_authenticated/$sellerId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRoute: typeof authenticatedRouteWithChildren
  loginRoute: typeof loginRoute
  acceptInvitationDotinvitationIdRoute: typeof acceptInvitationDotinvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof authenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof authenticatedRoute
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof acceptInvitationDotinvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$sellerId': {
      id: '/_authenticated/$sellerId'
      path: '/$sellerId'
      fullPath: '/$sellerId'
      preLoaderRoute: typeof authenticatedSellerIdRouteImport
      parentRoute: typeof authenticatedRoute
    }
    '/_authenticated/$sellerId/': {
      id: '/_authenticated/$sellerId/'
      path: '/'
      fullPath: '/$sellerId/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof authenticatedSellerIdRoute
    }
    '/_authenticated/$sellerId/settings': {
      id: '/_authenticated/$sellerId/settings'
      path: '/settings'
      fullPath: '/$sellerId/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof authenticatedSellerIdRoute
    }
    '/_authenticated/$sellerId/profile': {
      id: '/_authenticated/$sellerId/profile'
      path: '/profile'
      fullPath: '/$sellerId/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof authenticatedSellerIdRoute
    }
    '/_authenticated/$sellerId/onboarding': {
      id: '/_authenticated/$sellerId/onboarding'
      path: '/onboarding'
      fullPath: '/$sellerId/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof authenticatedSellerIdRoute
    }
    '/_authenticated/$sellerId/settings/': {
      id: '/_authenticated/$sellerId/settings/'
      path: '/'
      fullPath: '/$sellerId/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/$sellerId/settings/team': {
      id: '/_authenticated/$sellerId/settings/team'
      path: '/team'
      fullPath: '/$sellerId/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/$sellerId/settings/stock-locations': {
      id: '/_authenticated/$sellerId/settings/stock-locations'
      path: '/stock-locations'
      fullPath: '/$sellerId/settings/stock-locations'
      preLoaderRoute: typeof SettingsStockLocationsRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsStockLocationsRoute: typeof SettingsStockLocationsRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsStockLocationsRoute: SettingsStockLocationsRoute,
  SettingsTeamRoute: SettingsTeamRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface authenticatedSellerIdRouteChildren {
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  IndexRoute: typeof IndexRoute
}

const authenticatedSellerIdRouteChildren: authenticatedSellerIdRouteChildren = {
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRouteWithChildren,
  IndexRoute: IndexRoute,
}

const authenticatedSellerIdRouteWithChildren =
  authenticatedSellerIdRoute._addFileChildren(
    authenticatedSellerIdRouteChildren,
  )

interface authenticatedRouteChildren {
  authenticatedSellerIdRoute: typeof authenticatedSellerIdRouteWithChildren
  authenticatedIndexRoute: typeof authenticatedIndexRoute
}

const authenticatedRouteChildren: authenticatedRouteChildren = {
  authenticatedSellerIdRoute: authenticatedSellerIdRouteWithChildren,
  authenticatedIndexRoute: authenticatedIndexRoute,
}

const authenticatedRouteWithChildren = authenticatedRoute._addFileChildren(
  authenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRoute: authenticatedRouteWithChildren,
  loginRoute: loginRoute,
  acceptInvitationDotinvitationIdRoute: acceptInvitationDotinvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
