class AddSetupTokenToSpreeStores < ActiveRecord::Migration[8.1]
  # One-time first-run setup token
  # (docs/plans/6.0-store-context-and-first-run-setup.md): generated by
  # has_secure_token at store creation, printed by the installer, only
  # consulted while no admin user exists, and cleared when setup completes.
  # Plaintext at rest, like invitation tokens.
  def change
    add_column :spree_stores, :setup_token, :string
    add_index :spree_stores, :setup_token, unique: true
  end
end
