source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'sqlite3-ruby', :require => 'sqlite3'

group :test do
  gem 'rspec-rails', '2.0.0.beta.19'
  gem 'fabrication'
end

group :cucumber do
  gem 'cucumber-rails', '~> 0.3.2'
  gem 'database_cleaner', '~> 0.5.2'
  gem 'capybara', '~> 0.3.9', :require => false
end

