source 'http://rubygems.org'

gem 'rails', '~> 3.0.1'
gem 'sqlite3-ruby', :require => 'sqlite3'

group :test do
  gem 'rspec-rails', '~> 2.1.0'
  gem 'factory_girl_rails'
end

group :cucumber do
  gem 'cucumber-rails'
  gem 'database_cleaner', '~> 0.5.2'
  gem 'nokogiri'
  gem 'capybara'
end
