begin
  require "jeweler"
  Jeweler::Tasks.new do |gem|
    gem.name = "spree-payment-gateway"
    gem.summary = "Add payment gateway support to spree-core"
    gem.files = Dir["{lib}/**/*", "{app}/**/*", "{config}/**/*"]
    # other fields that would normally go in your gemspec
    # like authors, email and has_rdoc can also be included here
    gem.version = "0.30.0"      
    gem.add_dependency 'spree-core', '0.30.0'
  end
rescue
  puts "Jeweler or one of its dependencies is not installed."
end