# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{spree-payment-gateway}
  s.version = "0.30.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.date = %q{2010-06-20}
  s.default_executable = %q{spree}
  s.executables = ["spree"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "app/helpers/admin/gateways_helper.rb",
     "app/models/gateway.rb",
     "app/models/gateway/authorize_net.rb",
     "app/models/gateway/authorize_net_cim.rb",
     "app/models/gateway/beanstream.rb",
     "app/models/gateway/bogus.rb",
     "app/models/gateway/eway.rb",
     "app/models/gateway/linkpoint.rb",
     "app/models/gateway/pay_pal.rb",
     "app/models/gateway/sage_pay.rb",
     "config/locales/en.yml",
     "config/locales/ru-RU.yml",
     "config/routes.rb",
     "lib/active_merchant/billing/authorize_net_cim.rb",
     "lib/spree/payment_gateway.rb",
     "lib/tasks/payment_gateway_extension_tasks.rake"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Add payment gateway support to spree-core}
  s.test_files = [
    "spec/controllers/admin/configurations_controller_spec.rb",
     "spec/controllers/admin/mail_settings_controller_spec.rb",
     "spec/controllers/admin/shipping_categories_controller_spec.rb",
     "spec/controllers/admin/shipping_methods_controller_spec.rb",
     "spec/controllers/countries_controller_spec.rb",
     "spec/controllers/orders_controller_spec.rb",
     "spec/controllers/products_controller_spec.rb",
     "spec/controllers/states_controller_spec.rb",
     "spec/controllers/taxons_controller_spec.rb",
     "spec/lib/easy_role_requirement_system_spec.rb",
     "spec/models/address_spec.rb",
     "spec/models/app_configuration_spec.rb",
     "spec/models/creditcard_payment_spec.rb",
     "spec/models/creditcard_spec.rb",
     "spec/models/inventory_unit_spec.rb",
     "spec/models/option_type_spec.rb",
     "spec/models/option_value_spec.rb",
     "spec/models/order_spec.rb",
     "spec/models/payment_sepc.rb",
     "spec/models/product_option_type_spec.rb",
     "spec/models/product_property_spec.rb",
     "spec/models/property_spec.rb",
     "spec/models/prototype_spec.rb",
     "spec/models/shipment_spec.rb",
     "spec/models/shipping_category_spec.rb",
     "spec/models/shipping_order_spec.rb",
     "spec/models/tax_category_spec.rb",
     "spec/models/taxon_spec.rb",
     "spec/models/taxonomy_spec.rb",
     "spec/models/zone_member_spec.rb",
     "spec/models/zone_spec.rb",
     "spec/spec_helper.rb",
     "test/factories/address_factory.rb",
     "test/factories/adjustments_factory.rb",
     "test/factories/checkout_factory.rb",
     "test/factories/country_factory.rb",
     "test/factories/coupon_factory.rb",
     "test/factories/creditcard_factory.rb",
     "test/factories/inventory_unit_factory.rb",
     "test/factories/line_item_factory.rb",
     "test/factories/options_factory.rb",
     "test/factories/order_factory.rb",
     "test/factories/payment_factory.rb",
     "test/factories/preference_factory.rb",
     "test/factories/product_factory.rb",
     "test/factories/product_group_factory.rb",
     "test/factories/role_factory.rb",
     "test/factories/shipment_factory.rb",
     "test/factories/shipping_category_factory.rb",
     "test/factories/shipping_method_factory.rb",
     "test/factories/tax_category_factory.rb",
     "test/factories/tax_rate_factory.rb",
     "test/factories/taxon_factory.rb",
     "test/factories/taxonomy_factory.rb",
     "test/factories/user_factory.rb",
     "test/factories/variant_factory.rb",
     "test/factories/zone_factory.rb",
     "test/functional/admin/adjustments_controller_test.rb",
     "test/functional/admin/checkouts_controller_test.rb",
     "test/functional/admin/configurations_controller_test.rb",
     "test/functional/admin/line_items_controller_test.rb",
     "test/functional/admin/payments_controller_test.rb",
     "test/functional/admin/product_groups_controller_test.rb",
     "test/functional/admin/products_controller_test.rb",
     "test/functional/admin/reports_controller_test.rb",
     "test/functional/admin/return_authorizations_controller_test.rb",
     "test/functional/admin/shipments_controller_test.rb",
     "test/functional/calculators_controller_test.rb",
     "test/functional/checkouts_controller_test.rb",
     "test/functional/line_items_controller_test.rb",
     "test/functional/products_controller_test.rb",
     "test/functional/users_controller_test.rb",
     "test/integration/checkout_test.rb",
     "test/integration/searching_test.rb",
     "test/shoulda_macros/should_redirect.rb",
     "test/test_helper.rb",
     "test/unit/address_test.rb",
     "test/unit/adjustment_test.rb",
     "test/unit/charge_test.rb",
     "test/unit/checkout_test.rb",
     "test/unit/country_test.rb",
     "test/unit/coupon_test.rb",
     "test/unit/credit_test.rb",
     "test/unit/creditcard_payment_test.rb",
     "test/unit/creditcard_test.rb",
     "test/unit/factories_test.rb",
     "test/unit/flat_percent_item_total_test.rb",
     "test/unit/flat_rate_calculators_test.rb",
     "test/unit/flexi_rate_calculator_test.rb",
     "test/unit/has_calculator_test.rb",
     "test/unit/helpers/admin/adjustments_helper_test.rb",
     "test/unit/helpers/admin/credits_helper_test.rb",
     "test/unit/helpers/admin/return_authorizations_helper_test.rb",
     "test/unit/helpers/calculators_helper_test.rb",
     "test/unit/helpers/products_helper_test.rb",
     "test/unit/helpers/spree/base_helper_test.rb",
     "test/unit/inventory_unit_test.rb",
     "test/unit/line_item_test.rb",
     "test/unit/order_mailer_test.rb",
     "test/unit/order_state_test.rb",
     "test/unit/order_test.rb",
     "test/unit/payment_test.rb",
     "test/unit/per_item_calculator_test.rb",
     "test/unit/preference_definition_test.rb",
     "test/unit/preference_test.rb",
     "test/unit/product_group_test.rb",
     "test/unit/product_scope_test.rb",
     "test/unit/product_test.rb",
     "test/unit/return_authorization_test.rb",
     "test/unit/sales_tax_calculator_test.rb",
     "test/unit/shipment_test.rb",
     "test/unit/shipping_method_test.rb",
     "test/unit/state_event_test.rb",
     "test/unit/state_test.rb",
     "test/unit/tax_rate_test.rb",
     "test/unit/variant_test.rb",
     "test/unit/vat_calculator_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<spree-core>, ["= 0.30.0"])
    else
      s.add_dependency(%q<spree-core>, ["= 0.30.0"])
    end
  else
    s.add_dependency(%q<spree-core>, ["= 0.30.0"])
  end
end

