/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as AuthenticatedStoreIdRouteImport } from './routes/_authenticated/$storeId'
import { Route as AuthenticatedStoreIdIndexRouteImport } from './routes/_authenticated/$storeId/index'
import { Route as AuthenticatedStoreIdSettingsRouteImport } from './routes/_authenticated/$storeId/settings'
import { Route as AuthenticatedStoreIdSettingsIndexRouteImport } from './routes/_authenticated/$storeId/settings/index'
import { Route as AuthenticatedStoreIdPromotionsIndexRouteImport } from './routes/_authenticated/$storeId/promotions/index'
import { Route as AuthenticatedStoreIdProductsIndexRouteImport } from './routes/_authenticated/$storeId/products/index'
import { Route as AuthenticatedStoreIdOrdersIndexRouteImport } from './routes/_authenticated/$storeId/orders/index'
import { Route as AuthenticatedStoreIdCustomersIndexRouteImport } from './routes/_authenticated/$storeId/customers/index'
import { Route as AuthenticatedStoreIdSettingsTaxCategoriesRouteImport } from './routes/_authenticated/$storeId/settings/tax-categories'
import { Route as AuthenticatedStoreIdSettingsStoreRouteImport } from './routes/_authenticated/$storeId/settings/store'
import { Route as AuthenticatedStoreIdSettingsStockLocationsRouteImport } from './routes/_authenticated/$storeId/settings/stock-locations'
import { Route as AuthenticatedStoreIdSettingsStaffRouteImport } from './routes/_authenticated/$storeId/settings/staff'
import { Route as AuthenticatedStoreIdSettingsPaymentMethodsRouteImport } from './routes/_authenticated/$storeId/settings/payment-methods'
import { Route as AuthenticatedStoreIdSettingsCustomFieldDefinitionsRouteImport } from './routes/_authenticated/$storeId/settings/custom-field-definitions'
import { Route as AuthenticatedStoreIdSettingsApiKeysRouteImport } from './routes/_authenticated/$storeId/settings/api-keys'
import { Route as AuthenticatedStoreIdPromotionsNewRouteImport } from './routes/_authenticated/$storeId/promotions/new'
import { Route as AuthenticatedStoreIdPromotionsGiftCardsRouteImport } from './routes/_authenticated/$storeId/promotions/gift-cards'
import { Route as AuthenticatedStoreIdPromotionsPromotionIdRouteImport } from './routes/_authenticated/$storeId/promotions/$promotionId'
import { Route as AuthenticatedStoreIdProductsTransfersRouteImport } from './routes/_authenticated/$storeId/products/transfers'
import { Route as AuthenticatedStoreIdProductsOptionsRouteImport } from './routes/_authenticated/$storeId/products/options'
import { Route as AuthenticatedStoreIdProductsProductIdRouteImport } from './routes/_authenticated/$storeId/products/$productId'
import { Route as AuthenticatedStoreIdOrdersNewRouteImport } from './routes/_authenticated/$storeId/orders/new'
import { Route as AuthenticatedStoreIdOrdersDraftsRouteImport } from './routes/_authenticated/$storeId/orders/drafts'
import { Route as AuthenticatedStoreIdOrdersOrderIdRouteImport } from './routes/_authenticated/$storeId/orders/$orderId'
import { Route as AuthenticatedStoreIdCustomersGroupsRouteImport } from './routes/_authenticated/$storeId/customers/groups'
import { Route as AuthenticatedStoreIdCustomersCustomerIdRouteImport } from './routes/_authenticated/$storeId/customers/$customerId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedStoreIdRoute = AuthenticatedStoreIdRouteImport.update({
  id: '/$storeId',
  path: '/$storeId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStoreIdIndexRoute =
  AuthenticatedStoreIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdSettingsRoute =
  AuthenticatedStoreIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdSettingsIndexRoute =
  AuthenticatedStoreIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdPromotionsIndexRoute =
  AuthenticatedStoreIdPromotionsIndexRouteImport.update({
    id: '/promotions/',
    path: '/promotions/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdProductsIndexRoute =
  AuthenticatedStoreIdProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdOrdersIndexRoute =
  AuthenticatedStoreIdOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdCustomersIndexRoute =
  AuthenticatedStoreIdCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdSettingsTaxCategoriesRoute =
  AuthenticatedStoreIdSettingsTaxCategoriesRouteImport.update({
    id: '/tax-categories',
    path: '/tax-categories',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdSettingsStoreRoute =
  AuthenticatedStoreIdSettingsStoreRouteImport.update({
    id: '/store',
    path: '/store',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdSettingsStockLocationsRoute =
  AuthenticatedStoreIdSettingsStockLocationsRouteImport.update({
    id: '/stock-locations',
    path: '/stock-locations',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdSettingsStaffRoute =
  AuthenticatedStoreIdSettingsStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdSettingsPaymentMethodsRoute =
  AuthenticatedStoreIdSettingsPaymentMethodsRouteImport.update({
    id: '/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdSettingsCustomFieldDefinitionsRoute =
  AuthenticatedStoreIdSettingsCustomFieldDefinitionsRouteImport.update({
    id: '/custom-field-definitions',
    path: '/custom-field-definitions',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdSettingsApiKeysRoute =
  AuthenticatedStoreIdSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedStoreIdSettingsRoute,
  } as any)
const AuthenticatedStoreIdPromotionsNewRoute =
  AuthenticatedStoreIdPromotionsNewRouteImport.update({
    id: '/promotions/new',
    path: '/promotions/new',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdPromotionsGiftCardsRoute =
  AuthenticatedStoreIdPromotionsGiftCardsRouteImport.update({
    id: '/promotions/gift-cards',
    path: '/promotions/gift-cards',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdPromotionsPromotionIdRoute =
  AuthenticatedStoreIdPromotionsPromotionIdRouteImport.update({
    id: '/promotions/$promotionId',
    path: '/promotions/$promotionId',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdProductsTransfersRoute =
  AuthenticatedStoreIdProductsTransfersRouteImport.update({
    id: '/products/transfers',
    path: '/products/transfers',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdProductsOptionsRoute =
  AuthenticatedStoreIdProductsOptionsRouteImport.update({
    id: '/products/options',
    path: '/products/options',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdProductsProductIdRoute =
  AuthenticatedStoreIdProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdOrdersNewRoute =
  AuthenticatedStoreIdOrdersNewRouteImport.update({
    id: '/orders/new',
    path: '/orders/new',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdOrdersDraftsRoute =
  AuthenticatedStoreIdOrdersDraftsRouteImport.update({
    id: '/orders/drafts',
    path: '/orders/drafts',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdOrdersOrderIdRoute =
  AuthenticatedStoreIdOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdCustomersGroupsRoute =
  AuthenticatedStoreIdCustomersGroupsRouteImport.update({
    id: '/customers/groups',
    path: '/customers/groups',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdCustomersCustomerIdRoute =
  AuthenticatedStoreIdCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/$storeId': typeof AuthenticatedStoreIdRouteWithChildren
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/$storeId/settings': typeof AuthenticatedStoreIdSettingsRouteWithChildren
  '/$storeId/': typeof AuthenticatedStoreIdIndexRoute
  '/$storeId/customers/$customerId': typeof AuthenticatedStoreIdCustomersCustomerIdRoute
  '/$storeId/customers/groups': typeof AuthenticatedStoreIdCustomersGroupsRoute
  '/$storeId/orders/$orderId': typeof AuthenticatedStoreIdOrdersOrderIdRoute
  '/$storeId/orders/drafts': typeof AuthenticatedStoreIdOrdersDraftsRoute
  '/$storeId/orders/new': typeof AuthenticatedStoreIdOrdersNewRoute
  '/$storeId/products/$productId': typeof AuthenticatedStoreIdProductsProductIdRoute
  '/$storeId/products/options': typeof AuthenticatedStoreIdProductsOptionsRoute
  '/$storeId/products/transfers': typeof AuthenticatedStoreIdProductsTransfersRoute
  '/$storeId/promotions/$promotionId': typeof AuthenticatedStoreIdPromotionsPromotionIdRoute
  '/$storeId/promotions/gift-cards': typeof AuthenticatedStoreIdPromotionsGiftCardsRoute
  '/$storeId/promotions/new': typeof AuthenticatedStoreIdPromotionsNewRoute
  '/$storeId/settings/api-keys': typeof AuthenticatedStoreIdSettingsApiKeysRoute
  '/$storeId/settings/custom-field-definitions': typeof AuthenticatedStoreIdSettingsCustomFieldDefinitionsRoute
  '/$storeId/settings/payment-methods': typeof AuthenticatedStoreIdSettingsPaymentMethodsRoute
  '/$storeId/settings/staff': typeof AuthenticatedStoreIdSettingsStaffRoute
  '/$storeId/settings/stock-locations': typeof AuthenticatedStoreIdSettingsStockLocationsRoute
  '/$storeId/settings/store': typeof AuthenticatedStoreIdSettingsStoreRoute
  '/$storeId/settings/tax-categories': typeof AuthenticatedStoreIdSettingsTaxCategoriesRoute
  '/$storeId/customers/': typeof AuthenticatedStoreIdCustomersIndexRoute
  '/$storeId/orders/': typeof AuthenticatedStoreIdOrdersIndexRoute
  '/$storeId/products/': typeof AuthenticatedStoreIdProductsIndexRoute
  '/$storeId/promotions/': typeof AuthenticatedStoreIdPromotionsIndexRoute
  '/$storeId/settings/': typeof AuthenticatedStoreIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/$storeId': typeof AuthenticatedStoreIdIndexRoute
  '/$storeId/customers/$customerId': typeof AuthenticatedStoreIdCustomersCustomerIdRoute
  '/$storeId/customers/groups': typeof AuthenticatedStoreIdCustomersGroupsRoute
  '/$storeId/orders/$orderId': typeof AuthenticatedStoreIdOrdersOrderIdRoute
  '/$storeId/orders/drafts': typeof AuthenticatedStoreIdOrdersDraftsRoute
  '/$storeId/orders/new': typeof AuthenticatedStoreIdOrdersNewRoute
  '/$storeId/products/$productId': typeof AuthenticatedStoreIdProductsProductIdRoute
  '/$storeId/products/options': typeof AuthenticatedStoreIdProductsOptionsRoute
  '/$storeId/products/transfers': typeof AuthenticatedStoreIdProductsTransfersRoute
  '/$storeId/promotions/$promotionId': typeof AuthenticatedStoreIdPromotionsPromotionIdRoute
  '/$storeId/promotions/gift-cards': typeof AuthenticatedStoreIdPromotionsGiftCardsRoute
  '/$storeId/promotions/new': typeof AuthenticatedStoreIdPromotionsNewRoute
  '/$storeId/settings/api-keys': typeof AuthenticatedStoreIdSettingsApiKeysRoute
  '/$storeId/settings/custom-field-definitions': typeof AuthenticatedStoreIdSettingsCustomFieldDefinitionsRoute
  '/$storeId/settings/payment-methods': typeof AuthenticatedStoreIdSettingsPaymentMethodsRoute
  '/$storeId/settings/staff': typeof AuthenticatedStoreIdSettingsStaffRoute
  '/$storeId/settings/stock-locations': typeof AuthenticatedStoreIdSettingsStockLocationsRoute
  '/$storeId/settings/store': typeof AuthenticatedStoreIdSettingsStoreRoute
  '/$storeId/settings/tax-categories': typeof AuthenticatedStoreIdSettingsTaxCategoriesRoute
  '/$storeId/customers': typeof AuthenticatedStoreIdCustomersIndexRoute
  '/$storeId/orders': typeof AuthenticatedStoreIdOrdersIndexRoute
  '/$storeId/products': typeof AuthenticatedStoreIdProductsIndexRoute
  '/$storeId/promotions': typeof AuthenticatedStoreIdPromotionsIndexRoute
  '/$storeId/settings': typeof AuthenticatedStoreIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/$storeId': typeof AuthenticatedStoreIdRouteWithChildren
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$storeId/settings': typeof AuthenticatedStoreIdSettingsRouteWithChildren
  '/_authenticated/$storeId/': typeof AuthenticatedStoreIdIndexRoute
  '/_authenticated/$storeId/customers/$customerId': typeof AuthenticatedStoreIdCustomersCustomerIdRoute
  '/_authenticated/$storeId/customers/groups': typeof AuthenticatedStoreIdCustomersGroupsRoute
  '/_authenticated/$storeId/orders/$orderId': typeof AuthenticatedStoreIdOrdersOrderIdRoute
  '/_authenticated/$storeId/orders/drafts': typeof AuthenticatedStoreIdOrdersDraftsRoute
  '/_authenticated/$storeId/orders/new': typeof AuthenticatedStoreIdOrdersNewRoute
  '/_authenticated/$storeId/products/$productId': typeof AuthenticatedStoreIdProductsProductIdRoute
  '/_authenticated/$storeId/products/options': typeof AuthenticatedStoreIdProductsOptionsRoute
  '/_authenticated/$storeId/products/transfers': typeof AuthenticatedStoreIdProductsTransfersRoute
  '/_authenticated/$storeId/promotions/$promotionId': typeof AuthenticatedStoreIdPromotionsPromotionIdRoute
  '/_authenticated/$storeId/promotions/gift-cards': typeof AuthenticatedStoreIdPromotionsGiftCardsRoute
  '/_authenticated/$storeId/promotions/new': typeof AuthenticatedStoreIdPromotionsNewRoute
  '/_authenticated/$storeId/settings/api-keys': typeof AuthenticatedStoreIdSettingsApiKeysRoute
  '/_authenticated/$storeId/settings/custom-field-definitions': typeof AuthenticatedStoreIdSettingsCustomFieldDefinitionsRoute
  '/_authenticated/$storeId/settings/payment-methods': typeof AuthenticatedStoreIdSettingsPaymentMethodsRoute
  '/_authenticated/$storeId/settings/staff': typeof AuthenticatedStoreIdSettingsStaffRoute
  '/_authenticated/$storeId/settings/stock-locations': typeof AuthenticatedStoreIdSettingsStockLocationsRoute
  '/_authenticated/$storeId/settings/store': typeof AuthenticatedStoreIdSettingsStoreRoute
  '/_authenticated/$storeId/settings/tax-categories': typeof AuthenticatedStoreIdSettingsTaxCategoriesRoute
  '/_authenticated/$storeId/customers/': typeof AuthenticatedStoreIdCustomersIndexRoute
  '/_authenticated/$storeId/orders/': typeof AuthenticatedStoreIdOrdersIndexRoute
  '/_authenticated/$storeId/products/': typeof AuthenticatedStoreIdProductsIndexRoute
  '/_authenticated/$storeId/promotions/': typeof AuthenticatedStoreIdPromotionsIndexRoute
  '/_authenticated/$storeId/settings/': typeof AuthenticatedStoreIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$storeId'
    | '/accept-invitation/$invitationId'
    | '/$storeId/settings'
    | '/$storeId/'
    | '/$storeId/customers/$customerId'
    | '/$storeId/customers/groups'
    | '/$storeId/orders/$orderId'
    | '/$storeId/orders/drafts'
    | '/$storeId/orders/new'
    | '/$storeId/products/$productId'
    | '/$storeId/products/options'
    | '/$storeId/products/transfers'
    | '/$storeId/promotions/$promotionId'
    | '/$storeId/promotions/gift-cards'
    | '/$storeId/promotions/new'
    | '/$storeId/settings/api-keys'
    | '/$storeId/settings/custom-field-definitions'
    | '/$storeId/settings/payment-methods'
    | '/$storeId/settings/staff'
    | '/$storeId/settings/stock-locations'
    | '/$storeId/settings/store'
    | '/$storeId/settings/tax-categories'
    | '/$storeId/customers/'
    | '/$storeId/orders/'
    | '/$storeId/products/'
    | '/$storeId/promotions/'
    | '/$storeId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/accept-invitation/$invitationId'
    | '/'
    | '/$storeId'
    | '/$storeId/customers/$customerId'
    | '/$storeId/customers/groups'
    | '/$storeId/orders/$orderId'
    | '/$storeId/orders/drafts'
    | '/$storeId/orders/new'
    | '/$storeId/products/$productId'
    | '/$storeId/products/options'
    | '/$storeId/products/transfers'
    | '/$storeId/promotions/$promotionId'
    | '/$storeId/promotions/gift-cards'
    | '/$storeId/promotions/new'
    | '/$storeId/settings/api-keys'
    | '/$storeId/settings/custom-field-definitions'
    | '/$storeId/settings/payment-methods'
    | '/$storeId/settings/staff'
    | '/$storeId/settings/stock-locations'
    | '/$storeId/settings/store'
    | '/$storeId/settings/tax-categories'
    | '/$storeId/customers'
    | '/$storeId/orders'
    | '/$storeId/products'
    | '/$storeId/promotions'
    | '/$storeId/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/$storeId'
    | '/accept-invitation/$invitationId'
    | '/_authenticated/'
    | '/_authenticated/$storeId/settings'
    | '/_authenticated/$storeId/'
    | '/_authenticated/$storeId/customers/$customerId'
    | '/_authenticated/$storeId/customers/groups'
    | '/_authenticated/$storeId/orders/$orderId'
    | '/_authenticated/$storeId/orders/drafts'
    | '/_authenticated/$storeId/orders/new'
    | '/_authenticated/$storeId/products/$productId'
    | '/_authenticated/$storeId/products/options'
    | '/_authenticated/$storeId/products/transfers'
    | '/_authenticated/$storeId/promotions/$promotionId'
    | '/_authenticated/$storeId/promotions/gift-cards'
    | '/_authenticated/$storeId/promotions/new'
    | '/_authenticated/$storeId/settings/api-keys'
    | '/_authenticated/$storeId/settings/custom-field-definitions'
    | '/_authenticated/$storeId/settings/payment-methods'
    | '/_authenticated/$storeId/settings/staff'
    | '/_authenticated/$storeId/settings/stock-locations'
    | '/_authenticated/$storeId/settings/store'
    | '/_authenticated/$storeId/settings/tax-categories'
    | '/_authenticated/$storeId/customers/'
    | '/_authenticated/$storeId/orders/'
    | '/_authenticated/$storeId/products/'
    | '/_authenticated/$storeId/promotions/'
    | '/_authenticated/$storeId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$storeId': {
      id: '/_authenticated/$storeId'
      path: '/$storeId'
      fullPath: '/$storeId'
      preLoaderRoute: typeof AuthenticatedStoreIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$storeId/': {
      id: '/_authenticated/$storeId/'
      path: '/'
      fullPath: '/$storeId/'
      preLoaderRoute: typeof AuthenticatedStoreIdIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/settings': {
      id: '/_authenticated/$storeId/settings'
      path: '/settings'
      fullPath: '/$storeId/settings'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/settings/': {
      id: '/_authenticated/$storeId/settings/'
      path: '/'
      fullPath: '/$storeId/settings/'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/promotions/': {
      id: '/_authenticated/$storeId/promotions/'
      path: '/promotions'
      fullPath: '/$storeId/promotions/'
      preLoaderRoute: typeof AuthenticatedStoreIdPromotionsIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/': {
      id: '/_authenticated/$storeId/products/'
      path: '/products'
      fullPath: '/$storeId/products/'
      preLoaderRoute: typeof AuthenticatedStoreIdProductsIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/orders/': {
      id: '/_authenticated/$storeId/orders/'
      path: '/orders'
      fullPath: '/$storeId/orders/'
      preLoaderRoute: typeof AuthenticatedStoreIdOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/customers/': {
      id: '/_authenticated/$storeId/customers/'
      path: '/customers'
      fullPath: '/$storeId/customers/'
      preLoaderRoute: typeof AuthenticatedStoreIdCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/settings/tax-categories': {
      id: '/_authenticated/$storeId/settings/tax-categories'
      path: '/tax-categories'
      fullPath: '/$storeId/settings/tax-categories'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsTaxCategoriesRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/settings/store': {
      id: '/_authenticated/$storeId/settings/store'
      path: '/store'
      fullPath: '/$storeId/settings/store'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsStoreRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/settings/stock-locations': {
      id: '/_authenticated/$storeId/settings/stock-locations'
      path: '/stock-locations'
      fullPath: '/$storeId/settings/stock-locations'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsStockLocationsRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/settings/staff': {
      id: '/_authenticated/$storeId/settings/staff'
      path: '/staff'
      fullPath: '/$storeId/settings/staff'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsStaffRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/settings/payment-methods': {
      id: '/_authenticated/$storeId/settings/payment-methods'
      path: '/payment-methods'
      fullPath: '/$storeId/settings/payment-methods'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsPaymentMethodsRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/settings/custom-field-definitions': {
      id: '/_authenticated/$storeId/settings/custom-field-definitions'
      path: '/custom-field-definitions'
      fullPath: '/$storeId/settings/custom-field-definitions'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsCustomFieldDefinitionsRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/settings/api-keys': {
      id: '/_authenticated/$storeId/settings/api-keys'
      path: '/api-keys'
      fullPath: '/$storeId/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedStoreIdSettingsRoute
    }
    '/_authenticated/$storeId/promotions/new': {
      id: '/_authenticated/$storeId/promotions/new'
      path: '/promotions/new'
      fullPath: '/$storeId/promotions/new'
      preLoaderRoute: typeof AuthenticatedStoreIdPromotionsNewRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/promotions/gift-cards': {
      id: '/_authenticated/$storeId/promotions/gift-cards'
      path: '/promotions/gift-cards'
      fullPath: '/$storeId/promotions/gift-cards'
      preLoaderRoute: typeof AuthenticatedStoreIdPromotionsGiftCardsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/promotions/$promotionId': {
      id: '/_authenticated/$storeId/promotions/$promotionId'
      path: '/promotions/$promotionId'
      fullPath: '/$storeId/promotions/$promotionId'
      preLoaderRoute: typeof AuthenticatedStoreIdPromotionsPromotionIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/transfers': {
      id: '/_authenticated/$storeId/products/transfers'
      path: '/products/transfers'
      fullPath: '/$storeId/products/transfers'
      preLoaderRoute: typeof AuthenticatedStoreIdProductsTransfersRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/options': {
      id: '/_authenticated/$storeId/products/options'
      path: '/products/options'
      fullPath: '/$storeId/products/options'
      preLoaderRoute: typeof AuthenticatedStoreIdProductsOptionsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/$productId': {
      id: '/_authenticated/$storeId/products/$productId'
      path: '/products/$productId'
      fullPath: '/$storeId/products/$productId'
      preLoaderRoute: typeof AuthenticatedStoreIdProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/orders/new': {
      id: '/_authenticated/$storeId/orders/new'
      path: '/orders/new'
      fullPath: '/$storeId/orders/new'
      preLoaderRoute: typeof AuthenticatedStoreIdOrdersNewRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/orders/drafts': {
      id: '/_authenticated/$storeId/orders/drafts'
      path: '/orders/drafts'
      fullPath: '/$storeId/orders/drafts'
      preLoaderRoute: typeof AuthenticatedStoreIdOrdersDraftsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/orders/$orderId': {
      id: '/_authenticated/$storeId/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/$storeId/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedStoreIdOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/customers/groups': {
      id: '/_authenticated/$storeId/customers/groups'
      path: '/customers/groups'
      fullPath: '/$storeId/customers/groups'
      preLoaderRoute: typeof AuthenticatedStoreIdCustomersGroupsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/customers/$customerId': {
      id: '/_authenticated/$storeId/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/$storeId/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedStoreIdCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
  }
}

interface AuthenticatedStoreIdSettingsRouteChildren {
  AuthenticatedStoreIdSettingsApiKeysRoute: typeof AuthenticatedStoreIdSettingsApiKeysRoute
  AuthenticatedStoreIdSettingsCustomFieldDefinitionsRoute: typeof AuthenticatedStoreIdSettingsCustomFieldDefinitionsRoute
  AuthenticatedStoreIdSettingsPaymentMethodsRoute: typeof AuthenticatedStoreIdSettingsPaymentMethodsRoute
  AuthenticatedStoreIdSettingsStaffRoute: typeof AuthenticatedStoreIdSettingsStaffRoute
  AuthenticatedStoreIdSettingsStockLocationsRoute: typeof AuthenticatedStoreIdSettingsStockLocationsRoute
  AuthenticatedStoreIdSettingsStoreRoute: typeof AuthenticatedStoreIdSettingsStoreRoute
  AuthenticatedStoreIdSettingsTaxCategoriesRoute: typeof AuthenticatedStoreIdSettingsTaxCategoriesRoute
  AuthenticatedStoreIdSettingsIndexRoute: typeof AuthenticatedStoreIdSettingsIndexRoute
}

const AuthenticatedStoreIdSettingsRouteChildren: AuthenticatedStoreIdSettingsRouteChildren =
  {
    AuthenticatedStoreIdSettingsApiKeysRoute:
      AuthenticatedStoreIdSettingsApiKeysRoute,
    AuthenticatedStoreIdSettingsCustomFieldDefinitionsRoute:
      AuthenticatedStoreIdSettingsCustomFieldDefinitionsRoute,
    AuthenticatedStoreIdSettingsPaymentMethodsRoute:
      AuthenticatedStoreIdSettingsPaymentMethodsRoute,
    AuthenticatedStoreIdSettingsStaffRoute:
      AuthenticatedStoreIdSettingsStaffRoute,
    AuthenticatedStoreIdSettingsStockLocationsRoute:
      AuthenticatedStoreIdSettingsStockLocationsRoute,
    AuthenticatedStoreIdSettingsStoreRoute:
      AuthenticatedStoreIdSettingsStoreRoute,
    AuthenticatedStoreIdSettingsTaxCategoriesRoute:
      AuthenticatedStoreIdSettingsTaxCategoriesRoute,
    AuthenticatedStoreIdSettingsIndexRoute:
      AuthenticatedStoreIdSettingsIndexRoute,
  }

const AuthenticatedStoreIdSettingsRouteWithChildren =
  AuthenticatedStoreIdSettingsRoute._addFileChildren(
    AuthenticatedStoreIdSettingsRouteChildren,
  )

interface AuthenticatedStoreIdRouteChildren {
  AuthenticatedStoreIdSettingsRoute: typeof AuthenticatedStoreIdSettingsRouteWithChildren
  AuthenticatedStoreIdIndexRoute: typeof AuthenticatedStoreIdIndexRoute
  AuthenticatedStoreIdCustomersCustomerIdRoute: typeof AuthenticatedStoreIdCustomersCustomerIdRoute
  AuthenticatedStoreIdCustomersGroupsRoute: typeof AuthenticatedStoreIdCustomersGroupsRoute
  AuthenticatedStoreIdOrdersOrderIdRoute: typeof AuthenticatedStoreIdOrdersOrderIdRoute
  AuthenticatedStoreIdOrdersDraftsRoute: typeof AuthenticatedStoreIdOrdersDraftsRoute
  AuthenticatedStoreIdOrdersNewRoute: typeof AuthenticatedStoreIdOrdersNewRoute
  AuthenticatedStoreIdProductsProductIdRoute: typeof AuthenticatedStoreIdProductsProductIdRoute
  AuthenticatedStoreIdProductsOptionsRoute: typeof AuthenticatedStoreIdProductsOptionsRoute
  AuthenticatedStoreIdProductsTransfersRoute: typeof AuthenticatedStoreIdProductsTransfersRoute
  AuthenticatedStoreIdPromotionsPromotionIdRoute: typeof AuthenticatedStoreIdPromotionsPromotionIdRoute
  AuthenticatedStoreIdPromotionsGiftCardsRoute: typeof AuthenticatedStoreIdPromotionsGiftCardsRoute
  AuthenticatedStoreIdPromotionsNewRoute: typeof AuthenticatedStoreIdPromotionsNewRoute
  AuthenticatedStoreIdCustomersIndexRoute: typeof AuthenticatedStoreIdCustomersIndexRoute
  AuthenticatedStoreIdOrdersIndexRoute: typeof AuthenticatedStoreIdOrdersIndexRoute
  AuthenticatedStoreIdProductsIndexRoute: typeof AuthenticatedStoreIdProductsIndexRoute
  AuthenticatedStoreIdPromotionsIndexRoute: typeof AuthenticatedStoreIdPromotionsIndexRoute
}

const AuthenticatedStoreIdRouteChildren: AuthenticatedStoreIdRouteChildren = {
  AuthenticatedStoreIdSettingsRoute:
    AuthenticatedStoreIdSettingsRouteWithChildren,
  AuthenticatedStoreIdIndexRoute: AuthenticatedStoreIdIndexRoute,
  AuthenticatedStoreIdCustomersCustomerIdRoute:
    AuthenticatedStoreIdCustomersCustomerIdRoute,
  AuthenticatedStoreIdCustomersGroupsRoute:
    AuthenticatedStoreIdCustomersGroupsRoute,
  AuthenticatedStoreIdOrdersOrderIdRoute:
    AuthenticatedStoreIdOrdersOrderIdRoute,
  AuthenticatedStoreIdOrdersDraftsRoute: AuthenticatedStoreIdOrdersDraftsRoute,
  AuthenticatedStoreIdOrdersNewRoute: AuthenticatedStoreIdOrdersNewRoute,
  AuthenticatedStoreIdProductsProductIdRoute:
    AuthenticatedStoreIdProductsProductIdRoute,
  AuthenticatedStoreIdProductsOptionsRoute:
    AuthenticatedStoreIdProductsOptionsRoute,
  AuthenticatedStoreIdProductsTransfersRoute:
    AuthenticatedStoreIdProductsTransfersRoute,
  AuthenticatedStoreIdPromotionsPromotionIdRoute:
    AuthenticatedStoreIdPromotionsPromotionIdRoute,
  AuthenticatedStoreIdPromotionsGiftCardsRoute:
    AuthenticatedStoreIdPromotionsGiftCardsRoute,
  AuthenticatedStoreIdPromotionsNewRoute:
    AuthenticatedStoreIdPromotionsNewRoute,
  AuthenticatedStoreIdCustomersIndexRoute:
    AuthenticatedStoreIdCustomersIndexRoute,
  AuthenticatedStoreIdOrdersIndexRoute: AuthenticatedStoreIdOrdersIndexRoute,
  AuthenticatedStoreIdProductsIndexRoute:
    AuthenticatedStoreIdProductsIndexRoute,
  AuthenticatedStoreIdPromotionsIndexRoute:
    AuthenticatedStoreIdPromotionsIndexRoute,
}

const AuthenticatedStoreIdRouteWithChildren =
  AuthenticatedStoreIdRoute._addFileChildren(AuthenticatedStoreIdRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedStoreIdRoute: typeof AuthenticatedStoreIdRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedStoreIdRoute: AuthenticatedStoreIdRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
