// Renders the list filter types: the ones each SDK publishes, generated from
// its API reference (`pnpm generate:filters`), and an app's own, generated
// from the app's live filter tables (`spree filters types`). Both read the
// tables the Ransack allowlists produce, so the types say exactly what the API
// accepts.

import { FILTER_PREDICATES } from './filters'

const PACKAGE_HEADER =
  '// This file is auto-generated from the filter tables in docs/api-reference by `pnpm generate:filters`. Do not edit directly.\n'
const APP_HEADER =
  "// This file is generated by `spree filters types` from this app's filter tables. Do not edit it; run the command again after changing a filter.\n"

type Kind =
  | 'text'
  | 'decimal'
  | 'integer'
  | 'date'
  | 'datetime'
  | 'enum'
  | 'id'
  | 'type'
  | 'boolean'
type AttributeKind = Kind | { enum: string[] }
type ScopeType = Kind | Kind[] | { list: Kind }

interface FilterTable {
  attributes: Record<string, AttributeKind>
  associations: Record<string, string>
  scopes: Record<string, ScopeType>
}

interface EndpointFilters {
  table: string
  sortable: string[]
  custom_fields?: boolean
}

export interface FilterSpec {
  paths: Record<string, Record<string, { 'x-spree-filters'?: EndpointFilters }>>
  components?: {
    'x-spree-filter-tables'?: Record<string, FilterTable>
    'x-spree-filter-predicates'?: Record<Kind, string[]>
  }
}

const PREDICATE_GROUPS: Record<Kind, keyof typeof FILTER_PREDICATES> = {
  text: 'text',
  decimal: 'range',
  integer: 'range',
  date: 'range',
  datetime: 'range',
  enum: 'equality',
  id: 'equality',
  type: 'equality',
  boolean: 'boolean',
}

// The building blocks in sdk-core hard-code the predicates per kind; a spec
// publishing a different set means one side changed without the other.
function checkPredicates(published: Record<Kind, string[]> | undefined) {
  if (!published) throw new Error('The API reference publishes no x-spree-filter-predicates')

  for (const [kind, predicates] of Object.entries(published) as [Kind, string[]][]) {
    const group = FILTER_PREDICATES[PREDICATE_GROUPS[kind]]
    const known = [...group.value, ...group.list, ...group.flag].sort()
    if (known.join(' ') !== [...predicates].sort().join(' ')) {
      throw new Error(
        `Predicates for ${kind} differ: the API publishes ${predicates.join(', ')}, sdk-core has ${known.join(', ')}`,
      )
    }
  }
}

const MAX_DEPTH = 2
const PACKAGES: Record<string, string> = {
  store: '@spree/sdk',
  admin: '@spree/admin-sdk',
  seller: '@spree/seller-sdk',
}

// Each kind's TypeScript value and the sdk-core building block typing its
// predicates. Enum attributes carry their values and use `EnumFilters`.
const KIND_TYPES: Record<Exclude<Kind, 'enum'>, { value: string; block: string }> = {
  text: { value: 'string', block: 'TextFilters<$names>' },
  decimal: { value: 'string', block: 'RangeFilters<$names>' },
  integer: { value: 'number', block: 'RangeFilters<$names, number>' },
  date: { value: 'string', block: 'RangeFilters<$names>' },
  datetime: { value: 'string', block: 'RangeFilters<$names>' },
  id: { value: 'string', block: 'IdFilters<$names>' },
  type: { value: 'string', block: 'IdFilters<$names>' },
  boolean: { value: 'boolean', block: 'BooleanFilters<$names>' },
}

const valueType = (kind: Kind) => (kind === 'enum' ? 'string' : KIND_TYPES[kind].value)

const literal = (value: string) => `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
const union = (values: string[]) => values.map(literal).join(' | ')

function fieldsType(table: FilterTable): string {
  const byBlock = new Map<string, string[]>()
  const enums: string[] = []

  for (const [attribute, kind] of Object.entries(table.attributes)) {
    if (typeof kind === 'object') {
      enums.push(`Filter.EnumFilters<${literal(attribute)}, ${union(kind.enum)}>`)
      continue
    }
    const block = KIND_TYPES[kind as Exclude<Kind, 'enum'>].block
    byBlock.set(block, [...(byBlock.get(block) ?? []), attribute])
  }

  const parts = [...byBlock].map(
    ([block, names]) => `Filter.${block.replace('$names', union(names))}`,
  )
  parts.push(...enums)

  return parts.length ? parts.join('\n  & ') : 'Record<never, never>'
}

function scopeValueType(type: ScopeType): string {
  if (Array.isArray(type)) return `[${type.map(valueType).join(', ')}]`
  if (typeof type === 'object') return `${valueType(type.list)} | ${valueType(type.list)}[]`
  return valueType(type)
}

function scopesType(table: FilterTable): string | null {
  const entries = Object.entries(table.scopes)
  if (!entries.length) return null

  return `{\n${entries.map(([scope, type]) => `    ${scope}?: ${scopeValueType(type)}`).join('\n')}\n  }`
}

function associationsType(
  tables: Record<string, FilterTable>,
  table: FilterTable,
  depth: number,
  prefix = '',
): string[] {
  if (depth >= MAX_DEPTH) return []

  return Object.entries(table.associations).map(([association, target]) => {
    const nested = associationsType(tables, tables[target], depth + 1, prefix)
    const inner = [`${prefix}${target}Fields`, ...nested].join(' & ')
    return `Filter.Prefixed<'${association}_', ${inner}>`
  })
}

interface Group {
  table: string
  search: boolean
  sortable: Set<string>
}

// Endpoints listing the same records share one type, keyed by what they
// accept: the search-backed lists (custom fields, provider sorts) get their
// own `<Table>Search…` types when plain lists of the same records exist too.
function endpointGroups(spec: FilterSpec): Group[] {
  const groups = new Map<string, Group>()
  for (const operations of Object.values(spec.paths)) {
    const filters = operations.get?.['x-spree-filters']
    if (!filters) continue

    const search = Boolean(filters.custom_fields)
    const key = `${filters.table}:${search}`
    const group = groups.get(key) ?? { table: filters.table, search, sortable: new Set<string>() }
    for (const field of filters.sortable) group.sortable.add(field)
    groups.set(key, group)
  }

  return [...groups.values()].sort(
    (a, b) => a.table.localeCompare(b.table) || Number(a.search) - Number(b.search),
  )
}

function rootType(tables: Record<string, FilterTable>, name: string, prefix = ''): string[] {
  const table = tables[name]
  const parts = [`${prefix}${name}Fields`, ...associationsType(tables, table, 0, prefix)]
  const scopes = scopesType(table)
  if (scopes) parts.push(scopes)
  return parts
}

/**
 * The list filter and sort types an SDK publishes, from its API reference.
 *
 * @param spec the parsed `docs/api-reference/<api>.yaml`
 * @param api `store`, `admin` or `seller`
 */
export function renderFilterTypes(spec: FilterSpec, api: string): string {
  checkPredicates(spec.components?.['x-spree-filter-predicates'])
  const tables = spec.components?.['x-spree-filter-tables'] ?? {}
  const groups = endpointGroups(spec)
  const out: string[] = []

  for (const name of Object.keys(tables).sort()) {
    out.push(`export type ${name}Fields = ${fieldsType(tables[name])}`, '')
  }

  for (const { table: name, search, sortable } of groups) {
    const typeName =
      search && groups.some((g) => g.table === name && !g.search) ? `${name}Search` : name
    const parts = [...rootType(tables, name), 'Filter.OrFilters']
    if (search) parts.push('Filter.CustomFieldValueFilters')

    const fields = [
      ...(sortable.size ? [union([...sortable].sort())] : []),
      `(keyof ${name}SortExtensions & string)`,
    ]
    // biome-ignore lint/suspicious/noTemplateCurlyInString: a TypeScript template type, emitted as written
    if (search) fields.push('`cf_${string}`')

    // Filters an app adds through its own extensions, which the published
    // types cannot know about: `spree filters types` writes them here.
    if (typeName === name) {
      out.push(
        '/**',
        ` * Filters your app adds to ${name} lists. Generate them with \`spree filters types\`,`,
        ' * or declare them by hand in a file that has an `export`:',
        ' *',
        ' *     export {}',
        ` *     declare module '${PACKAGES[api]}' {`,
        ` *       interface ${name}FilterExtensions { erp_id_eq?: string }`,
        ' *     }',
        ' */',
        `export interface ${name}FilterExtensions {}`,
        '',
        `/** Sort fields your app adds to ${name} lists, as keys: \`{ erp_id: true }\`. */`,
        `export interface ${name}SortExtensions {}`,
        '',
      )
    }
    parts.push(`${name}FilterExtensions`)
    out.push(`export type ${typeName}Filters = ${parts.join('\n  & ')}`, '')
    out.push(`export type ${typeName}Sort = Filter.SortKey<${fields.join(' | ')}>`, '')
  }

  // A namespace import, so no table name can collide with a building block.
  return `${PACKAGE_HEADER}\nimport type * as Filter from '@spree/sdk-core'\n\n${out.join('\n').trimEnd()}\n`
}

/**
 * A declaration file for an app's own list filters: it extends each
 * resource's `…FilterExtensions` and `…SortExtensions` in the SDK with
 * everything the app's filter tables hold, the app's own filters included.
 *
 * @param spec the app's filter tables (`bin/rails spree:api:filter_tables`)
 * @param api `store`, `admin` or `seller`
 */
export function renderAppFilterTypes(spec: FilterSpec, api: string): string {
  checkPredicates(spec.components?.['x-spree-filter-predicates'])
  const tables = spec.components?.['x-spree-filter-tables'] ?? {}
  const roots = new Map<string, Set<string>>()
  for (const { table, sortable } of endpointGroups(spec)) {
    const fields = roots.get(table) ?? new Set<string>()
    for (const field of sortable) fields.add(field)
    roots.set(table, fields)
  }

  const out: string[] = []
  for (const name of Object.keys(tables).sort()) {
    out.push(`type App${name}Fields = ${fieldsType(tables[name])}`, '')
  }
  for (const name of [...roots.keys()].sort()) {
    out.push(`type App${name}Filters = ${rootType(tables, name, 'App').join('\n  & ')}`, '')
  }

  const declarations = [...roots]
    .sort(([a], [b]) => a.localeCompare(b))
    .flatMap(([name, sortable]) => [
      `  interface ${name}FilterExtensions extends App${name}Filters {}`,
      `  interface ${name}SortExtensions {${[...sortable]
        .sort()
        .map((field) => ` ${literal(field)}: true;`)
        .join('')} }`,
    ])

  return [
    APP_HEADER,
    `import type * as Filter from '${PACKAGES[api]}'`,
    '',
    out.join('\n').trimEnd(),
    '',
    `declare module '${PACKAGES[api]}' {`,
    ...declarations,
    '}',
    '',
  ].join('\n')
}
