source 'http://rubygems.org'

gem 'rails', '~> 3.0.0'
gem 'sqlite3-ruby', :require => 'sqlite3'

gemspec

group :test do
  gem 'rspec-rails', '2.0.0.beta.19'
  gem 'fabrication'
  gem 'thor'
end

group :cucumber do
  gem 'cucumber-rails', '~> 0.3.2'
  gem 'database_cleaner', '~> 0.5.2'
  gem 'capybara', '~> 0.3.9', :require => false
end

group :test_rails_app do
  gem 'spree_core', :path => '.'
  gem 'spree_auth', :path => '../auth'
end