require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rake/packagetask'
require 'rake/gempackagetask'

require 'lib/spree/i18n_utils'
include Spree::I18nUtils

spec = eval(File.read('spree_core.gemspec'))

Rake::GemPackageTask.new(spec) do |p|
  p.gem_spec = spec
end

desc "Release to gemcutter"
task :release => :package do
  require 'rake/gemcutter'
  Rake::Gemcutter::Tasks.new(spec).define
  Rake::Task['gem:push'].invoke
end

desc "Default Task"
task :default => [ :spec ]

require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new

require 'cucumber/rake/task'
Cucumber::Rake::Task.new do |t|
  t.cucumber_opts = %w{--format pretty}
end

desc "Regenerates a rails 3 app for testing"
task :test_app do
  require '../lib/generators/spree/test_app_generator'
  class CoreTestAppGenerator < Spree::Generators::TestAppGenerator
    def tweak_gemfile
      append_file 'Gemfile' do
        "gem 'spree_core', :path => '../..'"
      end
    end

    def install_spree_core
      inside "test_app" do
        run 'rake spree_core:install'
      end
    end

    def migrate_db
      run_migrations
    end
  end
  CoreTestAppGenerator.start
end

namespace :test_app do
  desc 'Rebuild test and cucumber databases'
  task :rebuild_dbs do
    system("cd spec/test_app && rake db:drop db:migrate RAILS_ENV=test && rake db:drop db:migrate RAILS_ENV=cucumber")
  end
end



namespace :spree do
  namespace :i18n do

    desc "Create a new translation file based on en"
    task :sort  do
      (dummy_comments, words) = read_file(File.dirname(__FILE__) + "/config/locales/en.yml", "en")
      words
      write_file "./config/locales/en.yml", "en", '---', words, false
    end

  end
end


