eval_gemfile("Gemfile.common")

gem "spree", path: "../spree"
gem "spree_emails", path: "../spree/emails"
gem "spree_admin", path: "../spree/admin"
gem "spree_stripe", github: "spree/spree_stripe"
gem "spree_i18n"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Audits gems for known security defects (use config/bundler-audit.yml to ignore issues)
  gem "bundler-audit", require: false

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false

  gem "spree_dev_tools"
  gem "letter_opener"
  gem "listen"
  gem "simplecov-cobertura"
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"
end
