require 'spree/core/dependencies_helper'

module Spree
  module Api
    class ApiDependencies
      INJECTION_POINTS_WITH_DEFAULTS = {
        # v3 serializers (API v3)
        credit_card_serializer: 'Spree::Api::V3::CreditCardSerializer',
        price_serializer: 'Spree::Api::V3::PriceSerializer',
        price_history_serializer: 'Spree::Api::V3::PriceHistorySerializer',
        product_serializer: 'Spree::Api::V3::ProductSerializer',
        product_type_serializer: 'Spree::Api::V3::ProductTypeSerializer',
        variant_serializer: 'Spree::Api::V3::VariantSerializer',
        media_serializer: 'Spree::Api::V3::MediaSerializer',
        option_type_serializer: 'Spree::Api::V3::OptionTypeSerializer',
        option_value_serializer: 'Spree::Api::V3::OptionValueSerializer',
        cart_serializer: 'Spree::Api::V3::CartSerializer',
        order_serializer: 'Spree::Api::V3::OrderSerializer',
        order_group_serializer: 'Spree::Api::V3::OrderGroupSerializer',
        line_item_serializer: 'Spree::Api::V3::LineItemSerializer',
        payment_serializer: 'Spree::Api::V3::PaymentSerializer',
        payment_session_serializer: 'Spree::Api::V3::PaymentSessionSerializer',
        payment_setup_session_serializer: 'Spree::Api::V3::PaymentSetupSessionSerializer',
        payment_source_serializer: 'Spree::Api::V3::PaymentSourceSerializer',
        store_credit_serializer: 'Spree::Api::V3::StoreCreditSerializer',
        shipment_serializer: 'Spree::Api::V3::FulfillmentSerializer',
        fulfillment_serializer: 'Spree::Api::V3::FulfillmentSerializer',
        delivery_serializer: 'Spree::Api::V3::DeliverySerializer',
        address_serializer: 'Spree::Api::V3::AddressSerializer',
        customer_serializer: 'Spree::Api::V3::CustomerSerializer',
        customer_group_serializer: 'Spree::Api::V3::CustomerGroupSerializer',
        country_serializer: 'Spree::Api::V3::CountrySerializer',
        channel_serializer: 'Spree::Api::V3::ChannelSerializer',
        product_publication_serializer: 'Spree::Api::V3::ProductPublicationSerializer',
        market_serializer: 'Spree::Api::V3::MarketSerializer',
        state_serializer: 'Spree::Api::V3::StateSerializer',
        wishlist_serializer: 'Spree::Api::V3::WishlistSerializer',
        wishlist_item_serializer: 'Spree::Api::V3::WishlistItemSerializer',
        wished_item_serializer: 'Spree::Api::V3::WishlistItemSerializer',
        payment_method_serializer: 'Spree::Api::V3::PaymentMethodSerializer',
        shipping_method_serializer: 'Spree::Api::V3::DeliveryMethodSerializer',
        shipping_rate_serializer: 'Spree::Api::V3::DeliveryRateSerializer',
        delivery_method_serializer: 'Spree::Api::V3::DeliveryMethodSerializer',
        delivery_rate_serializer: 'Spree::Api::V3::DeliveryRateSerializer',
        stock_location_serializer: 'Spree::Api::V3::StockLocationSerializer',
        category_serializer: 'Spree::Api::V3::CategorySerializer',
        collection_serializer: 'Spree::Api::V3::CollectionSerializer',
        applied_promotion_serializer: 'Spree::Api::V3::AppliedPromotionSerializer',
        discount_serializer: 'Spree::Api::V3::DiscountSerializer',
        tax_line_serializer: 'Spree::Api::V3::TaxLineSerializer',
        delivery_zone_serializer: 'Spree::Api::V3::DeliveryZoneSerializer',
        delivery_zone_member_serializer: 'Spree::Api::V3::DeliveryZoneMemberSerializer',
        fee_serializer: 'Spree::Api::V3::FeeSerializer',
        digital_link_serializer: 'Spree::Api::V3::DigitalLinkSerializer',
        gift_card_serializer: 'Spree::Api::V3::GiftCardSerializer',
        currency_serializer: 'Spree::Api::V3::CurrencySerializer',
        locale_serializer: 'Spree::Api::V3::LocaleSerializer',
        policy_serializer: 'Spree::Api::V3::PolicySerializer',
        custom_field_serializer: 'Spree::Api::V3::CustomFieldSerializer',
        tax_category_serializer: 'Spree::Api::V3::TaxCategorySerializer',
        tax_identifier_serializer: 'Spree::Api::V3::TaxIdentifierSerializer',
        product_filters_serializer: 'Spree::Api::V3::ProductFiltersSerializer',
        product_filter_price_range_serializer: 'Spree::Api::V3::ProductFilterPriceRangeSerializer',
        product_filter_availability_serializer: 'Spree::Api::V3::ProductFilterAvailabilitySerializer',
        product_filter_availability_option_serializer: 'Spree::Api::V3::ProductFilterAvailabilityOptionSerializer',
        product_filter_option_serializer: 'Spree::Api::V3::ProductFilterOptionSerializer',
        product_filter_option_value_serializer: 'Spree::Api::V3::ProductFilterOptionValueSerializer',
        product_filter_category_serializer: 'Spree::Api::V3::ProductFilterCategorySerializer',
        product_filter_category_option_serializer: 'Spree::Api::V3::ProductFilterCategoryOptionSerializer',
        product_filter_sort_option_serializer: 'Spree::Api::V3::ProductFilterSortOptionSerializer',

        # v3 event serializers (for models without Store API endpoints yet)
        media_event_serializer: 'Spree::Api::V3::MediaEventSerializer',
        return_serializer: 'Spree::Api::V3::ReturnSerializer',
        return_line_item_serializer: 'Spree::Api::V3::ReturnLineItemSerializer',
        exchange_serializer: 'Spree::Api::V3::ExchangeSerializer',
        exchange_line_item_serializer: 'Spree::Api::V3::ExchangeLineItemSerializer',
        claim_serializer: 'Spree::Api::V3::ClaimSerializer',
        claim_line_item_serializer: 'Spree::Api::V3::ClaimLineItemSerializer',
        return_reason_serializer: 'Spree::Api::V3::ReturnReasonSerializer',
        claim_reason_serializer: 'Spree::Api::V3::ClaimReasonSerializer',
        digital_asset_serializer: 'Spree::Api::V3::DigitalAssetSerializer',
        export_serializer: 'Spree::Api::V3::ExportSerializer',
        gift_card_batch_serializer: 'Spree::Api::V3::GiftCardBatchSerializer',
        import_serializer: 'Spree::Api::V3::ImportSerializer',
        import_row_serializer: 'Spree::Api::V3::ImportRowSerializer',
        invitation_serializer: 'Spree::Api::V3::InvitationSerializer',
        newsletter_subscriber_serializer: 'Spree::Api::V3::NewsletterSubscriberSerializer',
        promotion_serializer: 'Spree::Api::V3::PromotionSerializer',
        refund_serializer: 'Spree::Api::V3::RefundSerializer',
        report_serializer: 'Spree::Api::V3::ReportSerializer',
        stock_level_serializer: 'Spree::Api::V3::StockLevelSerializer',
        stock_movement_serializer: 'Spree::Api::V3::StockMovementSerializer',
        stock_reservation_serializer: 'Spree::Api::V3::StockReservationSerializer',
        stock_transfer_serializer: 'Spree::Api::V3::StockTransferSerializer',

        # v3 admin serializers (API v3 Admin)
        admin_country_serializer: 'Spree::Api::V3::Admin::CountrySerializer',
        admin_state_serializer: 'Spree::Api::V3::Admin::StateSerializer',
        admin_applied_promotion_serializer: 'Spree::Api::V3::Admin::AppliedPromotionSerializer',
        admin_discount_serializer: 'Spree::Api::V3::Admin::DiscountSerializer',
        admin_tax_line_serializer: 'Spree::Api::V3::Admin::TaxLineSerializer',
        admin_cart_serializer: 'Spree::Api::V3::Admin::CartSerializer',
        admin_delivery_zone_serializer: 'Spree::Api::V3::Admin::DeliveryZoneSerializer',
        admin_delivery_profile_serializer: 'Spree::Api::V3::Admin::DeliveryProfileSerializer',
        admin_delivery_origin_group_serializer: 'Spree::Api::V3::Admin::DeliveryOriginGroupSerializer',
        admin_integration_serializer: 'Spree::Api::V3::Admin::IntegrationSerializer',
        admin_delivery_method_rule_serializer: 'Spree::Api::V3::Admin::DeliveryMethodRuleSerializer',
        admin_delivery_zone_member_serializer: 'Spree::Api::V3::Admin::DeliveryZoneMemberSerializer',
        admin_fee_serializer: 'Spree::Api::V3::Admin::FeeSerializer',
        admin_customer_serializer: 'Spree::Api::V3::Admin::CustomerSerializer',
        admin_newsletter_subscriber_serializer: 'Spree::Api::V3::Admin::NewsletterSubscriberSerializer',
        admin_order_serializer: 'Spree::Api::V3::Admin::OrderSerializer',
        admin_order_group_serializer: 'Spree::Api::V3::Admin::OrderGroupSerializer',
        admin_product_serializer: 'Spree::Api::V3::Admin::ProductSerializer',
        admin_product_type_serializer: 'Spree::Api::V3::Admin::ProductTypeSerializer',
        admin_product_type_custom_field_definition_serializer: 'Spree::Api::V3::Admin::ProductTypeCustomFieldDefinitionSerializer',
        admin_variant_serializer: 'Spree::Api::V3::Admin::VariantSerializer',
        admin_price_serializer: 'Spree::Api::V3::Admin::PriceSerializer',
        admin_price_history_serializer: 'Spree::Api::V3::Admin::PriceHistorySerializer',
        admin_custom_field_serializer: 'Spree::Api::V3::Admin::CustomFieldSerializer',
        admin_custom_field_definition_serializer: 'Spree::Api::V3::Admin::CustomFieldDefinitionSerializer',
        admin_category_serializer: 'Spree::Api::V3::Admin::CategorySerializer',
        admin_collection_serializer: 'Spree::Api::V3::Admin::CollectionSerializer',
        admin_collection_rule_serializer: 'Spree::Api::V3::Admin::CollectionRuleSerializer',
        admin_line_item_serializer: 'Spree::Api::V3::Admin::LineItemSerializer',
        admin_option_type_serializer: 'Spree::Api::V3::Admin::OptionTypeSerializer',
        admin_option_value_serializer: 'Spree::Api::V3::Admin::OptionValueSerializer',
        admin_media_serializer: 'Spree::Api::V3::Admin::MediaSerializer',
        admin_stock_level_serializer: 'Spree::Api::V3::Admin::StockLevelSerializer',
        admin_stock_movement_serializer: 'Spree::Api::V3::Admin::StockMovementSerializer',
        admin_stock_transfer_serializer: 'Spree::Api::V3::Admin::StockTransferSerializer',
        admin_shipment_serializer: 'Spree::Api::V3::Admin::FulfillmentSerializer',
        admin_fulfillment_serializer: 'Spree::Api::V3::Admin::FulfillmentSerializer',
        admin_fulfillment_item_serializer: 'Spree::Api::V3::Admin::FulfillmentItemSerializer',
        admin_delivery_serializer: 'Spree::Api::V3::Admin::DeliverySerializer',
        admin_shipping_label_serializer: 'Spree::Api::V3::Admin::ShippingLabelSerializer',
        admin_gift_card_serializer: 'Spree::Api::V3::Admin::GiftCardSerializer',
        admin_gift_card_batch_serializer: 'Spree::Api::V3::Admin::GiftCardBatchSerializer',
        admin_payment_serializer: 'Spree::Api::V3::Admin::PaymentSerializer',
        admin_refund_serializer: 'Spree::Api::V3::Admin::RefundSerializer',
        admin_return_reason_serializer: 'Spree::Api::V3::Admin::ReturnReasonSerializer',
        admin_claim_reason_serializer: 'Spree::Api::V3::Admin::ClaimReasonSerializer',
        admin_refund_reason_serializer: 'Spree::Api::V3::Admin::RefundReasonSerializer',
        admin_order_cancellation_reason_serializer: 'Spree::Api::V3::Admin::OrderCancellationReasonSerializer',
        admin_return_serializer: 'Spree::Api::V3::Admin::ReturnSerializer',
        admin_return_line_item_serializer: 'Spree::Api::V3::Admin::ReturnLineItemSerializer',
        admin_exchange_serializer: 'Spree::Api::V3::Admin::ExchangeSerializer',
        admin_exchange_line_item_serializer: 'Spree::Api::V3::Admin::ExchangeLineItemSerializer',
        admin_claim_serializer: 'Spree::Api::V3::Admin::ClaimSerializer',
        admin_claim_line_item_serializer: 'Spree::Api::V3::Admin::ClaimLineItemSerializer',
        admin_policy_serializer: 'Spree::Api::V3::Admin::PolicySerializer',
        admin_tax_category_serializer: 'Spree::Api::V3::Admin::TaxCategorySerializer',
        admin_tax_rate_serializer: 'Spree::Api::V3::Admin::TaxRateSerializer',
        admin_tax_identifier_serializer: 'Spree::Api::V3::Admin::TaxIdentifierSerializer',

        company_serializer: 'Spree::Api::V3::CompanySerializer',
        company_membership_serializer: 'Spree::Api::V3::CompanyMembershipSerializer',
        company_invitation_serializer: 'Spree::Api::V3::CompanyInvitationSerializer',
        admin_company_serializer: 'Spree::Api::V3::Admin::CompanySerializer',
        admin_company_membership_serializer: 'Spree::Api::V3::Admin::CompanyMembershipSerializer',
        admin_company_invitation_serializer: 'Spree::Api::V3::Admin::CompanyInvitationSerializer',
        admin_catalog_serializer: 'Spree::Api::V3::Admin::CatalogSerializer',
        admin_catalog_price_serializer: 'Spree::Api::V3::Admin::CatalogPriceSerializer',
        admin_catalog_product_serializer: 'Spree::Api::V3::Admin::CatalogProductSerializer',
        admin_catalog_assignment_serializer: 'Spree::Api::V3::Admin::CatalogAssignmentSerializer',
        admin_catalog_quantity_rule_serializer: 'Spree::Api::V3::Admin::CatalogQuantityRuleSerializer',
        admin_catalog_product_term_serializer: 'Spree::Api::V3::Admin::CatalogProductTermSerializer',
        admin_catalog_order_minimum_serializer: 'Spree::Api::V3::Admin::CatalogOrderMinimumSerializer',
        admin_tax_exemption_certificate_serializer: 'Spree::Api::V3::Admin::TaxExemptionCertificateSerializer',
        admin_admin_user_serializer: 'Spree::Api::V3::Admin::AdminUserSerializer',
        admin_seller_team_member_serializer: 'Spree::Api::V3::Admin::SellerTeamMemberSerializer',
        seller_serializer: 'Spree::Api::V3::SellerSerializer',
        seller_profile_serializer: 'Spree::Api::V3::Seller::ProfileSerializer',
        seller_policy_serializer: 'Spree::Api::V3::Seller::PolicySerializer',
        seller_team_member_serializer: 'Spree::Api::V3::Seller::TeamMemberSerializer',
        seller_invitation_serializer: 'Spree::Api::V3::Seller::InvitationSerializer',
        seller_product_serializer: 'Spree::Api::V3::Seller::ProductSerializer',
        seller_product_type_serializer: 'Spree::Api::V3::Seller::ProductTypeSerializer',
        seller_delivery_profile_serializer: 'Spree::Api::V3::Seller::DeliveryProfileSerializer',
        seller_delivery_method_serializer: 'Spree::Api::V3::Seller::DeliveryMethodSerializer',
        seller_delivery_method_rule_serializer: 'Spree::Api::V3::Seller::DeliveryMethodRuleSerializer',
        seller_delivery_zone_serializer: 'Spree::Api::V3::Seller::DeliveryZoneSerializer',
        seller_variant_serializer: 'Spree::Api::V3::Seller::VariantSerializer',
        seller_media_serializer: 'Spree::Api::V3::Seller::MediaSerializer',
        seller_stock_level_serializer: 'Spree::Api::V3::Seller::StockLevelSerializer',
        seller_order_serializer: 'Spree::Api::V3::Seller::OrderSerializer',
        seller_order_line_item_serializer: 'Spree::Api::V3::Seller::OrderLineItemSerializer',
        seller_fulfillment_serializer: 'Spree::Api::V3::Seller::FulfillmentSerializer',
        seller_fulfillment_item_serializer: 'Spree::Api::V3::Seller::FulfillmentItemSerializer',
        seller_delivery_serializer: 'Spree::Api::V3::Seller::DeliverySerializer',
        seller_shipping_label_serializer: 'Spree::Api::V3::Seller::ShippingLabelSerializer',
        seller_return_serializer: 'Spree::Api::V3::Seller::ReturnSerializer',
        seller_return_line_item_serializer: 'Spree::Api::V3::Seller::ReturnLineItemSerializer',
        seller_exchange_serializer: 'Spree::Api::V3::Seller::ExchangeSerializer',
        seller_exchange_line_item_serializer: 'Spree::Api::V3::Seller::ExchangeLineItemSerializer',
        seller_claim_serializer: 'Spree::Api::V3::Seller::ClaimSerializer',
        seller_claim_line_item_serializer: 'Spree::Api::V3::Seller::ClaimLineItemSerializer',
        seller_reason_serializer: 'Spree::Api::V3::Seller::ReasonSerializer',
        seller_stock_location_serializer: 'Spree::Api::V3::Seller::StockLocationSerializer',
        seller_requirement_custom_field_serializer: 'Spree::Api::V3::Seller::RequirementCustomFieldSerializer',
        seller_tax_identifier_serializer: 'Spree::Api::V3::Seller::TaxIdentifierSerializer',
        seller_requirement_status_serializer: 'Spree::Api::V3::Seller::RequirementStatusSerializer',
        seller_import_serializer: 'Spree::Api::V3::Seller::ImportSerializer',
        seller_import_row_serializer: 'Spree::Api::V3::Seller::ImportRowSerializer',
        seller_import_mapping_serializer: 'Spree::Api::V3::Seller::ImportMappingSerializer',
        product_submission_serializer: 'Spree::Api::V3::Seller::ProductSubmissionSerializer',
        admin_product_submission_serializer: 'Spree::Api::V3::Admin::ProductSubmissionSerializer',
        seller_requirement_submission_serializer: 'Spree::Api::V3::Seller::RequirementSubmissionSerializer',
        seller_export_serializer: 'Spree::Api::V3::Seller::ExportSerializer',
        admin_seller_serializer: 'Spree::Api::V3::Admin::SellerSerializer',
        admin_seller_requirement_serializer: 'Spree::Api::V3::Admin::SellerRequirementSerializer',
        admin_seller_requirement_submission_serializer: 'Spree::Api::V3::Admin::SellerRequirementSubmissionSerializer',
        admin_seller_requirement_status_serializer: 'Spree::Api::V3::Admin::SellerRequirementStatusSerializer',
        admin_commission_rate_serializer: 'Spree::Api::V3::Admin::CommissionRateSerializer',
        admin_commission_rule_serializer: 'Spree::Api::V3::Admin::CommissionRuleSerializer',
        admin_commission_line_serializer: 'Spree::Api::V3::Admin::CommissionLineSerializer',
        admin_seller_transfer_serializer: 'Spree::Api::V3::Admin::SellerTransferSerializer',
        admin_seller_payout_serializer: 'Spree::Api::V3::Admin::SellerPayoutSerializer',
        admin_address_serializer: 'Spree::Api::V3::Admin::AddressSerializer',
        admin_channel_serializer: 'Spree::Api::V3::Admin::ChannelSerializer',
        admin_order_routing_rule_serializer: 'Spree::Api::V3::Admin::OrderRoutingRuleSerializer',
        admin_product_publication_serializer: 'Spree::Api::V3::Admin::ProductPublicationSerializer',
        admin_market_serializer: 'Spree::Api::V3::Admin::MarketSerializer',
        admin_shipping_method_serializer: 'Spree::Api::V3::Admin::DeliveryMethodSerializer',
        admin_delivery_method_serializer: 'Spree::Api::V3::Admin::DeliveryMethodSerializer',
        admin_delivery_method_service_serializer: 'Spree::Api::V3::Admin::DeliveryMethodServiceSerializer',
        admin_stock_location_serializer: 'Spree::Api::V3::Admin::StockLocationSerializer',
        admin_stock_reservation_serializer: 'Spree::Api::V3::Admin::StockReservationSerializer',
        admin_shipping_rate_serializer: 'Spree::Api::V3::Admin::DeliveryRateSerializer',
        admin_delivery_rate_serializer: 'Spree::Api::V3::Admin::DeliveryRateSerializer',
        admin_payment_method_serializer: 'Spree::Api::V3::Admin::PaymentMethodSerializer',
        admin_credit_card_serializer: 'Spree::Api::V3::Admin::CreditCardSerializer',
        admin_store_credit_serializer: 'Spree::Api::V3::Admin::StoreCreditSerializer',
        admin_customer_group_serializer: 'Spree::Api::V3::Admin::CustomerGroupSerializer',
        admin_payment_source_serializer: 'Spree::Api::V3::Admin::PaymentSourceSerializer',
        admin_digital_asset_serializer: 'Spree::Api::V3::Admin::DigitalAssetSerializer',
        admin_digital_link_serializer: 'Spree::Api::V3::Admin::DigitalLinkSerializer',
        admin_store_serializer: 'Spree::Api::V3::Admin::StoreSerializer',
        admin_setup_task_serializer: 'Spree::Api::V3::Admin::SetupTaskSerializer',
        admin_api_key_serializer: 'Spree::Api::V3::Admin::ApiKeySerializer',
        admin_allowed_origin_serializer: 'Spree::Api::V3::Admin::AllowedOriginSerializer',
        admin_webhook_endpoint_serializer: 'Spree::Api::V3::Admin::WebhookEndpointSerializer',
        admin_webhook_delivery_serializer: 'Spree::Api::V3::Admin::WebhookDeliverySerializer',
        admin_invitation_serializer: 'Spree::Api::V3::Admin::InvitationSerializer',
        admin_role_serializer: 'Spree::Api::V3::Admin::RoleSerializer',
        admin_permission_serializer: 'Spree::Api::V3::Admin::PermissionSerializer',
        admin_export_serializer: 'Spree::Api::V3::Admin::ExportSerializer',
        admin_import_serializer: 'Spree::Api::V3::Admin::ImportSerializer',
        admin_import_row_serializer: 'Spree::Api::V3::Admin::ImportRowSerializer',
        admin_import_mapping_serializer: 'Spree::Api::V3::Admin::ImportMappingSerializer',
        admin_promotion_serializer: 'Spree::Api::V3::Admin::PromotionSerializer',
        admin_promotion_action_serializer: 'Spree::Api::V3::Admin::PromotionActionSerializer',
        admin_promotion_rule_serializer: 'Spree::Api::V3::Admin::PromotionRuleSerializer',
        admin_coupon_code_serializer: 'Spree::Api::V3::Admin::CouponCodeSerializer',
        admin_price_list_serializer: 'Spree::Api::V3::Admin::PriceListSerializer',
        admin_price_rule_serializer: 'Spree::Api::V3::Admin::PriceRuleSerializer',
        admin_resource_translations_serializer: 'Spree::Api::V3::Admin::ResourceTranslationsSerializer',
      }

      include Spree::DependenciesHelper

      # Pre-6.0 names for the StockItem → StockLevel serializers. Unlike the
      # legacy workflow keys in core, these forward instead of stashing: a
      # serializer renders the same model under a new class name, so an
      # override written against the old key is still the class the host app
      # wants used. Removed in 6.1.
      LEGACY_SERIALIZER_KEYS = {
        stock_item_serializer: :stock_level_serializer,
        admin_stock_item_serializer: :admin_stock_level_serializer,
        digital_serializer: :digital_asset_serializer,
        admin_digital_serializer: :admin_digital_asset_serializer
      }.freeze

      LEGACY_SERIALIZER_KEYS.each do |legacy, current|
        define_method("#{legacy}=") do |value|
          Spree::Deprecation.warn("Spree.api.#{legacy}= is deprecated and will be removed in Spree 6.1. Use #{current}= instead.")
          send("#{current}=", value)
        end

        define_method(legacy) do
          Spree::Deprecation.warn("Spree.api.#{legacy} is deprecated and will be removed in Spree 6.1. Use #{current} instead.")
          send(current)
        end

        define_method("#{legacy}_class") do
          Spree::Deprecation.warn("Spree.api.#{legacy}_class is deprecated and will be removed in Spree 6.1. Use #{current}_class instead.")
          send("#{current}_class")
        end
      end
    end
  end
end
