require 'spree/core/dependencies_helper'

module Spree
  module Api
    class ApiDependencies
      INJECTION_POINTS_WITH_DEFAULTS = {
        # v3 serializers (API v3)
        credit_card_serializer: 'Spree::Api::V3::CreditCardSerializer',
        price_serializer: 'Spree::Api::V3::PriceSerializer',
        price_history_serializer: 'Spree::Api::V3::PriceHistorySerializer',
        product_serializer: 'Spree::Api::V3::ProductSerializer',
        variant_serializer: 'Spree::Api::V3::VariantSerializer',
        media_serializer: 'Spree::Api::V3::MediaSerializer',
        option_type_serializer: 'Spree::Api::V3::OptionTypeSerializer',
        option_value_serializer: 'Spree::Api::V3::OptionValueSerializer',
        cart_serializer: 'Spree::Api::V3::CartSerializer',
        order_serializer: 'Spree::Api::V3::OrderSerializer',
        line_item_serializer: 'Spree::Api::V3::LineItemSerializer',
        payment_serializer: 'Spree::Api::V3::PaymentSerializer',
        payment_session_serializer: 'Spree::Api::V3::PaymentSessionSerializer',
        payment_setup_session_serializer: 'Spree::Api::V3::PaymentSetupSessionSerializer',
        payment_source_serializer: 'Spree::Api::V3::PaymentSourceSerializer',
        store_credit_serializer: 'Spree::Api::V3::StoreCreditSerializer',
        shipment_serializer: 'Spree::Api::V3::FulfillmentSerializer',
        fulfillment_serializer: 'Spree::Api::V3::FulfillmentSerializer',
        address_serializer: 'Spree::Api::V3::AddressSerializer',
        customer_serializer: 'Spree::Api::V3::CustomerSerializer',
        country_serializer: 'Spree::Api::V3::CountrySerializer',
        market_serializer: 'Spree::Api::V3::MarketSerializer',
        state_serializer: 'Spree::Api::V3::StateSerializer',
        wishlist_serializer: 'Spree::Api::V3::WishlistSerializer',
        wishlist_item_serializer: 'Spree::Api::V3::WishlistItemSerializer',
        wished_item_serializer: 'Spree::Api::V3::WishlistItemSerializer',
        payment_method_serializer: 'Spree::Api::V3::PaymentMethodSerializer',
        shipping_method_serializer: 'Spree::Api::V3::DeliveryMethodSerializer',
        shipping_rate_serializer: 'Spree::Api::V3::DeliveryRateSerializer',
        delivery_method_serializer: 'Spree::Api::V3::DeliveryMethodSerializer',
        delivery_rate_serializer: 'Spree::Api::V3::DeliveryRateSerializer',
        stock_location_serializer: 'Spree::Api::V3::StockLocationSerializer',
        category_serializer: 'Spree::Api::V3::CategorySerializer',
        discount_serializer: 'Spree::Api::V3::DiscountSerializer',
        digital_link_serializer: 'Spree::Api::V3::DigitalLinkSerializer',
        gift_card_serializer: 'Spree::Api::V3::GiftCardSerializer',
        currency_serializer: 'Spree::Api::V3::CurrencySerializer',
        locale_serializer: 'Spree::Api::V3::LocaleSerializer',
        policy_serializer: 'Spree::Api::V3::PolicySerializer',
        custom_field_serializer: 'Spree::Api::V3::CustomFieldSerializer',
        shipping_category_serializer: 'Spree::Api::V3::ShippingCategorySerializer',
        tax_category_serializer: 'Spree::Api::V3::TaxCategorySerializer',

        # v3 event serializers (for models without Store API endpoints yet)
        asset_serializer: 'Spree::Api::V3::AssetSerializer',
        customer_return_serializer: 'Spree::Api::V3::CustomerReturnSerializer',
        digital_serializer: 'Spree::Api::V3::DigitalSerializer',
        export_serializer: 'Spree::Api::V3::ExportSerializer',
        gift_card_batch_serializer: 'Spree::Api::V3::GiftCardBatchSerializer',
        import_serializer: 'Spree::Api::V3::ImportSerializer',
        import_row_serializer: 'Spree::Api::V3::ImportRowSerializer',
        invitation_serializer: 'Spree::Api::V3::InvitationSerializer',
        newsletter_subscriber_serializer: 'Spree::Api::V3::NewsletterSubscriberSerializer',
        promotion_serializer: 'Spree::Api::V3::PromotionSerializer',
        refund_serializer: 'Spree::Api::V3::RefundSerializer',
        reimbursement_serializer: 'Spree::Api::V3::ReimbursementSerializer',
        report_serializer: 'Spree::Api::V3::ReportSerializer',
        return_authorization_serializer: 'Spree::Api::V3::ReturnAuthorizationSerializer',
        return_item_serializer: 'Spree::Api::V3::ReturnItemSerializer',
        stock_item_serializer: 'Spree::Api::V3::StockItemSerializer',
        stock_movement_serializer: 'Spree::Api::V3::StockMovementSerializer',
        stock_transfer_serializer: 'Spree::Api::V3::StockTransferSerializer',

        # v3 admin serializers (API v3 Admin)
        admin_country_serializer: 'Spree::Api::V3::Admin::CountrySerializer',
        admin_state_serializer: 'Spree::Api::V3::Admin::StateSerializer',
        admin_discount_serializer: 'Spree::Api::V3::Admin::DiscountSerializer',
        admin_customer_serializer: 'Spree::Api::V3::Admin::CustomerSerializer',
        admin_order_serializer: 'Spree::Api::V3::Admin::OrderSerializer',
        admin_product_serializer: 'Spree::Api::V3::Admin::ProductSerializer',
        admin_variant_serializer: 'Spree::Api::V3::Admin::VariantSerializer',
        admin_price_serializer: 'Spree::Api::V3::Admin::PriceSerializer',
        admin_price_history_serializer: 'Spree::Api::V3::Admin::PriceHistorySerializer',
        admin_custom_field_serializer: 'Spree::Api::V3::Admin::CustomFieldSerializer',
        admin_category_serializer: 'Spree::Api::V3::Admin::CategorySerializer',
        admin_line_item_serializer: 'Spree::Api::V3::Admin::LineItemSerializer',
        admin_option_type_serializer: 'Spree::Api::V3::Admin::OptionTypeSerializer',
        admin_option_value_serializer: 'Spree::Api::V3::Admin::OptionValueSerializer',
        admin_media_serializer: 'Spree::Api::V3::Admin::MediaSerializer',
        admin_asset_serializer: 'Spree::Api::V3::Admin::AssetSerializer',
        admin_stock_item_serializer: 'Spree::Api::V3::Admin::StockItemSerializer',
        admin_shipment_serializer: 'Spree::Api::V3::Admin::FulfillmentSerializer',
        admin_fulfillment_serializer: 'Spree::Api::V3::Admin::FulfillmentSerializer',
        admin_gift_card_serializer: 'Spree::Api::V3::Admin::GiftCardSerializer',
        admin_payment_serializer: 'Spree::Api::V3::Admin::PaymentSerializer',
        admin_refund_serializer: 'Spree::Api::V3::Admin::RefundSerializer',
        admin_adjustment_serializer: 'Spree::Api::V3::Admin::AdjustmentSerializer',
        admin_shipping_category_serializer: 'Spree::Api::V3::Admin::ShippingCategorySerializer',
        admin_tax_category_serializer: 'Spree::Api::V3::Admin::TaxCategorySerializer',
        admin_return_authorization_serializer: 'Spree::Api::V3::Admin::ReturnAuthorizationSerializer',
        admin_reimbursement_serializer: 'Spree::Api::V3::Admin::ReimbursementSerializer',
        admin_admin_user_serializer: 'Spree::Api::V3::Admin::AdminUserSerializer',
        admin_address_serializer: 'Spree::Api::V3::Admin::AddressSerializer',
        admin_market_serializer: 'Spree::Api::V3::Admin::MarketSerializer',
        admin_shipping_method_serializer: 'Spree::Api::V3::Admin::DeliveryMethodSerializer',
        admin_delivery_method_serializer: 'Spree::Api::V3::Admin::DeliveryMethodSerializer',
        admin_stock_location_serializer: 'Spree::Api::V3::Admin::StockLocationSerializer',
        admin_shipping_rate_serializer: 'Spree::Api::V3::Admin::DeliveryRateSerializer',
        admin_delivery_rate_serializer: 'Spree::Api::V3::Admin::DeliveryRateSerializer',
        admin_payment_method_serializer: 'Spree::Api::V3::Admin::PaymentMethodSerializer',
        admin_credit_card_serializer: 'Spree::Api::V3::Admin::CreditCardSerializer',
        admin_store_credit_serializer: 'Spree::Api::V3::Admin::StoreCreditSerializer',
        admin_payment_source_serializer: 'Spree::Api::V3::Admin::PaymentSourceSerializer',
        admin_digital_link_serializer: 'Spree::Api::V3::Admin::DigitalLinkSerializer',
      }

      include Spree::DependenciesHelper
    end
  end
end
