/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../dashboard/src/routes/__root'
import { Route as loginRouteImport } from './../../dashboard/src/routes/login'
import { Route as authenticatedRouteImport } from './../../dashboard/src/routes/_authenticated'
import { Route as authenticatedIndexRouteImport } from './../../dashboard/src/routes/_authenticated/index'
import { Route as acceptInvitationDotinvitationIdRouteImport } from './../../dashboard/src/routes/accept-invitation.$invitationId'
import { Route as authenticatedStoreIdRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId'
import { Route as IndexRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/index'
import { Route as SettingsRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/settings'
import { Route as SplatRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/$'
import { Route as SettingsIndexRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/settings/index'
import { Route as PromotionsIndexRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/promotions/index'
import { Route as ProductsIndexRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/products/index'
import { Route as OrdersIndexRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/orders/index'
import { Route as CustomersIndexRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/customers/index'
import { Route as BrandsDotindexRouteImport } from './../../dashboard-plugin-example/src/routes/brands.index'
import { Route as SettingsTaxCategoriesRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/settings/tax-categories'
import { Route as SettingsStoreRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/settings/store'
import { Route as SettingsStockLocationsRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/settings/stock-locations'
import { Route as SettingsStaffRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/settings/staff'
import { Route as SettingsProfileRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/settings/profile'
import { Route as SettingsPaymentMethodsRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/settings/payment-methods'
import { Route as SettingsMarketsRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/settings/markets'
import { Route as SettingsEmailsRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/settings/emails'
import { Route as SettingsCustomFieldDefinitionsRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/settings/custom-field-definitions'
import { Route as SettingsChannelsRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/settings/channels'
import { Route as SettingsApiKeysRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/settings/api-keys'
import { Route as SettingsAllowedOriginsRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/settings/allowed-origins'
import { Route as PromotionsNewRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/promotions/new'
import { Route as PromotionsGiftCardsRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/promotions/gift-cards'
import { Route as PromotionsPromotionIdRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/promotions/$promotionId'
import { Route as ProductsTransfersRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/products/transfers'
import { Route as ProductsOptionsRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/products/options'
import { Route as ProductsNewRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/products/new'
import { Route as ProductsProductIdRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/products/$productId'
import { Route as OrdersNewRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/orders/new'
import { Route as OrdersDraftsRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/orders/drafts'
import { Route as OrdersOrderIdRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/orders/$orderId'
import { Route as CustomersGroupsRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/customers/groups'
import { Route as CustomersCustomerIdRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/customers/$customerId'
import { Route as BrandsDotbrandIdRouteImport } from './../../dashboard-plugin-example/src/routes/brands.$brandId'
import { Route as SettingsWebhooksIndexRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/settings/webhooks/index'
import { Route as ProductsPriceListsIndexRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/products/price-lists/index'
import { Route as ProductsCategoriesIndexRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/products/categories/index'
import { Route as SettingsWebhooksWebhookEndpointIdRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/settings/webhooks/$webhookEndpointId'
import { Route as ProductsPriceListsNewRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/products/price-lists/new'
import { Route as ProductsCategoriesNewRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/products/categories/new'
import { Route as ProductsCategoriesCategoryIdRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/products/categories/$categoryId'
import { Route as ProductsPriceListsPriceListIdIndexRouteImport } from './../../dashboard/src/routes/_authenticated/$storeId/products/price-lists/$priceListId/index'

const loginRoute = loginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRoute = authenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedRoute,
} as any)
const acceptInvitationDotinvitationIdRoute =
  acceptInvitationDotinvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticatedStoreIdRoute = authenticatedStoreIdRouteImport.update({
  id: '/$storeId',
  path: '/$storeId',
  getParentRoute: () => authenticatedRoute,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const PromotionsIndexRoute = PromotionsIndexRouteImport.update({
  id: '/promotions/',
  path: '/promotions/',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const BrandsDotindexRoute = BrandsDotindexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const SettingsTaxCategoriesRoute = SettingsTaxCategoriesRouteImport.update({
  id: '/tax-categories',
  path: '/tax-categories',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsStoreRoute = SettingsStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsStockLocationsRoute = SettingsStockLocationsRouteImport.update({
  id: '/stock-locations',
  path: '/stock-locations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsStaffRoute = SettingsStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPaymentMethodsRoute = SettingsPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMarketsRoute = SettingsMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEmailsRoute = SettingsEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCustomFieldDefinitionsRoute =
  SettingsCustomFieldDefinitionsRouteImport.update({
    id: '/custom-field-definitions',
    path: '/custom-field-definitions',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsChannelsRoute = SettingsChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAllowedOriginsRoute = SettingsAllowedOriginsRouteImport.update({
  id: '/allowed-origins',
  path: '/allowed-origins',
  getParentRoute: () => SettingsRoute,
} as any)
const PromotionsNewRoute = PromotionsNewRouteImport.update({
  id: '/promotions/new',
  path: '/promotions/new',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const PromotionsGiftCardsRoute = PromotionsGiftCardsRouteImport.update({
  id: '/promotions/gift-cards',
  path: '/promotions/gift-cards',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const PromotionsPromotionIdRoute = PromotionsPromotionIdRouteImport.update({
  id: '/promotions/$promotionId',
  path: '/promotions/$promotionId',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const ProductsTransfersRoute = ProductsTransfersRouteImport.update({
  id: '/products/transfers',
  path: '/products/transfers',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const ProductsOptionsRoute = ProductsOptionsRouteImport.update({
  id: '/products/options',
  path: '/products/options',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const OrdersDraftsRoute = OrdersDraftsRouteImport.update({
  id: '/orders/drafts',
  path: '/orders/drafts',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const CustomersGroupsRoute = CustomersGroupsRouteImport.update({
  id: '/customers/groups',
  path: '/customers/groups',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const BrandsDotbrandIdRoute = BrandsDotbrandIdRouteImport.update({
  id: '/brands/$brandId',
  path: '/brands/$brandId',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const SettingsWebhooksIndexRoute = SettingsWebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => SettingsRoute,
} as any)
const ProductsPriceListsIndexRoute = ProductsPriceListsIndexRouteImport.update({
  id: '/products/price-lists/',
  path: '/products/price-lists/',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const ProductsCategoriesIndexRoute = ProductsCategoriesIndexRouteImport.update({
  id: '/products/categories/',
  path: '/products/categories/',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const SettingsWebhooksWebhookEndpointIdRoute =
  SettingsWebhooksWebhookEndpointIdRouteImport.update({
    id: '/webhooks/$webhookEndpointId',
    path: '/webhooks/$webhookEndpointId',
    getParentRoute: () => SettingsRoute,
  } as any)
const ProductsPriceListsNewRoute = ProductsPriceListsNewRouteImport.update({
  id: '/products/price-lists/new',
  path: '/products/price-lists/new',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const ProductsCategoriesNewRoute = ProductsCategoriesNewRouteImport.update({
  id: '/products/categories/new',
  path: '/products/categories/new',
  getParentRoute: () => authenticatedStoreIdRoute,
} as any)
const ProductsCategoriesCategoryIdRoute =
  ProductsCategoriesCategoryIdRouteImport.update({
    id: '/products/categories/$categoryId',
    path: '/products/categories/$categoryId',
    getParentRoute: () => authenticatedStoreIdRoute,
  } as any)
const ProductsPriceListsPriceListIdIndexRoute =
  ProductsPriceListsPriceListIdIndexRouteImport.update({
    id: '/products/price-lists/$priceListId/',
    path: '/products/price-lists/$priceListId/',
    getParentRoute: () => authenticatedStoreIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authenticatedIndexRoute
  '/login': typeof loginRoute
  '/$storeId': typeof authenticatedStoreIdRouteWithChildren
  '/accept-invitation/$invitationId': typeof acceptInvitationDotinvitationIdRoute
  '/$storeId/$': typeof SplatRoute
  '/$storeId/settings': typeof SettingsRouteWithChildren
  '/$storeId/': typeof IndexRoute
  '/$storeId/brands/$brandId': typeof BrandsDotbrandIdRoute
  '/$storeId/customers/$customerId': typeof CustomersCustomerIdRoute
  '/$storeId/customers/groups': typeof CustomersGroupsRoute
  '/$storeId/orders/$orderId': typeof OrdersOrderIdRoute
  '/$storeId/orders/drafts': typeof OrdersDraftsRoute
  '/$storeId/orders/new': typeof OrdersNewRoute
  '/$storeId/products/$productId': typeof ProductsProductIdRoute
  '/$storeId/products/new': typeof ProductsNewRoute
  '/$storeId/products/options': typeof ProductsOptionsRoute
  '/$storeId/products/transfers': typeof ProductsTransfersRoute
  '/$storeId/promotions/$promotionId': typeof PromotionsPromotionIdRoute
  '/$storeId/promotions/gift-cards': typeof PromotionsGiftCardsRoute
  '/$storeId/promotions/new': typeof PromotionsNewRoute
  '/$storeId/settings/allowed-origins': typeof SettingsAllowedOriginsRoute
  '/$storeId/settings/api-keys': typeof SettingsApiKeysRoute
  '/$storeId/settings/channels': typeof SettingsChannelsRoute
  '/$storeId/settings/custom-field-definitions': typeof SettingsCustomFieldDefinitionsRoute
  '/$storeId/settings/emails': typeof SettingsEmailsRoute
  '/$storeId/settings/markets': typeof SettingsMarketsRoute
  '/$storeId/settings/payment-methods': typeof SettingsPaymentMethodsRoute
  '/$storeId/settings/profile': typeof SettingsProfileRoute
  '/$storeId/settings/staff': typeof SettingsStaffRoute
  '/$storeId/settings/stock-locations': typeof SettingsStockLocationsRoute
  '/$storeId/settings/store': typeof SettingsStoreRoute
  '/$storeId/settings/tax-categories': typeof SettingsTaxCategoriesRoute
  '/$storeId/brands/': typeof BrandsDotindexRoute
  '/$storeId/customers/': typeof CustomersIndexRoute
  '/$storeId/orders/': typeof OrdersIndexRoute
  '/$storeId/products/': typeof ProductsIndexRoute
  '/$storeId/promotions/': typeof PromotionsIndexRoute
  '/$storeId/settings/': typeof SettingsIndexRoute
  '/$storeId/products/categories/$categoryId': typeof ProductsCategoriesCategoryIdRoute
  '/$storeId/products/categories/new': typeof ProductsCategoriesNewRoute
  '/$storeId/products/price-lists/new': typeof ProductsPriceListsNewRoute
  '/$storeId/settings/webhooks/$webhookEndpointId': typeof SettingsWebhooksWebhookEndpointIdRoute
  '/$storeId/products/categories/': typeof ProductsCategoriesIndexRoute
  '/$storeId/products/price-lists/': typeof ProductsPriceListsIndexRoute
  '/$storeId/settings/webhooks/': typeof SettingsWebhooksIndexRoute
  '/$storeId/products/price-lists/$priceListId/': typeof ProductsPriceListsPriceListIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof loginRoute
  '/accept-invitation/$invitationId': typeof acceptInvitationDotinvitationIdRoute
  '/': typeof authenticatedIndexRoute
  '/$storeId/$': typeof SplatRoute
  '/$storeId': typeof IndexRoute
  '/$storeId/brands/$brandId': typeof BrandsDotbrandIdRoute
  '/$storeId/customers/$customerId': typeof CustomersCustomerIdRoute
  '/$storeId/customers/groups': typeof CustomersGroupsRoute
  '/$storeId/orders/$orderId': typeof OrdersOrderIdRoute
  '/$storeId/orders/drafts': typeof OrdersDraftsRoute
  '/$storeId/orders/new': typeof OrdersNewRoute
  '/$storeId/products/$productId': typeof ProductsProductIdRoute
  '/$storeId/products/new': typeof ProductsNewRoute
  '/$storeId/products/options': typeof ProductsOptionsRoute
  '/$storeId/products/transfers': typeof ProductsTransfersRoute
  '/$storeId/promotions/$promotionId': typeof PromotionsPromotionIdRoute
  '/$storeId/promotions/gift-cards': typeof PromotionsGiftCardsRoute
  '/$storeId/promotions/new': typeof PromotionsNewRoute
  '/$storeId/settings/allowed-origins': typeof SettingsAllowedOriginsRoute
  '/$storeId/settings/api-keys': typeof SettingsApiKeysRoute
  '/$storeId/settings/channels': typeof SettingsChannelsRoute
  '/$storeId/settings/custom-field-definitions': typeof SettingsCustomFieldDefinitionsRoute
  '/$storeId/settings/emails': typeof SettingsEmailsRoute
  '/$storeId/settings/markets': typeof SettingsMarketsRoute
  '/$storeId/settings/payment-methods': typeof SettingsPaymentMethodsRoute
  '/$storeId/settings/profile': typeof SettingsProfileRoute
  '/$storeId/settings/staff': typeof SettingsStaffRoute
  '/$storeId/settings/stock-locations': typeof SettingsStockLocationsRoute
  '/$storeId/settings/store': typeof SettingsStoreRoute
  '/$storeId/settings/tax-categories': typeof SettingsTaxCategoriesRoute
  '/$storeId/brands': typeof BrandsDotindexRoute
  '/$storeId/customers': typeof CustomersIndexRoute
  '/$storeId/orders': typeof OrdersIndexRoute
  '/$storeId/products': typeof ProductsIndexRoute
  '/$storeId/promotions': typeof PromotionsIndexRoute
  '/$storeId/settings': typeof SettingsIndexRoute
  '/$storeId/products/categories/$categoryId': typeof ProductsCategoriesCategoryIdRoute
  '/$storeId/products/categories/new': typeof ProductsCategoriesNewRoute
  '/$storeId/products/price-lists/new': typeof ProductsPriceListsNewRoute
  '/$storeId/settings/webhooks/$webhookEndpointId': typeof SettingsWebhooksWebhookEndpointIdRoute
  '/$storeId/products/categories': typeof ProductsCategoriesIndexRoute
  '/$storeId/products/price-lists': typeof ProductsPriceListsIndexRoute
  '/$storeId/settings/webhooks': typeof SettingsWebhooksIndexRoute
  '/$storeId/products/price-lists/$priceListId': typeof ProductsPriceListsPriceListIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof authenticatedRouteWithChildren
  '/login': typeof loginRoute
  '/_authenticated/$storeId': typeof authenticatedStoreIdRouteWithChildren
  '/accept-invitation/$invitationId': typeof acceptInvitationDotinvitationIdRoute
  '/_authenticated/': typeof authenticatedIndexRoute
  '/_authenticated/$storeId/$': typeof SplatRoute
  '/_authenticated/$storeId/settings': typeof SettingsRouteWithChildren
  '/_authenticated/$storeId/': typeof IndexRoute
  '/_authenticated/$storeId/brands/$brandId': typeof BrandsDotbrandIdRoute
  '/_authenticated/$storeId/customers/$customerId': typeof CustomersCustomerIdRoute
  '/_authenticated/$storeId/customers/groups': typeof CustomersGroupsRoute
  '/_authenticated/$storeId/orders/$orderId': typeof OrdersOrderIdRoute
  '/_authenticated/$storeId/orders/drafts': typeof OrdersDraftsRoute
  '/_authenticated/$storeId/orders/new': typeof OrdersNewRoute
  '/_authenticated/$storeId/products/$productId': typeof ProductsProductIdRoute
  '/_authenticated/$storeId/products/new': typeof ProductsNewRoute
  '/_authenticated/$storeId/products/options': typeof ProductsOptionsRoute
  '/_authenticated/$storeId/products/transfers': typeof ProductsTransfersRoute
  '/_authenticated/$storeId/promotions/$promotionId': typeof PromotionsPromotionIdRoute
  '/_authenticated/$storeId/promotions/gift-cards': typeof PromotionsGiftCardsRoute
  '/_authenticated/$storeId/promotions/new': typeof PromotionsNewRoute
  '/_authenticated/$storeId/settings/allowed-origins': typeof SettingsAllowedOriginsRoute
  '/_authenticated/$storeId/settings/api-keys': typeof SettingsApiKeysRoute
  '/_authenticated/$storeId/settings/channels': typeof SettingsChannelsRoute
  '/_authenticated/$storeId/settings/custom-field-definitions': typeof SettingsCustomFieldDefinitionsRoute
  '/_authenticated/$storeId/settings/emails': typeof SettingsEmailsRoute
  '/_authenticated/$storeId/settings/markets': typeof SettingsMarketsRoute
  '/_authenticated/$storeId/settings/payment-methods': typeof SettingsPaymentMethodsRoute
  '/_authenticated/$storeId/settings/profile': typeof SettingsProfileRoute
  '/_authenticated/$storeId/settings/staff': typeof SettingsStaffRoute
  '/_authenticated/$storeId/settings/stock-locations': typeof SettingsStockLocationsRoute
  '/_authenticated/$storeId/settings/store': typeof SettingsStoreRoute
  '/_authenticated/$storeId/settings/tax-categories': typeof SettingsTaxCategoriesRoute
  '/_authenticated/$storeId/brands/': typeof BrandsDotindexRoute
  '/_authenticated/$storeId/customers/': typeof CustomersIndexRoute
  '/_authenticated/$storeId/orders/': typeof OrdersIndexRoute
  '/_authenticated/$storeId/products/': typeof ProductsIndexRoute
  '/_authenticated/$storeId/promotions/': typeof PromotionsIndexRoute
  '/_authenticated/$storeId/settings/': typeof SettingsIndexRoute
  '/_authenticated/$storeId/products/categories/$categoryId': typeof ProductsCategoriesCategoryIdRoute
  '/_authenticated/$storeId/products/categories/new': typeof ProductsCategoriesNewRoute
  '/_authenticated/$storeId/products/price-lists/new': typeof ProductsPriceListsNewRoute
  '/_authenticated/$storeId/settings/webhooks/$webhookEndpointId': typeof SettingsWebhooksWebhookEndpointIdRoute
  '/_authenticated/$storeId/products/categories/': typeof ProductsCategoriesIndexRoute
  '/_authenticated/$storeId/products/price-lists/': typeof ProductsPriceListsIndexRoute
  '/_authenticated/$storeId/settings/webhooks/': typeof SettingsWebhooksIndexRoute
  '/_authenticated/$storeId/products/price-lists/$priceListId/': typeof ProductsPriceListsPriceListIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$storeId'
    | '/accept-invitation/$invitationId'
    | '/$storeId/$'
    | '/$storeId/settings'
    | '/$storeId/'
    | '/$storeId/brands/$brandId'
    | '/$storeId/customers/$customerId'
    | '/$storeId/customers/groups'
    | '/$storeId/orders/$orderId'
    | '/$storeId/orders/drafts'
    | '/$storeId/orders/new'
    | '/$storeId/products/$productId'
    | '/$storeId/products/new'
    | '/$storeId/products/options'
    | '/$storeId/products/transfers'
    | '/$storeId/promotions/$promotionId'
    | '/$storeId/promotions/gift-cards'
    | '/$storeId/promotions/new'
    | '/$storeId/settings/allowed-origins'
    | '/$storeId/settings/api-keys'
    | '/$storeId/settings/channels'
    | '/$storeId/settings/custom-field-definitions'
    | '/$storeId/settings/emails'
    | '/$storeId/settings/markets'
    | '/$storeId/settings/payment-methods'
    | '/$storeId/settings/profile'
    | '/$storeId/settings/staff'
    | '/$storeId/settings/stock-locations'
    | '/$storeId/settings/store'
    | '/$storeId/settings/tax-categories'
    | '/$storeId/brands/'
    | '/$storeId/customers/'
    | '/$storeId/orders/'
    | '/$storeId/products/'
    | '/$storeId/promotions/'
    | '/$storeId/settings/'
    | '/$storeId/products/categories/$categoryId'
    | '/$storeId/products/categories/new'
    | '/$storeId/products/price-lists/new'
    | '/$storeId/settings/webhooks/$webhookEndpointId'
    | '/$storeId/products/categories/'
    | '/$storeId/products/price-lists/'
    | '/$storeId/settings/webhooks/'
    | '/$storeId/products/price-lists/$priceListId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/accept-invitation/$invitationId'
    | '/'
    | '/$storeId/$'
    | '/$storeId'
    | '/$storeId/brands/$brandId'
    | '/$storeId/customers/$customerId'
    | '/$storeId/customers/groups'
    | '/$storeId/orders/$orderId'
    | '/$storeId/orders/drafts'
    | '/$storeId/orders/new'
    | '/$storeId/products/$productId'
    | '/$storeId/products/new'
    | '/$storeId/products/options'
    | '/$storeId/products/transfers'
    | '/$storeId/promotions/$promotionId'
    | '/$storeId/promotions/gift-cards'
    | '/$storeId/promotions/new'
    | '/$storeId/settings/allowed-origins'
    | '/$storeId/settings/api-keys'
    | '/$storeId/settings/channels'
    | '/$storeId/settings/custom-field-definitions'
    | '/$storeId/settings/emails'
    | '/$storeId/settings/markets'
    | '/$storeId/settings/payment-methods'
    | '/$storeId/settings/profile'
    | '/$storeId/settings/staff'
    | '/$storeId/settings/stock-locations'
    | '/$storeId/settings/store'
    | '/$storeId/settings/tax-categories'
    | '/$storeId/brands'
    | '/$storeId/customers'
    | '/$storeId/orders'
    | '/$storeId/products'
    | '/$storeId/promotions'
    | '/$storeId/settings'
    | '/$storeId/products/categories/$categoryId'
    | '/$storeId/products/categories/new'
    | '/$storeId/products/price-lists/new'
    | '/$storeId/settings/webhooks/$webhookEndpointId'
    | '/$storeId/products/categories'
    | '/$storeId/products/price-lists'
    | '/$storeId/settings/webhooks'
    | '/$storeId/products/price-lists/$priceListId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/$storeId'
    | '/accept-invitation/$invitationId'
    | '/_authenticated/'
    | '/_authenticated/$storeId/$'
    | '/_authenticated/$storeId/settings'
    | '/_authenticated/$storeId/'
    | '/_authenticated/$storeId/brands/$brandId'
    | '/_authenticated/$storeId/customers/$customerId'
    | '/_authenticated/$storeId/customers/groups'
    | '/_authenticated/$storeId/orders/$orderId'
    | '/_authenticated/$storeId/orders/drafts'
    | '/_authenticated/$storeId/orders/new'
    | '/_authenticated/$storeId/products/$productId'
    | '/_authenticated/$storeId/products/new'
    | '/_authenticated/$storeId/products/options'
    | '/_authenticated/$storeId/products/transfers'
    | '/_authenticated/$storeId/promotions/$promotionId'
    | '/_authenticated/$storeId/promotions/gift-cards'
    | '/_authenticated/$storeId/promotions/new'
    | '/_authenticated/$storeId/settings/allowed-origins'
    | '/_authenticated/$storeId/settings/api-keys'
    | '/_authenticated/$storeId/settings/channels'
    | '/_authenticated/$storeId/settings/custom-field-definitions'
    | '/_authenticated/$storeId/settings/emails'
    | '/_authenticated/$storeId/settings/markets'
    | '/_authenticated/$storeId/settings/payment-methods'
    | '/_authenticated/$storeId/settings/profile'
    | '/_authenticated/$storeId/settings/staff'
    | '/_authenticated/$storeId/settings/stock-locations'
    | '/_authenticated/$storeId/settings/store'
    | '/_authenticated/$storeId/settings/tax-categories'
    | '/_authenticated/$storeId/brands/'
    | '/_authenticated/$storeId/customers/'
    | '/_authenticated/$storeId/orders/'
    | '/_authenticated/$storeId/products/'
    | '/_authenticated/$storeId/promotions/'
    | '/_authenticated/$storeId/settings/'
    | '/_authenticated/$storeId/products/categories/$categoryId'
    | '/_authenticated/$storeId/products/categories/new'
    | '/_authenticated/$storeId/products/price-lists/new'
    | '/_authenticated/$storeId/settings/webhooks/$webhookEndpointId'
    | '/_authenticated/$storeId/products/categories/'
    | '/_authenticated/$storeId/products/price-lists/'
    | '/_authenticated/$storeId/settings/webhooks/'
    | '/_authenticated/$storeId/products/price-lists/$priceListId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRoute: typeof authenticatedRouteWithChildren
  loginRoute: typeof loginRoute
  acceptInvitationDotinvitationIdRoute: typeof acceptInvitationDotinvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof authenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof authenticatedRoute
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof acceptInvitationDotinvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$storeId': {
      id: '/_authenticated/$storeId'
      path: '/$storeId'
      fullPath: '/$storeId'
      preLoaderRoute: typeof authenticatedStoreIdRouteImport
      parentRoute: typeof authenticatedRoute
    }
    '/_authenticated/$storeId/': {
      id: '/_authenticated/$storeId/'
      path: '/'
      fullPath: '/$storeId/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/settings': {
      id: '/_authenticated/$storeId/settings'
      path: '/settings'
      fullPath: '/$storeId/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/$': {
      id: '/_authenticated/$storeId/$'
      path: '/$'
      fullPath: '/$storeId/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/settings/': {
      id: '/_authenticated/$storeId/settings/'
      path: '/'
      fullPath: '/$storeId/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/$storeId/promotions/': {
      id: '/_authenticated/$storeId/promotions/'
      path: '/promotions'
      fullPath: '/$storeId/promotions/'
      preLoaderRoute: typeof PromotionsIndexRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/': {
      id: '/_authenticated/$storeId/products/'
      path: '/products'
      fullPath: '/$storeId/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/orders/': {
      id: '/_authenticated/$storeId/orders/'
      path: '/orders'
      fullPath: '/$storeId/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/customers/': {
      id: '/_authenticated/$storeId/customers/'
      path: '/customers'
      fullPath: '/$storeId/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/brands/': {
      id: '/_authenticated/$storeId/brands/'
      path: '/brands'
      fullPath: '/$storeId/brands/'
      preLoaderRoute: typeof BrandsDotindexRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/settings/tax-categories': {
      id: '/_authenticated/$storeId/settings/tax-categories'
      path: '/tax-categories'
      fullPath: '/$storeId/settings/tax-categories'
      preLoaderRoute: typeof SettingsTaxCategoriesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/$storeId/settings/store': {
      id: '/_authenticated/$storeId/settings/store'
      path: '/store'
      fullPath: '/$storeId/settings/store'
      preLoaderRoute: typeof SettingsStoreRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/$storeId/settings/stock-locations': {
      id: '/_authenticated/$storeId/settings/stock-locations'
      path: '/stock-locations'
      fullPath: '/$storeId/settings/stock-locations'
      preLoaderRoute: typeof SettingsStockLocationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/$storeId/settings/staff': {
      id: '/_authenticated/$storeId/settings/staff'
      path: '/staff'
      fullPath: '/$storeId/settings/staff'
      preLoaderRoute: typeof SettingsStaffRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/$storeId/settings/profile': {
      id: '/_authenticated/$storeId/settings/profile'
      path: '/profile'
      fullPath: '/$storeId/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/$storeId/settings/payment-methods': {
      id: '/_authenticated/$storeId/settings/payment-methods'
      path: '/payment-methods'
      fullPath: '/$storeId/settings/payment-methods'
      preLoaderRoute: typeof SettingsPaymentMethodsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/$storeId/settings/markets': {
      id: '/_authenticated/$storeId/settings/markets'
      path: '/markets'
      fullPath: '/$storeId/settings/markets'
      preLoaderRoute: typeof SettingsMarketsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/$storeId/settings/emails': {
      id: '/_authenticated/$storeId/settings/emails'
      path: '/emails'
      fullPath: '/$storeId/settings/emails'
      preLoaderRoute: typeof SettingsEmailsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/$storeId/settings/custom-field-definitions': {
      id: '/_authenticated/$storeId/settings/custom-field-definitions'
      path: '/custom-field-definitions'
      fullPath: '/$storeId/settings/custom-field-definitions'
      preLoaderRoute: typeof SettingsCustomFieldDefinitionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/$storeId/settings/channels': {
      id: '/_authenticated/$storeId/settings/channels'
      path: '/channels'
      fullPath: '/$storeId/settings/channels'
      preLoaderRoute: typeof SettingsChannelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/$storeId/settings/api-keys': {
      id: '/_authenticated/$storeId/settings/api-keys'
      path: '/api-keys'
      fullPath: '/$storeId/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/$storeId/settings/allowed-origins': {
      id: '/_authenticated/$storeId/settings/allowed-origins'
      path: '/allowed-origins'
      fullPath: '/$storeId/settings/allowed-origins'
      preLoaderRoute: typeof SettingsAllowedOriginsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/$storeId/promotions/new': {
      id: '/_authenticated/$storeId/promotions/new'
      path: '/promotions/new'
      fullPath: '/$storeId/promotions/new'
      preLoaderRoute: typeof PromotionsNewRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/promotions/gift-cards': {
      id: '/_authenticated/$storeId/promotions/gift-cards'
      path: '/promotions/gift-cards'
      fullPath: '/$storeId/promotions/gift-cards'
      preLoaderRoute: typeof PromotionsGiftCardsRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/promotions/$promotionId': {
      id: '/_authenticated/$storeId/promotions/$promotionId'
      path: '/promotions/$promotionId'
      fullPath: '/$storeId/promotions/$promotionId'
      preLoaderRoute: typeof PromotionsPromotionIdRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/transfers': {
      id: '/_authenticated/$storeId/products/transfers'
      path: '/products/transfers'
      fullPath: '/$storeId/products/transfers'
      preLoaderRoute: typeof ProductsTransfersRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/options': {
      id: '/_authenticated/$storeId/products/options'
      path: '/products/options'
      fullPath: '/$storeId/products/options'
      preLoaderRoute: typeof ProductsOptionsRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/new': {
      id: '/_authenticated/$storeId/products/new'
      path: '/products/new'
      fullPath: '/$storeId/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/$productId': {
      id: '/_authenticated/$storeId/products/$productId'
      path: '/products/$productId'
      fullPath: '/$storeId/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/orders/new': {
      id: '/_authenticated/$storeId/orders/new'
      path: '/orders/new'
      fullPath: '/$storeId/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/orders/drafts': {
      id: '/_authenticated/$storeId/orders/drafts'
      path: '/orders/drafts'
      fullPath: '/$storeId/orders/drafts'
      preLoaderRoute: typeof OrdersDraftsRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/orders/$orderId': {
      id: '/_authenticated/$storeId/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/$storeId/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/customers/groups': {
      id: '/_authenticated/$storeId/customers/groups'
      path: '/customers/groups'
      fullPath: '/$storeId/customers/groups'
      preLoaderRoute: typeof CustomersGroupsRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/customers/$customerId': {
      id: '/_authenticated/$storeId/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/$storeId/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/brands/$brandId': {
      id: '/_authenticated/$storeId/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/$storeId/brands/$brandId'
      preLoaderRoute: typeof BrandsDotbrandIdRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/settings/webhooks/': {
      id: '/_authenticated/$storeId/settings/webhooks/'
      path: '/webhooks'
      fullPath: '/$storeId/settings/webhooks/'
      preLoaderRoute: typeof SettingsWebhooksIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/$storeId/products/price-lists/': {
      id: '/_authenticated/$storeId/products/price-lists/'
      path: '/products/price-lists'
      fullPath: '/$storeId/products/price-lists/'
      preLoaderRoute: typeof ProductsPriceListsIndexRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/categories/': {
      id: '/_authenticated/$storeId/products/categories/'
      path: '/products/categories'
      fullPath: '/$storeId/products/categories/'
      preLoaderRoute: typeof ProductsCategoriesIndexRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/settings/webhooks/$webhookEndpointId': {
      id: '/_authenticated/$storeId/settings/webhooks/$webhookEndpointId'
      path: '/webhooks/$webhookEndpointId'
      fullPath: '/$storeId/settings/webhooks/$webhookEndpointId'
      preLoaderRoute: typeof SettingsWebhooksWebhookEndpointIdRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/$storeId/products/price-lists/new': {
      id: '/_authenticated/$storeId/products/price-lists/new'
      path: '/products/price-lists/new'
      fullPath: '/$storeId/products/price-lists/new'
      preLoaderRoute: typeof ProductsPriceListsNewRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/categories/new': {
      id: '/_authenticated/$storeId/products/categories/new'
      path: '/products/categories/new'
      fullPath: '/$storeId/products/categories/new'
      preLoaderRoute: typeof ProductsCategoriesNewRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/categories/$categoryId': {
      id: '/_authenticated/$storeId/products/categories/$categoryId'
      path: '/products/categories/$categoryId'
      fullPath: '/$storeId/products/categories/$categoryId'
      preLoaderRoute: typeof ProductsCategoriesCategoryIdRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/products/price-lists/$priceListId/': {
      id: '/_authenticated/$storeId/products/price-lists/$priceListId/'
      path: '/products/price-lists/$priceListId'
      fullPath: '/$storeId/products/price-lists/$priceListId/'
      preLoaderRoute: typeof ProductsPriceListsPriceListIdIndexRouteImport
      parentRoute: typeof authenticatedStoreIdRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsAllowedOriginsRoute: typeof SettingsAllowedOriginsRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsChannelsRoute: typeof SettingsChannelsRoute
  SettingsCustomFieldDefinitionsRoute: typeof SettingsCustomFieldDefinitionsRoute
  SettingsEmailsRoute: typeof SettingsEmailsRoute
  SettingsMarketsRoute: typeof SettingsMarketsRoute
  SettingsPaymentMethodsRoute: typeof SettingsPaymentMethodsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsStaffRoute: typeof SettingsStaffRoute
  SettingsStockLocationsRoute: typeof SettingsStockLocationsRoute
  SettingsStoreRoute: typeof SettingsStoreRoute
  SettingsTaxCategoriesRoute: typeof SettingsTaxCategoriesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsWebhooksWebhookEndpointIdRoute: typeof SettingsWebhooksWebhookEndpointIdRoute
  SettingsWebhooksIndexRoute: typeof SettingsWebhooksIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAllowedOriginsRoute: SettingsAllowedOriginsRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsChannelsRoute: SettingsChannelsRoute,
  SettingsCustomFieldDefinitionsRoute: SettingsCustomFieldDefinitionsRoute,
  SettingsEmailsRoute: SettingsEmailsRoute,
  SettingsMarketsRoute: SettingsMarketsRoute,
  SettingsPaymentMethodsRoute: SettingsPaymentMethodsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsStaffRoute: SettingsStaffRoute,
  SettingsStockLocationsRoute: SettingsStockLocationsRoute,
  SettingsStoreRoute: SettingsStoreRoute,
  SettingsTaxCategoriesRoute: SettingsTaxCategoriesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsWebhooksWebhookEndpointIdRoute:
    SettingsWebhooksWebhookEndpointIdRoute,
  SettingsWebhooksIndexRoute: SettingsWebhooksIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface authenticatedStoreIdRouteChildren {
  SplatRoute: typeof SplatRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  IndexRoute: typeof IndexRoute
  BrandsDotbrandIdRoute: typeof BrandsDotbrandIdRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  CustomersGroupsRoute: typeof CustomersGroupsRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersDraftsRoute: typeof OrdersDraftsRoute
  OrdersNewRoute: typeof OrdersNewRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsNewRoute: typeof ProductsNewRoute
  ProductsOptionsRoute: typeof ProductsOptionsRoute
  ProductsTransfersRoute: typeof ProductsTransfersRoute
  PromotionsPromotionIdRoute: typeof PromotionsPromotionIdRoute
  PromotionsGiftCardsRoute: typeof PromotionsGiftCardsRoute
  PromotionsNewRoute: typeof PromotionsNewRoute
  BrandsDotindexRoute: typeof BrandsDotindexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  PromotionsIndexRoute: typeof PromotionsIndexRoute
  ProductsCategoriesCategoryIdRoute: typeof ProductsCategoriesCategoryIdRoute
  ProductsCategoriesNewRoute: typeof ProductsCategoriesNewRoute
  ProductsPriceListsNewRoute: typeof ProductsPriceListsNewRoute
  ProductsCategoriesIndexRoute: typeof ProductsCategoriesIndexRoute
  ProductsPriceListsIndexRoute: typeof ProductsPriceListsIndexRoute
  ProductsPriceListsPriceListIdIndexRoute: typeof ProductsPriceListsPriceListIdIndexRoute
}

const authenticatedStoreIdRouteChildren: authenticatedStoreIdRouteChildren = {
  SplatRoute: SplatRoute,
  SettingsRoute: SettingsRouteWithChildren,
  IndexRoute: IndexRoute,
  BrandsDotbrandIdRoute: BrandsDotbrandIdRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  CustomersGroupsRoute: CustomersGroupsRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersDraftsRoute: OrdersDraftsRoute,
  OrdersNewRoute: OrdersNewRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsNewRoute: ProductsNewRoute,
  ProductsOptionsRoute: ProductsOptionsRoute,
  ProductsTransfersRoute: ProductsTransfersRoute,
  PromotionsPromotionIdRoute: PromotionsPromotionIdRoute,
  PromotionsGiftCardsRoute: PromotionsGiftCardsRoute,
  PromotionsNewRoute: PromotionsNewRoute,
  BrandsDotindexRoute: BrandsDotindexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  PromotionsIndexRoute: PromotionsIndexRoute,
  ProductsCategoriesCategoryIdRoute: ProductsCategoriesCategoryIdRoute,
  ProductsCategoriesNewRoute: ProductsCategoriesNewRoute,
  ProductsPriceListsNewRoute: ProductsPriceListsNewRoute,
  ProductsCategoriesIndexRoute: ProductsCategoriesIndexRoute,
  ProductsPriceListsIndexRoute: ProductsPriceListsIndexRoute,
  ProductsPriceListsPriceListIdIndexRoute:
    ProductsPriceListsPriceListIdIndexRoute,
}

const authenticatedStoreIdRouteWithChildren =
  authenticatedStoreIdRoute._addFileChildren(authenticatedStoreIdRouteChildren)

interface authenticatedRouteChildren {
  authenticatedStoreIdRoute: typeof authenticatedStoreIdRouteWithChildren
  authenticatedIndexRoute: typeof authenticatedIndexRoute
}

const authenticatedRouteChildren: authenticatedRouteChildren = {
  authenticatedStoreIdRoute: authenticatedStoreIdRouteWithChildren,
  authenticatedIndexRoute: authenticatedIndexRoute,
}

const authenticatedRouteWithChildren = authenticatedRoute._addFileChildren(
  authenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRoute: authenticatedRouteWithChildren,
  loginRoute: loginRoute,
  acceptInvitationDotinvitationIdRoute: acceptInvitationDotinvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
