module Spree
  module Emails
    # Writes the reference of every variable Spree's email templates receive,
    # read from the serializers that produce them, so it cannot drift from
    # what the templates actually get.
    class VariableReference
      MAX_DEPTH = 2

      # Which variables each email's template receives, besides `store` and `locale`.
      EMAILS = {
        'spree/order_mailer/confirm_email' => %w[order resend],
        'spree/order_mailer/cancel_email' => %w[order resend],
        'spree/order_mailer/store_owner_notification_email' => %w[order],
        'spree/order_mailer/payment_link_email' => %w[order payment_url],
        'spree/order_group_mailer/confirm_email' => %w[order_group resend],
        'spree/order_group_mailer/store_owner_notification_email' => %w[order_group],
        'spree/fulfillment_mailer/fulfilled_email' => %w[fulfillment order resend],
        'spree/return_mailer/refunded_email' => %w[return order resend],
        'spree/digital_asset_mailer/files_ready_email' => %w[order downloads resend],
        'spree/customer_mailer/password_reset_email' => %w[customer reset_url],
        'spree/customer_mailer/data_export_email' => %w[download_url expires_at],
        'spree/newsletter_mailer/email_confirmation' => %w[confirmation_url],
        'spree/company_mailer/invitation_email' => %w[company accept_url],
        'spree/seller_mailer/approved_email' => %w[seller dashboard_url],
        'spree/seller_mailer/suspended_email' => %w[seller dashboard_url],
        'spree/seller_mailer/rejected_email' => %w[seller dashboard_url],
        'spree/admin_user_mailer/password_reset_email' => %w[user reset_url],
        'spree/seller_user_mailer/password_reset_email' => %w[user reset_url],
        'spree/invitation_mailer/invitation_email' => %w[invitation accept_url],
        'spree/invitation_mailer/invitation_accepted' => %w[invitation],
        'spree/import_mailer/import_done' => %w[import],
        'spree/export_mailer/export_done' => %w[export],
        'spree/webhook_mailer/endpoint_disabled' => %w[endpoint]
      }.freeze

      VALUES = {
        'resend' => 'True when staff re-sent the email.',
        'locale' => 'The language the email renders in, e.g. `en`.',
        'payment_url' => 'Where the customer pays for the order.',
        'reset_url' => 'The password reset link, carrying its token.',
        'accept_url' => 'The link that accepts the invitation, carrying its token.',
        'confirmation_url' => 'The link that confirms the subscription, carrying its token.',
        'download_url' => "The signed link to the customer's data export.",
        'expires_at' => 'When the data export link stops working.',
        'dashboard_url' => "Where the seller signs in, when it is known.",
        'downloads' => 'Each file bought: `filename`, `url` (carrying its token) and `expires_at`.'
      }.freeze

      # @return [Hash{String => Class}] every serialized variable and the serializer producing it
      def self.objects
        {
          'store' => Spree::Emails::StoreSerializer,
          'order' => Spree::Emails::OrderSerializer,
          'order_group' => Spree::Emails::OrderGroupSerializer,
          'fulfillment' => Spree::Emails::FulfillmentSerializer,
          'return' => Spree::Emails::ReturnSerializer,
          'customer' => Spree.api.customer_serializer,
          'seller' => Spree.api.seller_serializer,
          'company' => Spree.api.company_serializer,
          'user' => Spree::Emails::UserSerializer,
          'invitation' => Spree::Emails::InvitationSerializer,
          'import' => Spree::Emails::ImportSerializer,
          'export' => Spree::Emails::ExportSerializer,
          'endpoint' => Spree::Emails::WebhookEndpointSerializer
        }
      end

      # @return [String] the reference page, as MDX
      def self.call
        new.call
      end

      def call
        [header, emails_section, values_section, objects_section].join("\n")
      end

      private

      def header
        <<~MDX
          ---
          title: Email Template Variables
          sidebarTitle: Template Variables
          description: Every variable Spree's Liquid email templates receive, email by email.
          ---

          {/* Generated by `bin/rails spree:emails:variable_reference` from the email serializers. Do not edit by hand. */}

          Every email template receives `store` and `locale`, plus the variables listed for it below. Spree's templates read these names, not Shopify's: there is no `shop` and no `order.name`. See [Email Templates](/developer/customization/emails) for how to override a template.
        MDX
      end

      def emails_section
        rows = EMAILS.map { |key, names| "| `#{key}` | #{names.map { |name| "`#{name}`" }.join(', ')} |" }

        (["## Emails", '', '| Template | Variables |', '| --- | --- |'] + rows + ['']).join("\n")
      end

      def values_section
        rows = VALUES.map { |name, description| "| `#{name}` | #{description} |" }

        (["## Values", '', '| Variable | What it holds |', '| --- | --- |'] + rows + ['']).join("\n")
      end

      def objects_section
        self.class.objects.map do |name, serializer|
          lines = groups(serializer, name).map { |path, keys| "- `#{path}`: #{keys.map { |key| "`#{key}`" }.join(', ')}" }
          "### `#{name}`\n\n#{lines.join("\n")}\n"
        end.unshift("## Objects\n\nEach object's fields, and the fields of the objects nested in it.\n").join("\n")
      end

      # @return [Array<Array(String, Array<Symbol>)>] each object path with its plain fields
      def groups(serializer, path, depth = 0)
        plain = []
        nested = []

        serializer._attributes.each do |key, attribute|
          next if attribute.is_a?(Alba::ConditionalAttribute)

          nested_class = nested_serializer(attribute)
          if nested_class
            nested.concat(groups(nested_class, "#{path}.#{key}", depth + 1)) if depth < MAX_DEPTH
          else
            plain << key
          end
        end

        [[path, plain]] + nested
      end

      def nested_serializer(attribute)
        return unless attribute.is_a?(Alba::Association)

        resource = attribute.instance_variable_get(:@resource)
        resource = resource.call(nil) if resource.is_a?(Proc)
        resource = resource.constantize if resource.is_a?(String)
        resource if resource.is_a?(Class)
      end
    end
  end
end
