base_locale: en
data:
  yaml:
    write:
      # do not wrap lines at 80 characters
      line_width: -1

# Find translate calls
search:
  paths:
    - '../api/app'
    - '../api/lib'

#### For API v1 only, START ####
  exclude:
    - '../api/app/controllers/spree/api/v1/*'
    - '../api/app/views/*'


ignore_unused:
  # Shown in the custom API authentication guide for apps to reuse.
  - 'spree.api.unauthorized'
