eval_gemfile('../common_spree_dependencies.rb')

gem 'spree_core', path: '../core'
gem 'spree_api', path: '../api'
gem 'spree_emails', path: '../emails'

group :test, :development do
  gem 'selenium-webdriver'
end

gem 'sassc' # needed for payment_icons gem

gemspec
