#!/usr/bin/env bash

source $BASH_ENV

export COMMIT_SHA

COMMIT_SHA="$(git rev-parse --short HEAD)"

export REGISTRY_URL="$BUILDKITE_AGENT_META_DATA_TEST_REGISTRY_URL"

export TEST_CONTAINER="$REGISTRY_URL/spree-test:$COMMIT_SHA"
