eval(Pathname.new(__dir__).join('../shared/dependencies.rb').read)

gem 'builder'
gem 'coderay_bash'
gem 'kramdown'
gem 'mime-types'
gem 'nokogiri'
gem 'nanoc', '3.6.3'
gem 'nanoc-toolbox'
gem 'rake'
gem 'thin'
gem 'yajl-ruby'
gem 'sass'
gem 'bourbon'
gem 'neat'

group :development do
  gem 'listen'
  gem 'rb-fsevent'
  gem 'adsf'
  gem 'fssm'
end

gem 'pry'
