import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import { toJsonSchema } from '../src/config/index'

const PACKAGE_COPY = resolve(import.meta.dirname, '../schemas/spree-config.json')
const DOCS_COPY = resolve(import.meta.dirname, '../../../docs/schemas/spree-config/1.json')

// Both files are generated by `pnpm build` (scripts/emit-config-schema.mjs);
// this fails when a schema change was committed without rebuilding, so the
// schema editors fetch never lags behind the one the CLI validates with.
describe('published JSON Schema', () => {
  it.each([
    ['the package copy', PACKAGE_COPY],
    ['the docs copy', DOCS_COPY],
  ])('%s matches the schema the engine validates with', (_label, file) => {
    expect(JSON.parse(readFileSync(file, 'utf-8'))).toEqual(toJsonSchema())
  })
})
