eval(File.read(File.dirname(__FILE__) + '/../common_spree_dependencies.rb'))

gem 'spree_core', :path => "../core"
gem 'spree_auth', :path => "../auth"

# Until rabl issue #199 is merged...
gem 'rabl', :git => "git://github.com/nesquena/rabl"

gemspec
