require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rspec/core/rake_task'
require 'spree/testing_support/common_rake'

RSpec::Core::RakeTask.new

task default: :spec

desc "Generates a dummy app for testing"
task :test_app do
  ENV['LIB_NAME'] = 'spree/api'

  if ENV['USE_PREBUILT_APP'] == 'true'
    Rake::Task['common:use_prebuilt_app'].invoke('basic')
  else
    Rake::Task['common:test_app'].invoke
  end
end

namespace :rswag do
  namespace :specs do
    desc 'Generate Swagger JSON files from integration specs'
    RSpec::Core::RakeTask.new('swaggerize') do |t|
      t.pattern = ENV.fetch(
        'PATTERN',
        'spec/integration/**/*_spec.rb'
      )

      t.rspec_opts = ['--format Rswag::Specs::SwaggerFormatter', '--order defined']
    end
  end
end
