# encoding: utf-8
require 'rubygems'
begin
  require 'jeweler'
rescue LoadError
  puts "Jeweler not available. Install it with: sudo gem install jeweler"
  exit 1
end

require 'rake'
require 'rake/testtask'
require 'rake/packagetask'
require 'rake/gempackagetask'

Jeweler::Tasks.new do |s|
  s.name = ""
  s.summary = ""
  s.description = s.summary
  s.email = ""
  s.homepage = ""
  s.authors = [""]
  s.add_dependency 'spree_core', ['>= 0.30.0.beta1']
  s.has_rdoc = false
end
Jeweler::GemcutterTasks.new

#TODO: RAILS3 - not clear what extension Rakefile should consist of

